"""Dense relativistic multireference perturbation theory."""

from .spinor_helper import (
    _SpinorERIs,
    check_eri_symmetry,
    init_eris as init_spinor_eris,
)
from .nevpt2_utils import (
    MRPTNumericalWarning,
    adjoint_transition_pdm,
    make_dm1234,
    make_rdm1,
    make_rdm2,
    make_rdm3,
    make_rdm4,
    make_transition_dm1234,
    make_transition_overlap,
    make_transition_rdm1,
    make_transition_rdm2,
    make_transition_rdm3,
    make_transition_rdm4,
    validate_pdms,
    validate_transition_pdms,
)
from .x2cscnevpt2 import (
    WickX2CSCNEVPT2,
    X2CSCNEVPT2,
)
from .x2cficnevpt2 import (
    WickX2CFICNEVPT2,
    WickX2CICNEVPT2,
    WickX2CPCNEVPT2,
    X2CFICNEVPT2,
    X2CICNEVPT2,
    X2CPCNEVPT2,
)
from .x2ccaspt2 import (
    CASPT2IPEAWarning,
    CASPT2IntruderError,
    CASPT2Matrices,
    CASPT2NumericalError,
    CASPT2Result,
    WickX2CCASPT2,
    X2CCASPT2,
    build_caspt2_matrices,
    build_generalized_fock,
    build_ipea_matrix,
    caspt2_from_integrals,
    solve_caspt2,
)
from .x2cicmrcisd import (
    WickX2CICMRCISD,
    X2CICMRCISD,
)
from .x2cicmrrept2 import (
    WickX2CICMRREPT2,
    X2CICMRREPT2,
)
from .x2ctnevpt2 import (
    TMPSNEVPT2,
    X2CTMPSNEVPT2,
    X2CTNEVPT2,
)
from .x2cqdscnevpt2 import (
    QDBlochSCNEVPT2Result,
    QDSCNEVPT2Result,
    WickX2CQDBlochSCNEVPT2,
    WickX2CQDSCNEVPT2,
    X2CQDBlochSCNEVPT2,
    X2CQDSCNEVPT2,
)

__all__ = [
    "_SpinorERIs",
    "check_eri_symmetry",
    "init_spinor_eris",
    "MRPTNumericalWarning",
    "adjoint_transition_pdm",
    "make_dm1234",
    "make_rdm1",
    "make_rdm2",
    "make_rdm3",
    "make_rdm4",
    "make_transition_dm1234",
    "make_transition_overlap",
    "make_transition_rdm1",
    "make_transition_rdm2",
    "make_transition_rdm3",
    "make_transition_rdm4",
    "validate_pdms",
    "validate_transition_pdms",
    "WickX2CSCNEVPT2",
    "X2CSCNEVPT2",
    "WickX2CFICNEVPT2",
    "X2CFICNEVPT2",
    "WickX2CICNEVPT2",
    "X2CICNEVPT2",
    "WickX2CPCNEVPT2",
    "X2CPCNEVPT2",
    "CASPT2IPEAWarning",
    "CASPT2IntruderError",
    "CASPT2Matrices",
    "CASPT2NumericalError",
    "CASPT2Result",
    "WickX2CCASPT2",
    "X2CCASPT2",
    "build_caspt2_matrices",
    "build_generalized_fock",
    "build_ipea_matrix",
    "caspt2_from_integrals",
    "solve_caspt2",
    "WickX2CICMRCISD",
    "X2CICMRCISD",
    "WickX2CICMRREPT2",
    "X2CICMRREPT2",
    "X2CTMPSNEVPT2",
    "X2CTNEVPT2",
    "TMPSNEVPT2",
    "QDSCNEVPT2Result",
    "QDBlochSCNEVPT2Result",
    "WickX2CQDSCNEVPT2",
    "X2CQDSCNEVPT2",
    "WickX2CQDBlochSCNEVPT2",
    "X2CQDBlochSCNEVPT2",
]
