#!/usr/bin/env python
# SPDX-License-Identifier: GPL-3.0-or-later
r"""Dense general-complex-spinor fully internally contracted NEVPT2.

This module implements the single-state, second-order, internally contracted
NEVPT2 equations for the same no-pair X2C spinor Hamiltonian used by
:mod:`x2cscnevpt2`,

.. math::

   H = \sum_{pq} h_{pq} C_p D_q
       + \frac12 \sum_{pqrs} w_{pqrs} C_p C_q D_s D_r,

with unantisymmetrized spinor integrals

.. math::

   w_{pqrs} = \mathrm{eri}_{prqs},\qquad
   \mathrm{eri}_{pqrs}=(pq|rs).

Every index labels one complex spinor. There is no spin summation, spatial
``E1/E2`` operator, Kramers compression, density fitting, Cholesky
factorization, QD coupling, or compressed-RDM approximation.

Terminology
-----------
The approximation implemented here is the internally contracted/partially
contracted variant introduced by Angeli, Cimiraglia, and Malrieu,
J. Chem. Phys. 117, 9138 (2002). Modern program documentation often calls the
same wave-function ansatz *fully internally contracted* (FIC) NEVPT2. The
public class therefore uses the ``FIC`` name, while ``IC`` and ``PC`` aliases
are provided for interoperability.

Operator definition
-------------------
For a fixed set ``eta`` of inactive holes and external particles, let
``O[eta,mu]`` denote all one- and two-body excitation operators that reach the
corresponding first-order interacting subspace. The contracted basis is

.. math::

   |\Phi_{\eta\mu}\rangle = O_{\eta\mu}|\Psi_0\rangle.

The projected source uses the shared, independently audited NEVPT2 definition,

.. math::

   |B_\eta\rangle = P_\eta H|\Psi_0\rangle.

Block2 Wick algebra generates, directly in the raw SGF 1--4 RDM convention,

.. math::

   S^\eta_{\mu\nu}
     &= \langle\Psi_0|O_{\eta\mu}^\dagger O_{\eta\nu}|\Psi_0\rangle,\\
   K^\eta_{\mu\nu}
     &= \langle\Psi_0|O_{\eta\mu}^\dagger
        [H_{\rm act}^{D},O_{\eta\nu}]|\Psi_0\rangle,\\
   b^\eta_\mu
     &= \langle\Psi_0|O_{\eta\mu}^\dagger B_\eta|\Psi_0\rangle.

The complete Dyall matrix in that block is

.. math::

   A^\eta = K^\eta + \Delta_\eta^{\rm orb} S^\eta
           = \langle\Phi_\eta|(H_D-E_0)|\Phi_\eta\rangle.

After canonical orthogonalization of the nonorthogonal contracted basis, the
linear problem is solved in its positive, non-null metric subspace and the
energy is

.. math::

   E^{(2)}_\eta = - (b^\eta)^\dagger (A^\eta)^+ b^\eta.

The explicit one-body components in the ``ir``, ``r``, and ``i`` spaces make
the basis complete even in limiting active-electron occupations. They are
usually linearly dependent on part of the two-body contracted basis; metric
canonicalization removes that redundancy without changing the physical span.

The implementation constructs the overlap, right and left Dyall-commutator
matrices and audits their exact Hermitian/eigenstate relations before
projecting finite numerical noise onto the required Hermitian matrices.
Non-finite values, a physically negative metric, a source outside the retained
metric range, or a non-positive Dyall eigenvalue remain hard errors.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import gc
import itertools
import time

import numpy as np
from pyscf import lib
from pyscf.lib import logger

try:
    from . import nevpt2_utils as _utils
    from . import spinor_helper
except ImportError:  # pragma: no cover - permits running a repository snapshot
    import nevpt2_utils as _utils
    import spinor_helper


__all__ = [
    "SUBSPACE_ORDER",
    "WickX2CFICNEVPT2",
    "X2CFICNEVPT2",
    "WickX2CICNEVPT2",
    "X2CICNEVPT2",
    "WickX2CPCNEVPT2",
    "X2CPCNEVPT2",
    "dump_fic_wick_equations",
]


SUBSPACE_ORDER = _utils.SUBSPACE_ORDER


@dataclass(frozen=True)
class _ICComponent:
    """One one-/two-body operator family in an IC excitation class."""

    name: str
    expression: str
    ket_active: tuple[str, ...]
    bra_active: tuple[str, ...]
    active_pairs: tuple[tuple[int, int], ...] = ()

    def __post_init__(self):
        if len(self.ket_active) != len(self.bra_active):
            raise ValueError("ket and bra active-index ranks must agree")
        if len(set(self.ket_active)) != len(self.ket_active):
            raise ValueError("ket active labels must be distinct")
        if len(set(self.bra_active)) != len(self.bra_active):
            raise ValueError("bra active labels must be distinct")
        for left, right in self.active_pairs:
            if not (0 <= left < right < len(self.ket_active)):
                raise ValueError("invalid active-pair restriction")


# Complete spin-orbital FOIS generated by a one-/two-body Hamiltonian.
# Same-kind active pairs are stored once. Singles in the semi-internal spaces
# are explicit; exact metric-null-space removal handles their particle-number
# redundancies.
_IC_COMPONENTS: dict[str, tuple[_ICComponent, ...]] = {
    "ijrs": (
        _ICComponent("double", "C[r] C[s] D[j] D[i]", (), ()),
    ),
    "rsi": (
        _ICComponent(
            "double", "C[r] C[s] D[a] D[i]", ("a",), ("p",)
        ),
    ),
    "ijr": (
        _ICComponent(
            "double", "C[r] C[a] D[j] D[i]", ("a",), ("p",)
        ),
    ),
    "rs": (
        _ICComponent(
            "double",
            "C[r] C[s] D[b] D[a]",
            ("a", "b"),
            ("p", "q"),
            ((0, 1),),
        ),
    ),
    "ij": (
        _ICComponent(
            "double",
            "C[a] C[b] D[j] D[i]",
            ("a", "b"),
            ("p", "q"),
            ((0, 1),),
        ),
    ),
    "ir": (
        _ICComponent("single", "C[r] D[i]", (), ()),
        _ICComponent(
            "double",
            "C[r] C[a] D[b] D[i]",
            ("a", "b"),
            ("p", "q"),
        ),
    ),
    "r": (
        _ICComponent("single", "C[r] D[a]", ("a",), ("p",)),
        _ICComponent(
            "double",
            "C[r] C[a] D[c] D[b]",
            ("a", "b", "c"),
            ("p", "q", "g"),
            ((1, 2),),
        ),
    ),
    "i": (
        _ICComponent("single", "C[a] D[i]", ("a",), ("p",)),
        _ICComponent(
            "double",
            "C[a] C[b] D[c] D[i]",
            ("a", "b", "c"),
            ("p", "q", "g"),
            ((0, 1),),
        ),
    ),
}


_FREE_PAIRS = _utils._PAIR_RESTRICTIONS


@dataclass(frozen=True)
class _FICEquationBundle:
    rhs_code: dict[tuple[str, str], str]
    metric_code: dict[tuple[str, str, str], str]
    right_code: dict[tuple[str, str, str], str]
    left_code: dict[tuple[str, str, str], str]
    rhs_text: dict[tuple[str, str], str]
    metric_text: dict[tuple[str, str, str], str]
    right_text: dict[tuple[str, str, str], str]
    left_text: dict[tuple[str, str, str], str]


def _replace_active_labels(expression: str, mapping: dict[str, str]) -> str:
    """Replace only bracketed one-index operator labels."""

    result = expression
    for source, target in mapping.items():
        result = result.replace(f"[{source}]", f"[{target}]")
    return result


def _target(parse_tensor, name: str, labels: tuple[str, ...]):
    return parse_tensor(f"{name}[{''.join(labels)}]")


@lru_cache(maxsize=1)
def _compile_fic_equations() -> _FICEquationBundle:
    """Generate all FIC RHS, metric, and Dyall-matrix contractions."""

    types = _utils._block2_wick_types()
    parse, parse_tensor = _utils._wick_parsers(types)

    h_dyall_active = parse("SUM <ab> h[ab] C[a] D[b]")
    h_dyall_active += parse(
        "0.5 SUM <abcd> w[abcd] C[a] C[b] D[d] D[c]"
    )

    rhs_code = {}
    metric_code = {}
    right_code = {}
    left_code = {}
    rhs_text = {}
    metric_text = {}
    right_text = {}
    left_text = {}

    for key in SUBSPACE_ORDER:
        source = parse(_utils._PERTURBER_EXPRESSIONS[key])
        components = _IC_COMPONENTS[key]
        ket_expressions = {
            component.name: parse(component.expression)
            for component in components
        }
        bra_expressions = {}
        for component in components:
            mapped = _replace_active_labels(
                component.expression,
                dict(zip(component.ket_active, component.bra_active)),
            )
            bra_expressions[component.name] = parse(mapped).conjugate()

        free_labels = tuple(key)
        for bra_component in components:
            bra = bra_expressions[bra_component.name]
            rhs = _utils._lower_active_operators(
                _utils._vacuum_reduce(bra * source), types
            )
            labels = free_labels + bra_component.bra_active
            rhs_code[(key, bra_component.name)] = rhs.to_einsum(
                _target(parse_tensor, "rhs", labels)
            )
            rhs_text[(key, bra_component.name)] = repr(rhs)

            for ket_component in components:
                ket = ket_expressions[ket_component.name]
                pair = (key, bra_component.name, ket_component.name)
                labels = (
                    free_labels
                    + bra_component.bra_active
                    + ket_component.ket_active
                )

                metric = _utils._lower_active_operators(
                    _utils._vacuum_reduce(bra * ket), types
                )

                # [one-/two-body H_D, one-/two-body O] is connected and
                # contains at most three creation and three annihilation
                # operators. This is the same max_unctr policy used by SC.
                connected_right = (
                    (h_dyall_active ^ ket).expand(6).simplify()
                )
                right = _utils._lower_active_operators(
                    _utils._vacuum_reduce(bra * connected_right), types
                )
                connected_left = (
                    (bra ^ h_dyall_active).expand(6).simplify()
                )
                left = _utils._lower_active_operators(
                    _utils._vacuum_reduce(connected_left * ket), types
                )

                metric_code[pair] = metric.to_einsum(
                    _target(parse_tensor, "metric", labels)
                )
                right_code[pair] = right.to_einsum(
                    _target(parse_tensor, "right", labels)
                )
                left_code[pair] = left.to_einsum(
                    _target(parse_tensor, "left", labels)
                )
                metric_text[pair] = repr(metric)
                right_text[pair] = repr(right)
                left_text[pair] = repr(left)

    return _FICEquationBundle(
        rhs_code=rhs_code,
        metric_code=metric_code,
        right_code=right_code,
        left_code=left_code,
        rhs_text=rhs_text,
        metric_text=metric_text,
        right_text=right_text,
        left_text=left_text,
    )


def dump_fic_wick_equations(filename: str | None = None) -> str:
    """Return, and optionally write, every generated FIC Wick equation."""

    equations = _compile_fic_equations()
    sections = []
    for key in SUBSPACE_ORDER:
        sections.append(f"[{key}] source\n{_utils._PERTURBER_EXPRESSIONS[key]}")
        for component in _IC_COMPONENTS[key]:
            sections.extend(
                (
                    f"[{key}/{component.name}] basis\n{component.expression}",
                    f"[{key}/{component.name}] RHS expression\n"
                    f"{equations.rhs_text[(key, component.name)]}",
                    f"[{key}/{component.name}] RHS einsum\n"
                    f"{equations.rhs_code[(key, component.name)]}",
                )
            )
        for bra_component in _IC_COMPONENTS[key]:
            for ket_component in _IC_COMPONENTS[key]:
                pair = (key, bra_component.name, ket_component.name)
                title = f"{key}/{bra_component.name},{ket_component.name}"
                sections.extend(
                    (
                        f"[{title}] metric expression\n"
                        f"{equations.metric_text[pair]}",
                        f"[{title}] metric einsum\n"
                        f"{equations.metric_code[pair]}",
                        f"[{title}] right Dyall expression\n"
                        f"{equations.right_text[pair]}",
                        f"[{title}] right Dyall einsum\n"
                        f"{equations.right_code[pair]}",
                        f"[{title}] left Dyall expression\n"
                        f"{equations.left_text[pair]}",
                        f"[{title}] left Dyall einsum\n"
                        f"{equations.left_code[pair]}",
                    )
                )
    text = "\n\n".join(sections) + "\n"
    if filename is not None:
        with open(filename, "w", encoding="utf-8") as handle:
            handle.write(text)
    return text


_warn_numerical = _utils._warn_numerical
_maximum_abs = _utils._maximum_abs
_finite_nonnegative = _utils._finite_nonnegative


def _label_dimension(label: str, eris) -> int:
    if label in "ij":
        return int(eris.ncore)
    if label in "rs":
        return int(eris.nvirt)
    if label in "abcdefghpq":
        return int(eris.ncas)
    raise ValueError(f"unknown Wick index label {label!r}")


def _shape_for_labels(labels: tuple[str, ...], eris) -> tuple[int, ...]:
    return tuple(_label_dimension(label, eris) for label in labels)


@lru_cache(maxsize=None)
def _active_selection(
    ncas: int,
    rank: int,
    restrictions: tuple[tuple[int, int], ...],
) -> tuple[np.ndarray, tuple[tuple[int, ...], ...]]:
    """Flat full-tensor indices of the independent active basis."""

    ncas = int(ncas)
    rank = int(rank)
    if rank == 0:
        return np.array([0], dtype=np.int64), ((),)
    if ncas == 0:
        return np.empty(0, dtype=np.int64), ()

    tuples = tuple(
        indices
        for indices in itertools.product(range(ncas), repeat=rank)
        if all(indices[left] < indices[right] for left, right in restrictions)
    )
    if not tuples:
        return np.empty(0, dtype=np.int64), ()
    coordinates = np.asarray(tuples, dtype=np.int64).T
    flat = np.ravel_multi_index(coordinates, (ncas,) * rank)
    return np.asarray(flat, dtype=np.int64), tuples


def _component_selection(component: _ICComponent, ncas: int):
    return _active_selection(
        int(ncas), len(component.ket_active), component.active_pairs
    )[0]


def _component_dimension(component: _ICComponent, ncas: int) -> int:
    return int(len(_component_selection(component, ncas)))


def _iter_free_tuples(key: str, eris):
    shape = _shape_for_labels(tuple(key), eris)
    if any(size == 0 for size in shape):
        return
    for indices in itertools.product(*(range(size) for size in shape)):
        if all(
            indices[left] < indices[right]
            for left, right in _FREE_PAIRS[key]
        ):
            yield indices


def _orbital_gap_at(
    key: str, indices, core_energy, virtual_energy
) -> float:
    value = 0.0
    for label, index in zip(key, indices):
        if label in "ij":
            value -= float(core_energy[index])
        else:
            value += float(virtual_energy[index])
    return float(value)


def _execute_tensor(
    code,
    target_name,
    labels,
    base_context,
    wick_globals,
    dtype,
    eris,
):
    result = np.zeros(_shape_for_labels(labels, eris), dtype=dtype)
    context = dict(base_context)
    context[target_name] = result
    exec(code, wick_globals, context)
    return result


def _selected_vector(tensor, free_indices, component, ncas):
    block = np.asarray(tensor[free_indices])
    full_dimension = int(ncas) ** len(component.bra_active)
    selection = _component_selection(component, ncas)
    return block.reshape(full_dimension)[selection]


def _selected_matrix(
    tensor,
    free_indices,
    bra_component,
    ket_component,
    ncas,
):
    block = np.asarray(tensor[free_indices])
    nbra_full = int(ncas) ** len(bra_component.bra_active)
    nket_full = int(ncas) ** len(ket_component.ket_active)
    matrix = block.reshape(nbra_full, nket_full)
    rows = _component_selection(bra_component, ncas)
    columns = _component_selection(ket_component, ncas)
    return matrix[np.ix_(rows, columns)]


def _assemble_vector(rhs_tensors, free_indices, components, ncas):
    pieces = [
        _selected_vector(
            rhs_tensors[component.name], free_indices, component, ncas
        )
        for component in components
    ]
    return np.concatenate(pieces) if pieces else np.empty(0, dtype=complex)


def _assemble_matrix(tensors, free_indices, components, ncas):
    rows = []
    for bra_component in components:
        row = []
        for ket_component in components:
            row.append(
                _selected_matrix(
                    tensors[(bra_component.name, ket_component.name)],
                    free_indices,
                    bra_component,
                    ket_component,
                    ncas,
                )
            )
        rows.append(row)
    return np.block(rows) if rows else np.empty((0, 0), dtype=complex)


def _gate_relation(error, scale, *, atol, rtol, message):
    tolerance = float(atol + rtol * max(1.0, float(scale)))
    passed = bool(error <= tolerance)
    if not passed:
        _warn_numerical(
            f"{message}: error={error:.3e}, tolerance={tolerance:.3e}"
        )
    return passed, tolerance


def _solve_fic_block(
    metric,
    right_active,
    left_active,
    rhs,
    orbital_gap,
    *,
    root,
    subspace,
    free_indices,
    metric_atol,
    metric_rtol,
    metric_rcond,
    matrix_atol,
    matrix_rtol,
    null_rhs_atol,
    null_rhs_rtol,
    denominator_tol,
):
    """Solve one fixed-nonactive-index IC block in a canonical metric basis."""

    metric = np.asarray(metric, dtype=np.complex128)
    right_active = np.asarray(right_active, dtype=np.complex128)
    left_active = np.asarray(left_active, dtype=np.complex128)
    rhs = np.asarray(rhs, dtype=np.complex128)

    dimension = rhs.size
    expected = (dimension, dimension)
    if (
        metric.shape != expected
        or right_active.shape != expected
        or left_active.shape != expected
    ):
        raise ValueError(
            f"root {root} subspace {subspace} block {free_indices}: "
            "contracted matrices and RHS have inconsistent dimensions"
        )
    if not (
        np.all(np.isfinite(metric))
        and np.all(np.isfinite(right_active))
        and np.all(np.isfinite(left_active))
        and np.all(np.isfinite(rhs))
        and np.isfinite(orbital_gap)
    ):
        raise FloatingPointError(
            f"root {root} subspace {subspace} block {free_indices}: "
            "non-finite contracted data"
        )

    if dimension == 0:
        return 0.0, {"dimension": 0, "metric_rank": 0, "energy": 0.0}

    metric_scale = _maximum_abs(metric)
    metric_hermiticity_error = _maximum_abs(metric - metric.conj().T)
    metric_gate, metric_hermiticity_tolerance = _gate_relation(
        metric_hermiticity_error,
        metric_scale,
        atol=matrix_atol,
        rtol=matrix_rtol,
        message=(
            f"root {root} subspace {subspace} block {free_indices}: "
            "contracted metric is not Hermitian"
        ),
    )
    metric_h = 0.5 * (metric + metric.conj().T)

    active_consistency_error = _maximum_abs(right_active - left_active)
    active_scale = max(_maximum_abs(right_active), _maximum_abs(left_active))
    active_consistency_gate, active_consistency_tolerance = _gate_relation(
        active_consistency_error,
        active_scale,
        atol=matrix_atol,
        rtol=matrix_rtol,
        message=(
            f"root {root} subspace {subspace} block {free_indices}: "
            "left/right Dyall commutator matrices disagree"
        ),
    )
    active_reconciled = 0.5 * (right_active + left_active)
    active_hermiticity_error = _maximum_abs(
        active_reconciled - active_reconciled.conj().T
    )
    active_hermiticity_gate, active_hermiticity_tolerance = _gate_relation(
        active_hermiticity_error,
        _maximum_abs(active_reconciled),
        atol=matrix_atol,
        rtol=matrix_rtol,
        message=(
            f"root {root} subspace {subspace} block {free_indices}: "
            "reconciled active Dyall matrix is not Hermitian"
        ),
    )
    active_h = 0.5 * (active_reconciled + active_reconciled.conj().T)

    dyall = active_h + float(orbital_gap) * metric_h
    dyall_hermiticity_error = _maximum_abs(dyall - dyall.conj().T)
    dyall_h = 0.5 * (dyall + dyall.conj().T)

    metric_eigenvalues, metric_eigenvectors = np.linalg.eigh(metric_h)
    metric_maximum = float(np.max(metric_eigenvalues, initial=0.0))
    metric_negative_tolerance = (
        metric_atol + metric_rtol * max(1.0, abs(metric_maximum))
    )
    metric_minimum = float(np.min(metric_eigenvalues, initial=0.0))
    if metric_minimum < -metric_negative_tolerance:
        raise FloatingPointError(
            f"root {root} subspace {subspace} block {free_indices}: "
            f"contracted metric has a negative eigenvalue {metric_minimum:.3e}"
        )

    metric_cutoff = max(
        float(metric_atol),
        float(metric_rcond) * max(metric_maximum, 0.0),
    )
    retained = metric_eigenvalues > metric_cutoff
    metric_rank = int(np.count_nonzero(retained))
    transformed_rhs_all = metric_eigenvectors.conj().T @ rhs
    discarded_rhs_norm = float(np.linalg.norm(transformed_rhs_all[~retained]))
    rhs_norm = float(np.linalg.norm(rhs))
    null_rhs_limit = float(
        null_rhs_atol + null_rhs_rtol * max(1.0, rhs_norm)
    )
    if discarded_rhs_norm > null_rhs_limit:
        raise FloatingPointError(
            f"root {root} subspace {subspace} block {free_indices}: source "
            f"has norm {discarded_rhs_norm:.3e} in the discarded metric "
            f"null space (limit {null_rhs_limit:.3e})"
        )

    common_diagnostics = {
        "dimension": int(dimension),
        "metric_rank": metric_rank,
        "metric_minimum_eigenvalue": metric_minimum,
        "metric_maximum_eigenvalue": metric_maximum,
        "metric_cutoff": metric_cutoff,
        "discarded_rhs_norm": discarded_rhs_norm,
        "discarded_rhs_limit": null_rhs_limit,
        "metric_hermiticity_error": metric_hermiticity_error,
        "metric_hermiticity_tolerance": metric_hermiticity_tolerance,
        "metric_hermiticity_gate_passed": metric_gate,
        "active_left_right_error": active_consistency_error,
        "active_left_right_tolerance": active_consistency_tolerance,
        "active_left_right_gate_passed": active_consistency_gate,
        "active_hermiticity_error": active_hermiticity_error,
        "active_hermiticity_tolerance": active_hermiticity_tolerance,
        "active_hermiticity_gate_passed": active_hermiticity_gate,
        "dyall_hermiticity_error": dyall_hermiticity_error,
    }
    if metric_rank == 0:
        return 0.0, {**common_diagnostics, "energy": 0.0}

    retained_values = metric_eigenvalues[retained]
    orthogonalizer = metric_eigenvectors[:, retained] / np.sqrt(
        retained_values
    )[None, :]
    dyall_orth = orthogonalizer.conj().T @ dyall_h @ orthogonalizer
    dyall_orth_hermiticity_error = _maximum_abs(
        dyall_orth - dyall_orth.conj().T
    )
    dyall_orth = 0.5 * (dyall_orth + dyall_orth.conj().T)
    rhs_orth = orthogonalizer.conj().T @ rhs

    denominator_eigenvalues, denominator_vectors = np.linalg.eigh(
        dyall_orth
    )
    denominator_minimum = float(np.min(denominator_eigenvalues))
    denominator_maximum = float(np.max(denominator_eigenvalues))
    if denominator_minimum <= denominator_tol:
        raise FloatingPointError(
            f"root {root} subspace {subspace} block {free_indices}: "
            "non-positive or near-zero internally contracted Dyall "
            f"eigenvalue {denominator_minimum:.3e}"
        )

    projected_rhs = denominator_vectors.conj().T @ rhs_orth
    response_orth = denominator_vectors @ (
        projected_rhs / denominator_eigenvalues
    )
    residual = dyall_orth @ response_orth - rhs_orth
    residual_norm = float(np.linalg.norm(residual))
    residual_limit = float(
        matrix_atol
        + matrix_rtol * max(1.0, float(np.linalg.norm(rhs_orth)))
    )
    if residual_norm > residual_limit:
        raise FloatingPointError(
            f"root {root} subspace {subspace} block {free_indices}: "
            f"contracted linear-solve residual {residual_norm:.3e} "
            f"exceeds {residual_limit:.3e}"
        )

    energy_complex = -np.vdot(rhs_orth, response_orth)
    if not np.isfinite(energy_complex):
        raise FloatingPointError(
            f"root {root} subspace {subspace} block {free_indices}: "
            "non-finite second-order energy"
        )
    energy_imaginary = float(abs(energy_complex.imag))
    energy_reality_limit = float(
        matrix_atol
        + matrix_rtol * max(1.0, abs(float(energy_complex.real)))
    )
    if energy_imaginary > energy_reality_limit:
        _warn_numerical(
            f"root {root} subspace {subspace} block {free_indices}: "
            f"FIC energy has imaginary part {energy_imaginary:.3e}; "
            "using the Hermitian-projected real value"
        )
    energy = float(energy_complex.real)
    if energy > energy_reality_limit:
        _warn_numerical(
            f"root {root} subspace {subspace} block {free_indices}: "
            f"FIC contribution is positive ({energy:.3e})"
        )

    return energy, {
        **common_diagnostics,
        "orthogonal_dyall_hermiticity_error": (
            dyall_orth_hermiticity_error
        ),
        "denominator_minimum": denominator_minimum,
        "denominator_maximum": denominator_maximum,
        "denominator_condition_number": (
            denominator_maximum / denominator_minimum
        ),
        "linear_solve_residual_norm": residual_norm,
        "linear_solve_residual_limit": residual_limit,
        "energy_imaginary_part": energy_imaginary,
        "energy_reality_limit": energy_reality_limit,
        "energy": energy,
    }


def _new_subspace_summary(key, components, ncas):
    dimensions = {
        component.name: _component_dimension(component, ncas)
        for component in components
    }
    return {
        "subspace": key,
        "basis_component_dimensions": dimensions,
        "basis_dimension": int(sum(dimensions.values())),
        "number_of_free_blocks": 0,
        "minimum_metric_rank": 0,
        "maximum_metric_rank": 0,
        "minimum_denominator": None,
        "maximum_denominator": None,
        "maximum_denominator_condition_number": 0.0,
        "maximum_metric_hermiticity_error": 0.0,
        "maximum_active_left_right_error": 0.0,
        "maximum_active_hermiticity_error": 0.0,
        "maximum_dyall_hermiticity_error": 0.0,
        "maximum_linear_solve_residual_norm": 0.0,
        "maximum_discarded_rhs_norm": 0.0,
        "worst_block": None,
    }


def _accumulate_block_diagnostics(summary, block, free_indices):
    summary["number_of_free_blocks"] += 1
    rank = int(block["metric_rank"])
    if summary["number_of_free_blocks"] == 1:
        summary["minimum_metric_rank"] = rank
        summary["maximum_metric_rank"] = rank
    else:
        summary["minimum_metric_rank"] = min(
            summary["minimum_metric_rank"], rank
        )
        summary["maximum_metric_rank"] = max(
            summary["maximum_metric_rank"], rank
        )

    for destination, source in (
        ("maximum_metric_hermiticity_error", "metric_hermiticity_error"),
        ("maximum_active_left_right_error", "active_left_right_error"),
        ("maximum_active_hermiticity_error", "active_hermiticity_error"),
        ("maximum_dyall_hermiticity_error", "dyall_hermiticity_error"),
        (
            "maximum_linear_solve_residual_norm",
            "linear_solve_residual_norm",
        ),
        ("maximum_discarded_rhs_norm", "discarded_rhs_norm"),
    ):
        summary[destination] = max(
            float(summary[destination]), float(block.get(source, 0.0))
        )

    if block.get("metric_rank", 0):
        minimum = float(block["denominator_minimum"])
        maximum = float(block["denominator_maximum"])
        condition = float(block["denominator_condition_number"])
        if summary["minimum_denominator"] is None:
            summary["minimum_denominator"] = minimum
            summary["maximum_denominator"] = maximum
        else:
            summary["minimum_denominator"] = min(
                summary["minimum_denominator"], minimum
            )
            summary["maximum_denominator"] = max(
                summary["maximum_denominator"], maximum
            )
        if condition >= summary["maximum_denominator_condition_number"]:
            summary["maximum_denominator_condition_number"] = condition
            summary["worst_block"] = [
                int(index) for index in free_indices
            ]


def _evaluate_fic_subspaces(
    eris,
    pdms,
    core_energy,
    virtual_energy,
    *,
    root=0,
    contraction_backend=None,
    metric_atol=1.0e-12,
    metric_rtol=1.0e-10,
    metric_rcond=1.0e-11,
    matrix_atol=1.0e-10,
    matrix_rtol=1.0e-9,
    null_rhs_atol=1.0e-10,
    null_rhs_rtol=1.0e-8,
    denominator_tol=1.0e-12,
    return_timings=False,
    return_diagnostics=False,
):
    """Evaluate and solve all eight spinor FIC-NEVPT2 subspaces."""

    if contraction_backend is None:
        contraction_backend = _utils._DEFAULT_CONTRACTION_BACKEND
    contraction_backend = _utils._normalize_contraction_backend(
        contraction_backend
    )
    for name, value in (
        ("metric_atol", metric_atol),
        ("metric_rtol", metric_rtol),
        ("metric_rcond", metric_rcond),
        ("matrix_atol", matrix_atol),
        ("matrix_rtol", matrix_rtol),
        ("null_rhs_atol", null_rhs_atol),
        ("null_rhs_rtol", null_rhs_rtol),
        ("denominator_tol", denominator_tol),
    ):
        _finite_nonnegative(value, name=name)

    if contraction_backend == "pytblis":
        _utils._validate_tblis_operand_dtypes(
            [
                (f"h{key}", eris.get_h1eff(key))
                for key in _utils._H1_KEYS
            ]
            + [
                (f"w{key}", eris.get_phys(key))
                for key in _utils._W_KEYS
            ]
            + [
                (f"dm{rank}", density)
                for rank, density in enumerate(pdms, 1)
            ]
        )

    equations = _compile_fic_equations()
    base_context = _utils._execution_context(eris, pdms)
    wick_globals = {
        "np": _utils._wick_einsum_namespace(contraction_backend),
    }
    dtype = np.result_type(
        np.complex128,
        *(eris.get_h1eff(key).dtype for key in _utils._H1_KEYS),
        *(eris.get_phys(key).dtype for key in _utils._W_KEYS),
        *(np.asarray(density).dtype for density in pdms),
    )
    # Block2 emits singleton ``identN`` operands when a coefficient-free
    # overlap/commutator term has free inactive or external indices that are
    # absent from every physical tensor in that term.  NumPy/TBLIS then
    # broadcast those singleton axes into the preallocated target.  The SC
    # equations never need these operands because their integral coefficients
    # already carry every free index, whereas the IC basis matrices do.
    base_context.update(
        {
            f"ident{rank}": np.ones((1,) * rank, dtype=dtype)
            for rank in range(1, 4)
        }
    )

    sub_eners = {}
    sub_times = {}
    diagnostics = {}

    for key in SUBSPACE_ORDER:
        start = time.perf_counter()
        components = _IC_COMPONENTS[key]
        free_labels = tuple(key)

        rhs_tensors = {}
        for component in components:
            labels = free_labels + component.bra_active
            rhs_tensors[component.name] = _execute_tensor(
                equations.rhs_code[(key, component.name)],
                "rhs",
                labels,
                base_context,
                wick_globals,
                dtype,
                eris,
            )

        metric_tensors = {}
        right_tensors = {}
        left_tensors = {}
        for bra_component in components:
            for ket_component in components:
                pair = (key, bra_component.name, ket_component.name)
                labels = (
                    free_labels
                    + bra_component.bra_active
                    + ket_component.ket_active
                )
                short_pair = (
                    bra_component.name,
                    ket_component.name,
                )
                metric_tensors[short_pair] = _execute_tensor(
                    equations.metric_code[pair],
                    "metric",
                    labels,
                    base_context,
                    wick_globals,
                    dtype,
                    eris,
                )
                right_tensors[short_pair] = _execute_tensor(
                    equations.right_code[pair],
                    "right",
                    labels,
                    base_context,
                    wick_globals,
                    dtype,
                    eris,
                )
                left_tensors[short_pair] = _execute_tensor(
                    equations.left_code[pair],
                    "left",
                    labels,
                    base_context,
                    wick_globals,
                    dtype,
                    eris,
                )

        summary = _new_subspace_summary(key, components, eris.ncas)
        summary["contraction_backend"] = contraction_backend
        energy = 0.0
        for free_indices in _iter_free_tuples(key, eris):
            rhs = _assemble_vector(
                rhs_tensors, free_indices, components, eris.ncas
            )
            metric = _assemble_matrix(
                metric_tensors, free_indices, components, eris.ncas
            )
            right = _assemble_matrix(
                right_tensors, free_indices, components, eris.ncas
            )
            left = _assemble_matrix(
                left_tensors, free_indices, components, eris.ncas
            )
            orbital_gap = _orbital_gap_at(
                key,
                free_indices,
                core_energy,
                virtual_energy,
            )
            block_energy, block_diagnostics = _solve_fic_block(
                metric,
                right,
                left,
                rhs,
                orbital_gap,
                root=root,
                subspace=key,
                free_indices=free_indices,
                metric_atol=metric_atol,
                metric_rtol=metric_rtol,
                metric_rcond=metric_rcond,
                matrix_atol=matrix_atol,
                matrix_rtol=matrix_rtol,
                null_rhs_atol=null_rhs_atol,
                null_rhs_rtol=null_rhs_rtol,
                denominator_tol=denominator_tol,
            )
            energy += block_energy
            _accumulate_block_diagnostics(
                summary, block_diagnostics, free_indices
            )

        sub_eners[key] = float(energy)
        sub_times[key] = time.perf_counter() - start
        summary["energy"] = float(energy)
        summary["elapsed_time"] = sub_times[key]
        diagnostics[key] = summary

        del rhs_tensors, metric_tensors, right_tensors, left_tensors
        gc.collect()

    result = (sub_eners,)
    if return_timings:
        result += (sub_times,)
    if return_diagnostics:
        result += (diagnostics,)
    return result[0] if len(result) == 1 else result


class WickX2CFICNEVPT2(lib.StreamObject):
    """Single-state dense complex-spinor FIC/PC-NEVPT2 driver."""

    def __init__(self, mc, frozen=0):
        if _utils._has_frozen_orbitals(frozen) or _utils._has_frozen_orbitals(
            getattr(mc, "frozen", None)
        ):
            raise NotImplementedError(
                "nonzero frozen spinors are outside dense FIC v1"
            )
        self._mc = mc
        self._scf = mc._scf
        self.mol = self._scf.mol
        self.verbose = getattr(mc, "verbose", self.mol.verbose)
        self.stdout = getattr(mc, "stdout", self.mol.stdout)

        self.root = 0
        self.mo_coeff = getattr(mc, "mo_coeff", None)
        self.mo_energy = getattr(mc, "mo_energy", None)
        self.canonicalized = False
        self.eris = None
        self.eris_basis = None
        self.reference_energy = None
        self.e_corr = None
        self.sub_eners = {}
        self.sub_times = {}
        self.sub_diagnostics = {}
        self.rdm_diagnostics = None
        self.integral_symmetry_diagnostics = None

        self.integral_roundoff_factor = (
            _utils._DEFAULT_AO2MO_ROUNDOFF_FACTOR
        )
        self.rdm_atol = _utils._DEFAULT_RDM_ATOL
        self.rdm_rtol = _utils._DEFAULT_RDM_RTOL
        self.rdm_work_memory = _utils._DEFAULT_RDM_WORK_MEMORY
        self.denominator_tol = _utils._DEFAULT_DENOMINATOR_TOL

        self.contraction_backend = _utils._DEFAULT_CONTRACTION_BACKEND
        self.metric_atol = 1.0e-12
        self.metric_rtol = 1.0e-10
        self.metric_rcond = 1.0e-11
        self.matrix_atol = 1.0e-10
        self.matrix_rtol = 1.0e-9
        self.null_rhs_atol = 1.0e-10
        self.null_rhs_rtol = 1.0e-8
        self.frozen = 0
        self._keys = set(self.__dict__)

    @property
    def e_tot(self):
        if self.e_corr is None:
            return None
        return np.asarray(self.reference_energy) + np.asarray(self.e_corr)

    def _semicanonicalize(self, mc, mo_coeff, dm1, root):
        return _utils.semicanonicalize(
            mc,
            mo_coeff,
            dm1,
            root,
            canonicalized=self.canonicalized,
            mo_energy=self.mo_energy,
            verbose=self.verbose,
        )

    def kernel(
        self,
        mc=None,
        mo_coeff=None,
        pdms=None,
        eris=None,
        eris_basis="input_mo",
        root=None,
        contraction_backend=None,
        compact_eris=True,
    ):
        """Compute one root-specific X2C-FIC-NEVPT2 correction.

        ``pdms`` must contain raw SGF particle RDMs of ranks one through four.
        The active basis is never rotated after those RDMs are formed.
        """

        total_start = time.perf_counter()
        if mc is None:
            mc = self._mc
        if _utils._has_frozen_orbitals(getattr(mc, "frozen", None)):
            raise NotImplementedError(
                "nonzero frozen spinors are outside dense FIC v1"
            )
        eris_basis = _utils._normalize_eris_basis(eris_basis)
        if root is None:
            root = self.root
        root = int(root)
        if root < 0:
            raise IndexError("root must be non-negative")
        self.root = root
        if mo_coeff is None:
            mo_coeff = mc.mo_coeff
        input_mo = np.asarray(mo_coeff)
        if contraction_backend is None:
            contraction_backend = self.contraction_backend
        contraction_backend = _utils._normalize_contraction_backend(
            contraction_backend
        )
        self.contraction_backend = contraction_backend

        for name in (
            "metric_atol",
            "metric_rtol",
            "metric_rcond",
            "matrix_atol",
            "matrix_rtol",
            "null_rhs_atol",
            "null_rhs_rtol",
            "denominator_tol",
        ):
            setattr(
                self,
                name,
                _finite_nonnegative(getattr(self, name), name=name),
            )

        self.reference_energy = _utils._reference_energy(mc, root)

        pdm_start = time.perf_counter()
        if pdms is None:
            pdms = _utils.make_dm1234(mc.fcisolver, root=root)
        nelec_source = getattr(mc.fcisolver, "nelecas", None)
        if nelec_source is None:
            nelec_source = mc.nelecas
        pdms, self.rdm_diagnostics = _utils.validate_pdms(
            pdms,
            int(mc.ncas),
            _utils._total_nelec(nelec_source),
            atol=self.rdm_atol,
            rtol=self.rdm_rtol,
            work_memory=self.rdm_work_memory,
        )
        pdm_time = time.perf_counter() - pdm_start

        integral_start = time.perf_counter()
        semicanonical_mo, orbital_energy = self._semicanonicalize(
            mc, input_mo, pdms[0], root
        )
        if eris is None:
            prepared_eris = _utils._dense_eris_from_mc(
                mc,
                semicanonical_mo,
                roundoff_factor=self.integral_roundoff_factor,
            )
            self.integral_symmetry_diagnostics = getattr(
                prepared_eris, "symmetry_diagnostics", None
            )
            if compact_eris:
                prepared_eris = _utils._compact_wick_eris(prepared_eris)
        else:
            if not isinstance(eris, spinor_helper._SpinorERIs):
                raise TypeError(
                    "eris must be a spinor_helper._SpinorERIs instance"
                )
            if (eris.ncore, eris.ncas, eris.nmo) != (
                int(mc.ncore),
                int(mc.ncas),
                semicanonical_mo.shape[1],
            ):
                raise ValueError(
                    "eris partition does not match the CASSCF object"
                )
            self.integral_symmetry_diagnostics = getattr(
                eris, "symmetry_diagnostics", None
            )
            prepared_eris = eris
            if (
                eris_basis == "input_mo"
                and not np.array_equal(semicanonical_mo, input_mo)
            ):
                overlap = np.asarray(mc._scf.get_ovlp())
                rotation = (
                    input_mo.T.conj() @ overlap @ semicanonical_mo
                )
                prepared_eris = (
                    _utils._rotate_wick_eris(eris, rotation)
                    if compact_eris
                    else _utils._rotate_eris(eris, rotation)
                )
            elif compact_eris:
                prepared_eris = _utils._compact_wick_eris(eris)
        integral_time = time.perf_counter() - integral_start

        self.mo_coeff = semicanonical_mo
        self.mo_energy = np.asarray(orbital_energy, dtype=float)
        self.eris = prepared_eris
        self.eris_basis = "semicanonical"

        ncore = int(prepared_eris.ncore)
        nocc = int(prepared_eris.nocc)
        core_energy = self.mo_energy[:ncore]
        virtual_energy = self.mo_energy[nocc:]

        evaluated = _evaluate_fic_subspaces(
            prepared_eris,
            pdms,
            core_energy,
            virtual_energy,
            root=root,
            contraction_backend=contraction_backend,
            metric_atol=self.metric_atol,
            metric_rtol=self.metric_rtol,
            metric_rcond=self.metric_rcond,
            matrix_atol=self.matrix_atol,
            matrix_rtol=self.matrix_rtol,
            null_rhs_atol=self.null_rhs_atol,
            null_rhs_rtol=self.null_rhs_rtol,
            denominator_tol=self.denominator_tol,
            return_timings=True,
            return_diagnostics=True,
        )
        self.sub_eners, subspace_times, self.sub_diagnostics = evaluated
        self.sub_times = {
            "pdms": pdm_time,
            "eris": integral_time,
            **subspace_times,
        }
        self.e_corr = float(sum(self.sub_eners.values()))
        self.sub_times["total"] = time.perf_counter() - total_start

        for key in SUBSPACE_ORDER:
            diagnostics = self.sub_diagnostics[key]
            minimum = diagnostics["minimum_denominator"]
            maximum = diagnostics["maximum_denominator"]
            logger.note(
                self,
                "root %d E(%s-%4s) = %20.14f  basis=%d  "
                "rank=[%d,%d]  gap=[%s,%s]",
                root,
                self.__class__.__name__,
                key,
                self.sub_eners[key],
                diagnostics["basis_dimension"],
                diagnostics["minimum_metric_rank"],
                diagnostics["maximum_metric_rank"],
                "nan" if minimum is None else f"{minimum:.8g}",
                "nan" if maximum is None else f"{maximum:.8g}",
            )

        logger.note(
            self,
            "root %d E(reference) = %.16g  E_corr(FIC) = %.16g  "
            "E(total) = %.16g",
            root,
            self.reference_energy,
            self.e_corr,
            self.e_tot,
        )
        logger.info(
            self,
            "root %d contraction_backend=%s metric_rcond=%.3e "
            "timings: %s",
            root,
            contraction_backend,
            self.metric_rcond,
            " | ".join(
                f"{key}={value:.2f}s"
                for key, value in self.sub_times.items()
            ),
        )
        return self.e_corr


X2CFICNEVPT2 = WickX2CFICNEVPT2
WickX2CICNEVPT2 = WickX2CFICNEVPT2
X2CICNEVPT2 = WickX2CFICNEVPT2
WickX2CPCNEVPT2 = WickX2CFICNEVPT2
X2CPCNEVPT2 = WickX2CFICNEVPT2
