#!/usr/bin/env python
# SPDX-License-Identifier: GPL-3.0-or-later
# Structurally derived in part from pyblock2.icmr.icmrrept2_full.
# Copyright (C) 2020-2021 Huanchen Zhai <hczhai@caltech.edu>
r"""General-complex-spinor X2C fully internally contracted MR-REPT2.

This module implements the state-specific, full-class-matrix second-order
retaining-the-excitation-degree perturbation theory of Fink [Chem. Phys.
Lett. 428, 461 (2006); Chem. Phys. 356, 39 (2009)].  It is structurally based
on the GPL-3.0-or-later Block2 ``pyblock2.icmr.icmrrept2_full`` driver
(Copyright 2020-2021 Huanchen Zhai), while replacing its spin-free and real
orbital assumptions by explicit fermionic creation/destruction operators,
raw spin-orbital one- through four-particle RDMs, and Hermitian complex
linear algebra.

Fink's zeroth-order Hamiltonian is generated by retaining every term of the
bare physical Hamiltonian that conserves the electron number separately in
the inactive, active, and external orbital spaces.  No orbital energies,
Dyall Hamiltonian, semicanonicalization, strong contraction, or level shift
is used.  For each of the eight internally contracted excitation classes,
all core/external free-index tuples are coupled in one full matrix.

The installed Block2 ``full`` implementation uses ``trunc_thrds`` as an
absolute *overlap-metric* eigenvalue cutoff and delegates singular response
directions to ``numpy.linalg.lstsq``.  This implementation preserves the
former meaning and exposes a separate ``denominator_atol`` for the latter;
discarding a near-zero response mode with material source weight is a hard
error rather than a silent regularization.

Official-source map (``pyblock2.icmr.icmrrept2_full``): its nine contracted
operator families ``ijrs/rsi/ijr/rs/ij/ir1/ir2/r/i`` are the eight public
classes here (the two semi-internal ``ir`` families share one full matrix);
``norm_eqs`` gives the overlap metric, ``ener_eqs`` gives the shifted Fink-H0
matrix, and ``rhhk_eqs`` gives the Hamiltonian source.  The official nested
index assembly couples every active and core/external free direction before
solving.  Its ``trunc_thrds`` filters overlap eigenvalues, and its final class
contribution is the source--first-order-wavefunction contraction.  Here those
objects are regenerated with ordinary complex C/D algebra, and H0 is generated
from the population-balance rule instead of a hand-maintained term list.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import gc
import itertools
import math
import time
from typing import Any, Sequence

import numpy as np
from pyscf import lib
from pyscf.lib import logger

from . import nevpt2_utils as _utils
from . import spinor_helper
from . import x2cicmrcisd as _mrci


__all__ = [
    "WickX2CICMRREPT2",
    "X2CICMRREPT2",
    "dump_mrrept2_wick_equations",
    "dump_fink_h0_terms",
]


CLASS_ORDER = tuple(_utils.SUBSPACE_ORDER)
_KERNEL_KEYWORDS = frozenset(
    ("mc", "mo_coeff", "pdms", "eris", "eris_basis", "root")
)
_SPACE_ORDER = ("I", "A", "E")


@dataclass(frozen=True)
class _EquationBundle:
    """Lazy general-spinor Wick equations for the MR-REPT2 response."""

    metric_expr: dict[tuple[str, str, str], Any]
    right_expr: dict[tuple[str, str, str], Any]
    left_expr: dict[tuple[str, str, str], Any]
    source_h_expr: dict[tuple[str, str], Any]
    source_h0_expr: dict[tuple[str, str], Any]
    source_v_expr: dict[tuple[str, str], Any]
    metric_text: dict[tuple[str, str, str], str]
    right_text: dict[tuple[str, str, str], str]
    left_text: dict[tuple[str, str, str], str]
    source_text: dict[tuple[str, str], str]
    metric_code: dict[tuple[str, str, str], str]
    right_code: dict[tuple[str, str, str], str]
    left_code: dict[tuple[str, str, str], str]
    source_code: dict[tuple[str, str], str]
    required_h1_blocks: tuple[str, ...]
    required_eri_blocks: tuple[str, ...]
    maximum_rdm_rank: int
    h0_one_body_blocks: tuple[str, ...]
    h0_two_body_blocks: tuple[str, ...]
    reference_first_moment: Any
    reference_second_moment: Any


@dataclass(frozen=True)
class _ClassMetric:
    """Canonical metric data shared by every free tuple of one class."""

    layout: Any
    metric: np.ndarray
    eigenvalues: np.ndarray
    eigenvectors: np.ndarray
    retained: np.ndarray
    orthogonalizer: np.ndarray
    cutoff: float
    diagnostics: dict[str, Any]


def _space_counts(spaces: Sequence[str]) -> tuple[int, int, int]:
    spaces = tuple(spaces)
    if any(space not in _SPACE_ORDER for space in spaces):
        raise ValueError(f"unknown orbital-space pattern {spaces!r}")
    return tuple(spaces.count(space) for space in _SPACE_ORDER)


def _retains_excitation_degree_one_body(spaces: Sequence[str]) -> bool:
    """Whether a one-body monomial preserves all I/A/E populations."""

    spaces = tuple(spaces)
    if len(spaces) != 2:
        raise ValueError("a one-body space pattern must contain two entries")
    return _space_counts(spaces[:1]) == _space_counts(spaces[1:])


def _retains_excitation_degree_two_body(spaces: Sequence[str]) -> bool:
    """Whether a two-body monomial preserves all I/A/E populations."""

    spaces = tuple(spaces)
    if len(spaces) != 4:
        raise ValueError("a two-body space pattern must contain four entries")
    return _space_counts(spaces[:2]) == _space_counts(spaces[2:])


def _fink_h0_block_keys() -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Return all automatically classified one- and two-body H0 blocks."""

    one_body = tuple(
        "".join(spaces)
        for spaces in itertools.product(_SPACE_ORDER, repeat=2)
        if _retains_excitation_degree_one_body(spaces)
    )
    two_body = tuple(
        "".join(spaces)
        for spaces in itertools.product(_SPACE_ORDER, repeat=4)
        if _retains_excitation_degree_two_body(spaces)
    )
    return one_body, two_body


def _indices_for_spaces(spaces: Sequence[str]) -> str:
    return "".join(
        _mrci._SPACE_DUMMY_LABELS[space][axis]
        for axis, space in enumerate(spaces)
    )


def _fink_h0_hamiltonian(parse):
    """Generate Fink H0 from the I/A/E population-balance definition."""

    result = parse("")
    one_body, two_body = _fink_h0_block_keys()
    for key in one_body:
        indices = _indices_for_spaces(key)
        result += parse(
            f"SUM <{indices}> h[{indices}] "
            f"C[{indices[0]}] D[{indices[1]}]"
        )
    for key in two_body:
        indices = _indices_for_spaces(key)
        result += parse(
            f"0.5 SUM <{indices}> w[{indices}] "
            f"C[{indices[0]}] C[{indices[1]}] "
            f"D[{indices[3]}] D[{indices[2]}]"
        )
    return result


def dump_fink_h0_terms(filename: str | None = None) -> str:
    """Return, and optionally write, the complete retained H0 block list."""

    one_body, two_body = _fink_h0_block_keys()
    text = "\n".join(
        (
            "Fink retaining-excitation-degree H0",
            "criterion: count_I/A/E(creators) == count_I/A/E(annihilators)",
            "one-body blocks (%d): %s" % (len(one_body), ", ".join(one_body)),
            "two-body blocks (%d): %s" % (len(two_body), ", ".join(two_body)),
            "rejected one-body patterns: %d" % (3**2 - len(one_body)),
            "rejected two-body patterns: %d" % (3**4 - len(two_body)),
        )
    ) + "\n"
    if filename is not None:
        with open(filename, "w", encoding="utf-8") as handle:
            handle.write(text)
    return text


@lru_cache(maxsize=1)
@_mrci._preserve_omp_threads
def _compile_equations() -> _EquationBundle:
    """Generate S, left/right Fink A, and H/H0/V source equations."""

    types = _utils._block2_wick_types()
    parse, parse_tensor = _utils._wick_parsers(types)
    h0 = _fink_h0_hamiltonian(parse)
    full_hamiltonian = _mrci._full_bare_hamiltonian(parse)
    perturbation = full_hamiltonian - h0

    active_hamiltonian = parse(
        "SUM <ab> f[ab] C[a] D[b]"
    ) + parse(
        "0.5 SUM <abcd> w[abcd] C[a] C[b] D[d] D[c]"
    )
    reference_first_moment = _utils._lower_active_operators(
        _utils._vacuum_reduce(active_hamiltonian), types
    )
    reference_second_moment = _utils._lower_active_operators(
        _utils._vacuum_reduce(active_hamiltonian * active_hamiltonian), types
    )

    metric_expr = {}
    right_expr = {}
    left_expr = {}
    source_h_expr = {}
    source_h0_expr = {}
    source_v_expr = {}
    metric_text = {}
    right_text = {}
    left_text = {}
    source_text = {}
    metric_code = {}
    right_code = {}
    left_code = {}
    source_code = {}
    required_h1 = set()
    required_eri = set()
    maximum_rdm_rank = max(
        _mrci._expression_rdm_rank(reference_first_moment),
        _mrci._expression_rdm_rank(reference_second_moment),
    )

    for key in CLASS_ORDER:
        for bra_component in _mrci._components(key):
            bra = _mrci._bra_expression(parse, key, bra_component)
            source_pair = (key, bra_component.name)
            source_labels = _mrci._bra_labels(key, bra_component)
            sources = {}
            for source_name, operator in (
                ("H", full_hamiltonian),
                ("H0", h0),
                ("V", perturbation),
            ):
                expression = _utils._lower_active_operators(
                    _utils._vacuum_reduce(bra * operator), types
                )
                sources[source_name] = expression
                maximum_rdm_rank = max(
                    maximum_rdm_rank,
                    _mrci._expression_rdm_rank(expression),
                )
                hkeys, wkeys = _mrci._expression_integral_blocks(
                    expression, types
                )
                required_h1.update(hkeys)
                required_eri.update(wkeys)
            source_h_expr[source_pair] = sources["H"]
            source_h0_expr[source_pair] = sources["H0"]
            source_v_expr[source_pair] = sources["V"]
            source_text[source_pair] = (
                f"H source\n{sources['H']!r}\n\n"
                f"H0 source\n{sources['H0']!r}\n\n"
                f"V source\n{sources['V']!r}"
            )
            source_code[source_pair] = sources["H"].to_einsum(
                _mrci._target(parse_tensor, "source", source_labels)
            )

            for ket_component in _mrci._components(key):
                ket = parse(ket_component.expression)
                pair = (key, bra_component.name, ket_component.name)
                labels = _mrci._bra_labels(
                    key, bra_component
                ) + _mrci._ket_labels(key, ket_component)
                metric = _utils._lower_active_operators(
                    _utils._vacuum_reduce(bra * ket), types
                )

                # Right branch: <Psi| O_b^dagger [H0,O_k] |Psi>.
                right_connected = (h0 ^ ket).expand(6).simplify()
                right = _utils._lower_active_operators(
                    _utils._vacuum_reduce(bra * right_connected), types
                )
                # Left branch: <Psi| [O_b^dagger,H0] O_k |Psi>.
                left_connected = (bra ^ h0).expand(6).simplify()
                left = _utils._lower_active_operators(
                    _utils._vacuum_reduce(left_connected * ket), types
                )

                metric_expr[pair] = metric
                right_expr[pair] = right
                left_expr[pair] = left
                metric_text[pair] = repr(metric)
                right_text[pair] = repr(right)
                left_text[pair] = repr(left)
                metric_code[pair] = metric.to_einsum(
                    _mrci._target(parse_tensor, "metric", labels)
                )
                right_code[pair] = right.to_einsum(
                    _mrci._target(parse_tensor, "fink_right", labels)
                )
                left_code[pair] = left.to_einsum(
                    _mrci._target(parse_tensor, "fink_left", labels)
                )
                for expression in (metric, right, left):
                    maximum_rdm_rank = max(
                        maximum_rdm_rank,
                        _mrci._expression_rdm_rank(expression),
                    )
                for expression in (right, left):
                    hkeys, wkeys = _mrci._expression_integral_blocks(
                        expression, types
                    )
                    required_h1.update(hkeys)
                    required_eri.update(wkeys)

    if maximum_rdm_rank > 4:
        raise RuntimeError(
            "Fink MR-REPT2 Wick lowering requested an active RDM above rank four"
        )
    one_body, two_body = _fink_h0_block_keys()
    return _EquationBundle(
        metric_expr=metric_expr,
        right_expr=right_expr,
        left_expr=left_expr,
        source_h_expr=source_h_expr,
        source_h0_expr=source_h0_expr,
        source_v_expr=source_v_expr,
        metric_text=metric_text,
        right_text=right_text,
        left_text=left_text,
        source_text=source_text,
        metric_code=metric_code,
        right_code=right_code,
        left_code=left_code,
        source_code=source_code,
        required_h1_blocks=tuple(sorted(required_h1)),
        required_eri_blocks=tuple(sorted(required_eri)),
        maximum_rdm_rank=maximum_rdm_rank,
        h0_one_body_blocks=one_body,
        h0_two_body_blocks=two_body,
        reference_first_moment=reference_first_moment,
        reference_second_moment=reference_second_moment,
    )


def dump_mrrept2_wick_equations(filename: str | None = None) -> str:
    """Return, and optionally write, every generated MR-REPT2 equation."""

    equations = _compile_equations()
    sections = [
        "[conventions]",
        "H = bare h[pq] C[p]D[q] + 0.5 w[pqrs] C[p]C[q]D[s]D[r]",
        "H0 retains I/A/E population-balanced monomials",
        "full class matrices couple every core/external free-index tuple",
        f"maximum active RDM rank: {equations.maximum_rdm_rank}",
        "H0 h blocks: " + ", ".join(equations.h0_one_body_blocks),
        "H0 w blocks: " + ", ".join(equations.h0_two_body_blocks),
        "required h blocks: " + ", ".join(equations.required_h1_blocks),
        "required w blocks: " + ", ".join(equations.required_eri_blocks),
    ]
    for key in CLASS_ORDER:
        for bra_component in _mrci._components(key):
            source_pair = (key, bra_component.name)
            sections.extend(
                (
                    f"[{key}/{bra_component.name}] source expressions\n"
                    f"{equations.source_text[source_pair]}",
                    f"[{key}/{bra_component.name}] H-source einsum\n"
                    f"{equations.source_code[source_pair]}",
                )
            )
            for ket_component in _mrci._components(key):
                pair = (key, bra_component.name, ket_component.name)
                title = (
                    f"{key}/{bra_component.name} <- "
                    f"{ket_component.name}"
                )
                sections.extend(
                    (
                        f"[{title}] metric expression\n"
                        f"{equations.metric_text[pair]}",
                        f"[{title}] metric einsum\n"
                        f"{equations.metric_code[pair]}",
                        f"[{title}] right A expression\n"
                        f"{equations.right_text[pair]}",
                        f"[{title}] right A einsum\n"
                        f"{equations.right_code[pair]}",
                        f"[{title}] left A expression\n"
                        f"{equations.left_text[pair]}",
                        f"[{title}] left A einsum\n"
                        f"{equations.left_code[pair]}",
                    )
                )
    text = "\n\n".join(sections) + "\n"
    if filename is not None:
        with open(filename, "w", encoding="utf-8") as handle:
            handle.write(text)
    return text


def _evaluate_class_block(
    evaluator,
    expressions: dict[tuple[str, str, str], Any],
    layout,
    bra_free: Sequence[int],
    ket_free: Sequence[int],
) -> np.ndarray:
    result = np.zeros(
        (layout.local_dimension, layout.local_dimension),
        dtype=evaluator.dtype,
    )
    fixed = _mrci._fixed_indices(
        layout, bra_free, layout, ket_free
    )
    for bra_index, bra_component in enumerate(layout.components):
        for ket_index, ket_component in enumerate(layout.components):
            expression = expressions[
                layout.key, bra_component.name, ket_component.name
            ]
            output = tuple(bra_component.bra_active) + tuple(
                ket_component.ket_active
            )
            tensor = evaluator.evaluate(expression, output, fixed)
            block = _mrci._selected_component_matrix(
                tensor,
                layout.active_selections[bra_index],
                layout.active_selections[ket_index],
                len(bra_component.bra_active),
                len(ket_component.ket_active),
                int(evaluator.eris.ncas),
            )
            result[
                layout.component_slices[bra_index],
                layout.component_slices[ket_index],
            ] = block
    return result


def _evaluate_source_vector(
    evaluator,
    expressions: dict[tuple[str, str], Any],
    layout,
    bra_free: Sequence[int],
) -> np.ndarray:
    result = np.zeros(layout.local_dimension, dtype=evaluator.dtype)
    fixed = {
        _mrci._FREE_BRA_LABEL[label]: int(value)
        for label, value in zip(layout.key, bra_free)
    }
    ncas = int(evaluator.eris.ncas)
    for component_index, component in enumerate(layout.components):
        expression = expressions[layout.key, component.name]
        tensor = evaluator.evaluate(
            expression, tuple(component.bra_active), fixed
        )
        size = ncas ** len(component.bra_active)
        selected = np.asarray(tensor).reshape(size)[
            layout.active_selections[component_index]
        ]
        result[layout.component_slices[component_index]] = selected
    return result


def _build_class_metric(
    layout,
    evaluator,
    equations,
    *,
    metric_atol: float,
    metric_rtol: float,
    metric_rcond: float,
    trunc_thrds: float,
    matrix_atol: float,
    matrix_rtol: float,
) -> _ClassMetric:
    if not layout.free_tuples or layout.local_dimension == 0:
        empty = np.zeros(
            (layout.local_dimension, layout.local_dimension),
            dtype=evaluator.dtype,
        )
        return _ClassMetric(
            layout=layout,
            metric=empty,
            eigenvalues=np.empty(0),
            eigenvectors=empty,
            retained=np.zeros(0, dtype=bool),
            orthogonalizer=np.zeros(
                (layout.local_dimension, 0), dtype=evaluator.dtype
            ),
            cutoff=float(max(metric_atol, trunc_thrds)),
            diagnostics={
                "class": layout.key,
                "free_tuple_count": 0,
                "local_raw_dimension": layout.local_dimension,
                "raw_dimension": 0,
                "local_rank": 0,
                "rank": 0,
                "metric_cutoff": float(max(metric_atol, trunc_thrds)),
                "trunc_thrds_semantics": "absolute overlap eigenvalue cutoff",
                "metric_block_structure": "empty class",
            },
        )

    representative = layout.free_tuples[0]
    raw_metric = _evaluate_class_block(
        evaluator,
        equations.metric_expr,
        layout,
        representative,
        representative,
    )
    hermiticity_error = _mrci._maximum_abs(
        raw_metric - raw_metric.conj().T
    )
    scale = max(1.0, _mrci._maximum_abs(raw_metric))
    hermiticity_tolerance = float(matrix_atol + matrix_rtol * scale)
    hermiticity_hard_tolerance = _mrci._audit_projection_residual(
        f"MR-REPT2 class {layout.key} metric Hermiticity",
        hermiticity_error,
        hermiticity_tolerance,
        projection="applying the audited Hermitian projection",
    )
    metric = 0.5 * (raw_metric + raw_metric.conj().T)
    eigenvalues, eigenvectors = np.linalg.eigh(metric)
    maximum = float(np.max(eigenvalues, initial=0.0))
    minimum = float(np.min(eigenvalues, initial=0.0))
    negative_tolerance = float(
        metric_atol + metric_rtol * max(1.0, abs(maximum))
    )
    if minimum < -negative_tolerance:
        raise FloatingPointError(
            f"MR-REPT2 class {layout.key} metric has significant negative "
            f"eigenvalue {minimum:.3e}"
        )
    cutoff = float(
        max(
            metric_atol,
            trunc_thrds,
            metric_rcond * max(maximum, 0.0),
        )
    )
    retained = eigenvalues > cutoff
    retained_values = eigenvalues[retained]
    orthogonalizer = eigenvectors[:, retained] / np.sqrt(
        retained_values
    )[None, :]
    identity = orthogonalizer.conj().T @ metric @ orthogonalizer
    orthonormality_error = _mrci._maximum_abs(
        identity - np.eye(identity.shape[0], dtype=identity.dtype)
    )
    user_tolerance = float(matrix_atol + matrix_rtol)
    if retained_values.size:
        condition = float(retained_values[-1] / retained_values[0])
        (
            orthonormality_tolerance,
            roundoff_bound,
            machine_epsilon,
        ) = _mrci._canonical_orthonormality_tolerance(
            matrix_atol,
            matrix_rtol,
            condition,
            metric.dtype,
        )
    else:
        condition = math.inf
        orthonormality_tolerance = user_tolerance
        roundoff_bound = 0.0
        machine_epsilon = float(np.finfo(metric.real.dtype).eps)
    if orthonormality_error > orthonormality_tolerance:
        raise FloatingPointError(
            f"MR-REPT2 class {layout.key} canonical metric residual "
            f"{orthonormality_error:.3e} exceeds "
            f"{orthonormality_tolerance:.3e}"
        )

    repeated_block_error = 0.0
    cross_free_metric_error = 0.0
    if len(layout.free_tuples) > 1:
        last = layout.free_tuples[-1]
        repeated = _evaluate_class_block(
            evaluator, equations.metric_expr, layout, last, last
        )
        repeated_block_error = _mrci._maximum_abs(repeated - raw_metric)
        cross = _evaluate_class_block(
            evaluator,
            equations.metric_expr,
            layout,
            representative,
            last,
        )
        cross_free_metric_error = _mrci._maximum_abs(cross)
        structure_error = max(repeated_block_error, cross_free_metric_error)
        if structure_error > 1.0e3 * hermiticity_tolerance:
            raise FloatingPointError(
                f"MR-REPT2 class {layout.key} metric free-index block "
                f"structure failed ({structure_error:.3e})"
            )
        if structure_error > hermiticity_tolerance:
            _utils._warn_numerical(
                f"MR-REPT2 class {layout.key} metric free-index block "
                f"residual {structure_error:.3e} exceeds "
                f"{hermiticity_tolerance:.3e}"
            )

    local_rank = int(retained_values.size)
    diagnostics = {
        "class": layout.key,
        "free_tuple_count": len(layout.free_tuples),
        "local_raw_dimension": layout.local_dimension,
        "raw_dimension": layout.raw_dimension,
        "local_rank": local_rank,
        "rank": int(local_rank * len(layout.free_tuples)),
        "metric_eigenvalues": [float(value) for value in eigenvalues],
        "metric_minimum_eigenvalue": minimum,
        "metric_maximum_eigenvalue": maximum,
        "metric_negative_tolerance": negative_tolerance,
        "metric_cutoff": cutoff,
        "metric_atol": float(metric_atol),
        "metric_rcond": float(metric_rcond),
        "trunc_thrds": float(trunc_thrds),
        "trunc_thrds_semantics": "absolute overlap eigenvalue cutoff",
        "minimum_retained_eigenvalue": (
            None if not retained_values.size else float(retained_values[0])
        ),
        "retained_condition_number": condition,
        "metric_hermiticity_error": hermiticity_error,
        "metric_hermiticity_tolerance": hermiticity_tolerance,
        "metric_hermiticity_hard_tolerance": hermiticity_hard_tolerance,
        "orthonormality_error": orthonormality_error,
        "orthonormality_tolerance": orthonormality_tolerance,
        "orthonormality_user_tolerance": user_tolerance,
        "orthonormality_roundoff_bound": roundoff_bound,
        "orthonormality_machine_epsilon": machine_epsilon,
        "repeated_block_error": repeated_block_error,
        "cross_free_metric_error": cross_free_metric_error,
        "metric_block_structure": (
            "identical direct sum over free tuples; class response remains full"
        ),
    }
    return _ClassMetric(
        layout=layout,
        metric=np.asarray(metric),
        eigenvalues=np.asarray(eigenvalues),
        eigenvectors=np.asarray(eigenvectors),
        retained=np.asarray(retained),
        orthogonalizer=np.asarray(orthogonalizer),
        cutoff=cutoff,
        diagnostics=diagnostics,
    )


def _source_threshold(source_norm, *, atol: float, rtol: float) -> float:
    return float(atol + rtol * max(1.0, float(source_norm)))


def _external_signature(
    key: str, free_indices: Sequence[int]
) -> tuple[frozenset[int], frozenset[int]]:
    """Return inactive holes and external particles for one free tuple."""

    holes = frozenset(
        int(value)
        for label, value in zip(key, free_indices)
        if label in "ij"
    )
    particles = frozenset(
        int(value)
        for label, value in zip(key, free_indices)
        if label in "rs"
    )
    return holes, particles


def _minimum_external_excitation_rank(
    key: str,
    bra_free: Sequence[int],
    ket_free: Sequence[int],
) -> int:
    """Minimum operator rank needed between two external occupations."""

    bra_holes, bra_particles = _external_signature(key, bra_free)
    ket_holes, ket_particles = _external_signature(key, ket_free)
    bra_only = len(ket_holes - bra_holes) + len(
        bra_particles - ket_particles
    )
    ket_only = len(bra_holes - ket_holes) + len(
        ket_particles - bra_particles
    )
    return max(bra_only, ket_only)


def _replacement_subsets(
    occupied: frozenset[int], dimension: int, changes: int
):
    """Yield fixed-cardinality subsets at one exact replacement distance."""

    occupied_tuple = tuple(sorted(occupied))
    unoccupied_tuple = tuple(
        index for index in range(int(dimension)) if index not in occupied
    )
    for removed in itertools.combinations(occupied_tuple, changes):
        retained = occupied.difference(removed)
        for added in itertools.combinations(unoccupied_tuple, changes):
            yield frozenset((*retained, *added))


def _two_body_coupled_ket_indices(
    key: str,
    bra_free: Sequence[int],
    *,
    ncore: int,
    nvirt: int,
    signature_indices: dict[
        tuple[frozenset[int], frozenset[int]], int
    ],
):
    """Yield free tuples reachable through an at-most-two-body operator."""

    holes, particles = _external_signature(key, bra_free)
    maximum_hole_changes = min(len(holes), int(ncore) - len(holes), 2)
    maximum_particle_changes = min(
        len(particles), int(nvirt) - len(particles), 2
    )
    for hole_changes in range(maximum_hole_changes + 1):
        for particle_changes in range(maximum_particle_changes + 1):
            if hole_changes + particle_changes > 2:
                continue
            for candidate_holes in _replacement_subsets(
                holes, ncore, hole_changes
            ):
                for candidate_particles in _replacement_subsets(
                    particles, nvirt, particle_changes
                ):
                    candidate = signature_indices.get(
                        (candidate_holes, candidate_particles)
                    )
                    if candidate is not None:
                        yield candidate


def _class_memory_estimate(
    raw_dimension: int,
    orthogonal_dimension: int,
    *,
    retain_raw_matrices: bool,
    dtype,
) -> dict[str, int]:
    itemsize = np.dtype(dtype).itemsize
    orth_matrix = itemsize * orthogonal_dimension**2
    raw_matrix = itemsize * raw_dimension**2
    # right, left, reconciled/projection, eigensolver and implementation margin
    orthogonal_workspace = 8 * orth_matrix
    raw_workspace = 3 * raw_matrix if retain_raw_matrices else 0
    vectors = itemsize * (5 * raw_dimension + 8 * orthogonal_dimension)
    return {
        "raw_dimension": int(raw_dimension),
        "orthogonal_dimension": int(orthogonal_dimension),
        "orthogonal_matrix_bytes": int(orth_matrix),
        "orthogonal_workspace_bytes": int(orthogonal_workspace),
        "raw_workspace_bytes": int(raw_workspace),
        "vector_workspace_bytes": int(vectors),
        "estimated_peak_bytes": int(
            orthogonal_workspace + raw_workspace + vectors
        ),
    }


def _solve_orthogonal_response(
    fink_matrix,
    source,
    *,
    class_key: str,
    denominator_atol: float,
    denominator_rtol: float,
    discarded_source_atol: float,
    discarded_source_rtol: float,
    energy_imag_atol: float,
    energy_imag_rtol: float,
) -> tuple[float, np.ndarray, dict[str, Any]]:
    """Solve ``A t = -b`` with explicit signed near-zero-mode handling."""

    fink_matrix = np.asarray(fink_matrix)
    source = np.asarray(source)
    denominators, denominator_vectors = np.linalg.eigh(fink_matrix)
    denominator_scale = float(
        max(1.0, np.max(np.abs(denominators), initial=0.0))
    )
    denominator_cutoff = float(
        max(denominator_atol, denominator_rtol * denominator_scale)
    )
    projected_source = denominator_vectors.conj().T @ source
    near_zero = np.abs(denominators) <= denominator_cutoff
    retained_denominators = denominators[~near_zero]
    discarded_source_norm = float(np.linalg.norm(projected_source[near_zero]))
    source_norm = float(np.linalg.norm(source))
    source_tolerance = _source_threshold(
        source_norm,
        atol=discarded_source_atol,
        rtol=discarded_source_rtol,
    )
    if discarded_source_norm > source_tolerance:
        raise FloatingPointError(
            f"MR-REPT2 class {class_key} has material source weight "
            f"{discarded_source_norm:.3e} in near-zero Fink denominators "
            f"(limit {source_tolerance:.3e})"
        )

    response_modes = np.zeros_like(projected_source)
    response_modes[~near_zero] = (
        -projected_source[~near_zero] / denominators[~near_zero]
    )
    amplitudes = denominator_vectors @ response_modes
    energy_complex = complex(np.vdot(source, amplitudes))
    energy_tolerance = float(
        energy_imag_atol
        + energy_imag_rtol * max(1.0, abs(energy_complex.real))
    )
    if not np.isfinite(energy_complex.real) or not np.isfinite(
        energy_complex.imag
    ):
        raise FloatingPointError(
            f"MR-REPT2 class {class_key} energy is non-finite"
        )
    if abs(energy_complex.imag) > energy_tolerance:
        raise FloatingPointError(
            f"MR-REPT2 class {class_key} energy has imaginary part "
            f"{energy_complex.imag:.3e} exceeding {energy_tolerance:.3e}"
        )
    response_residual = fink_matrix @ amplitudes + source
    transformed_residual = denominator_vectors.conj().T @ response_residual
    retained_mode_residual = _mrci._maximum_abs(
        transformed_residual[~near_zero]
    )
    return (
        float(energy_complex.real),
        np.asarray(amplitudes),
        {
            "denominators": [float(value) for value in denominators],
            "minimum_denominator": (
                None if not denominators.size else float(denominators.min())
            ),
            "maximum_denominator": (
                None if not denominators.size else float(denominators.max())
            ),
            "minimum_absolute_denominator": (
                None
                if not denominators.size
                else float(np.min(np.abs(denominators)))
            ),
            "minimum_absolute_retained_denominator": (
                None
                if not retained_denominators.size
                else float(np.min(np.abs(retained_denominators)))
            ),
            "maximum_absolute_retained_denominator": (
                None
                if not retained_denominators.size
                else float(np.max(np.abs(retained_denominators)))
            ),
            "denominator_cutoff": denominator_cutoff,
            "near_zero_denominator_count": int(np.count_nonzero(near_zero)),
            "discarded_denominator_source_norm": discarded_source_norm,
            "denominator_source_tolerance": source_tolerance,
            "negative_denominator_count": int(
                np.count_nonzero(denominators < -denominator_cutoff)
            ),
            "positive_denominator_count": int(
                np.count_nonzero(denominators > denominator_cutoff)
            ),
            "denominator_signs_preserved": True,
            "retained_mode_response_residual": retained_mode_residual,
            "energy_real": float(energy_complex.real),
            "energy_imaginary": float(energy_complex.imag),
            "energy_imaginary_tolerance": energy_tolerance,
        },
    )


def _solve_class(
    calculation,
    metric: _ClassMetric,
    evaluator,
    equations,
) -> tuple[float, np.ndarray, dict[str, Any], dict[str, Any]]:
    layout = metric.layout
    local_dimension = int(layout.local_dimension)
    local_rank = int(metric.orthogonalizer.shape[1])
    free_count = len(layout.free_tuples)
    raw_dimension = int(layout.raw_dimension)
    orthogonal_dimension = int(local_rank * free_count)
    x = metric.orthogonalizer
    assembly_started = time.perf_counter()

    right_orth = np.zeros(
        (orthogonal_dimension, orthogonal_dimension), dtype=evaluator.dtype
    )
    left_orth = np.zeros_like(right_orth)
    source_h_raw = np.zeros(raw_dimension, dtype=evaluator.dtype)
    source_h0_raw = np.zeros_like(source_h_raw)
    source_v_raw = np.zeros_like(source_h_raw)
    right_raw = (
        np.zeros((raw_dimension, raw_dimension), dtype=evaluator.dtype)
        if calculation.retain_raw_matrices
        else None
    )
    left_raw = np.zeros_like(right_raw) if right_raw is not None else None
    candidate_block_count = int(free_count**2)
    potentially_nonzero_block_count = 0
    evaluated_block_count = 0
    evaluated_block_pair_count = 0
    signature_indices = {
        _external_signature(layout.key, free): index
        for index, free in enumerate(layout.free_tuples)
    }
    if len(signature_indices) != free_count:
        raise RuntimeError(
            f"MR-REPT2 class {layout.key} has duplicate external signatures"
        )

    for bra_index, bra_free in enumerate(layout.free_tuples):
        raw_bra = slice(
            bra_index * local_dimension,
            (bra_index + 1) * local_dimension,
        )
        orth_bra = slice(
            bra_index * local_rank,
            (bra_index + 1) * local_rank,
        )
        b_h = _evaluate_source_vector(
            evaluator, equations.source_h_expr, layout, bra_free
        )
        b_h0 = _evaluate_source_vector(
            evaluator, equations.source_h0_expr, layout, bra_free
        )
        b_v = _evaluate_source_vector(
            evaluator, equations.source_v_expr, layout, bra_free
        )
        source_h_raw[raw_bra] = b_h
        source_h0_raw[raw_bra] = b_h0
        source_v_raw[raw_bra] = b_v

        coupled_ket_indices = _two_body_coupled_ket_indices(
            layout.key,
            bra_free,
            ncore=int(evaluator.eris.ncore),
            nvirt=int(evaluator.eris.nvirt),
            signature_indices=signature_indices,
        )
        for ket_index in coupled_ket_indices:
            if ket_index < bra_index:
                continue
            ket_free = layout.free_tuples[ket_index]
            raw_ket = slice(
                ket_index * local_dimension,
                (ket_index + 1) * local_dimension,
            )
            orth_ket = slice(
                ket_index * local_rank,
                (ket_index + 1) * local_rank,
            )
            block_multiplicity = 1 if ket_index == bra_index else 2
            potentially_nonzero_block_count += block_multiplicity
            evaluated_block_count += block_multiplicity
            evaluated_block_pair_count += 1
            raw_right = _evaluate_class_block(
                evaluator,
                equations.right_expr,
                layout,
                bra_free,
                ket_free,
            )
            raw_left = _evaluate_class_block(
                evaluator,
                equations.left_expr,
                layout,
                bra_free,
                ket_free,
            )
            transformed_right = x.conj().T @ raw_right @ x
            transformed_left = x.conj().T @ raw_left @ x
            right_orth[orth_bra, orth_ket] = transformed_right
            left_orth[orth_bra, orth_ket] = transformed_left
            if ket_index != bra_index:
                # [O_b^dagger,H0] O_k is the adjoint of
                # O_k^dagger [H0,O_b].  Thus the independently generated
                # left branch at (b,k) is the right branch at (k,b)^dagger,
                # and conversely.  Populate the reverse orientation from
                # this exact algebraic identity while retaining both branch
                # audits; this halves equation evaluations without imposing
                # block diagonal structure.
                right_orth[orth_ket, orth_bra] = transformed_left.conj().T
                left_orth[orth_ket, orth_bra] = transformed_right.conj().T
            if right_raw is not None:
                right_raw[raw_bra, raw_ket] = raw_right
                left_raw[raw_bra, raw_ket] = raw_left
                if ket_index != bra_index:
                    right_raw[raw_ket, raw_bra] = raw_left.conj().T
                    left_raw[raw_ket, raw_bra] = raw_right.conj().T

    assembly_seconds = time.perf_counter() - assembly_started
    source_norm = float(np.linalg.norm(source_h_raw))
    source_tolerance = _source_threshold(
        source_norm,
        atol=calculation.discarded_source_atol,
        rtol=calculation.discarded_source_rtol,
    )
    source_h0_norm = float(np.linalg.norm(source_h0_raw))
    source_decomposition_error = _mrci._maximum_abs(
        source_h_raw - source_h0_raw - source_v_raw
    )
    source_h_v_error = _mrci._maximum_abs(source_h_raw - source_v_raw)
    if source_h0_norm > source_tolerance:
        raise FloatingPointError(
            f"MR-REPT2 class {layout.key} H0 couples the reference to Q: "
            f"norm={source_h0_norm:.3e}, limit={source_tolerance:.3e}"
        )
    if max(source_decomposition_error, source_h_v_error) > source_tolerance:
        raise FloatingPointError(
            f"MR-REPT2 class {layout.key} H/H0/V source decomposition failed"
        )

    source_orth = np.zeros(orthogonal_dimension, dtype=evaluator.dtype)
    discarded_metric_components = []
    discarded_vectors = metric.eigenvectors[:, ~metric.retained]
    for free_index in range(free_count):
        raw_slice = slice(
            free_index * local_dimension,
            (free_index + 1) * local_dimension,
        )
        orth_slice = slice(
            free_index * local_rank,
            (free_index + 1) * local_rank,
        )
        local_source = source_h_raw[raw_slice]
        source_orth[orth_slice] = x.conj().T @ local_source
        if discarded_vectors.shape[1]:
            discarded_metric_components.append(
                discarded_vectors.conj().T @ local_source
            )
    discarded_metric_source_norm = float(
        np.linalg.norm(
            np.concatenate(discarded_metric_components)
            if discarded_metric_components
            else np.empty(0)
        )
    )
    if discarded_metric_source_norm > source_tolerance:
        raise FloatingPointError(
            f"MR-REPT2 class {layout.key} source has material weight in "
            f"discarded metric space: {discarded_metric_source_norm:.3e} "
            f"> {source_tolerance:.3e}"
        )

    scale = max(
        1.0,
        _mrci._maximum_abs(right_orth),
        _mrci._maximum_abs(left_orth),
    )
    tolerance = float(calculation.matrix_atol + calculation.matrix_rtol * scale)
    branch_error = _mrci._maximum_abs(right_orth - left_orth)
    right_hermiticity_error = _mrci._maximum_abs(
        right_orth - right_orth.conj().T
    )
    left_adjoint_error = _mrci._maximum_abs(
        left_orth - right_orth.conj().T
    )
    branch_hard_tolerance = _mrci._audit_projection_residual(
        f"MR-REPT2 class {layout.key} left/right Fink branch equality",
        branch_error,
        tolerance,
        projection="reconciling the independently generated branches",
    )
    hermiticity_hard_tolerance = _mrci._audit_projection_residual(
        f"MR-REPT2 class {layout.key} raw Fink-matrix Hermiticity",
        right_hermiticity_error,
        tolerance,
        projection="applying the audited Hermitian projection",
    )
    _mrci._audit_projection_residual(
        f"MR-REPT2 class {layout.key} left/right adjoint identity",
        left_adjoint_error,
        tolerance,
        projection="reconciling the independently generated branches",
    )
    # Reconcile in place before the eigensolve.  For the large scalar-limit
    # regressions this avoids retaining two audited branch matrices plus a
    # third reconciled copy; the independent branches have already been
    # compared above and raw copies, when explicitly requested, are separate.
    right_orth += left_orth
    right_orth *= 0.5
    reconciled = right_orth
    del left_orth
    reconciled_hermiticity_error = _mrci._maximum_abs(
        reconciled - reconciled.conj().T
    )
    fink_matrix = 0.5 * (reconciled + reconciled.conj().T)
    projected_hermiticity_error = _mrci._maximum_abs(
        fink_matrix - fink_matrix.conj().T
    )

    response_started = time.perf_counter()
    energy, amplitudes_orth, response_diagnostics = (
        _solve_orthogonal_response(
            fink_matrix,
            source_orth,
            class_key=layout.key,
            denominator_atol=calculation.denominator_atol,
            denominator_rtol=calculation.denominator_rtol,
            discarded_source_atol=calculation.discarded_source_atol,
            discarded_source_rtol=calculation.discarded_source_rtol,
            energy_imag_atol=calculation.energy_imag_atol,
            energy_imag_rtol=calculation.energy_imag_rtol,
        )
    )

    response_seconds = time.perf_counter() - response_started
    amplitudes_raw = np.zeros(raw_dimension, dtype=evaluator.dtype)
    for free_index in range(free_count):
        raw_slice = slice(
            free_index * local_dimension,
            (free_index + 1) * local_dimension,
        )
        orth_slice = slice(
            free_index * local_rank,
            (free_index + 1) * local_rank,
        )
        amplitudes_raw[raw_slice] = x @ amplitudes_orth[orth_slice]
    diagnostics = {
        "class": layout.key,
        "matrix_shape": [orthogonal_dimension, orthogonal_dimension],
        "assembly_seconds": assembly_seconds,
        "response_seconds": response_seconds,
        "all_free_indices_coupled": True,
        "candidate_free_index_block_count": candidate_block_count,
        "evaluated_free_index_block_count": evaluated_block_count,
        "evaluated_free_index_block_pair_count": evaluated_block_pair_count,
        "potentially_nonzero_free_index_block_count": (
            potentially_nonzero_block_count
        ),
        "exact_slater_condon_zero_block_count": (
            candidate_block_count - potentially_nonzero_block_count
        ),
        "slater_condon_screening_is_approximate": False,
        "source_norm": source_norm,
        "source_tolerance": source_tolerance,
        "h0_reference_to_q_source_norm": source_h0_norm,
        "h_equals_v_source_error": source_h_v_error,
        "h_h0_v_decomposition_error": source_decomposition_error,
        "discarded_metric_source_norm": discarded_metric_source_norm,
        "right_left_branch_error": branch_error,
        "right_fink_hermiticity_error": right_hermiticity_error,
        "left_right_adjoint_error": left_adjoint_error,
        "matrix_tolerance": tolerance,
        "branch_hard_tolerance": branch_hard_tolerance,
        "hermiticity_hard_tolerance": hermiticity_hard_tolerance,
        "reconciled_hermiticity_error": reconciled_hermiticity_error,
        "projected_hermiticity_error": projected_hermiticity_error,
        **response_diagnostics,
    }
    retained_data = {
        "metric": (
            np.kron(np.eye(free_count), metric.metric)
            if calculation.retain_raw_matrices
            else None
        ),
        "fink_right": right_raw,
        "fink_left": left_raw,
        "fink": (
            None
            if right_raw is None
            else 0.25
            * (
                right_raw
                + left_raw
                + right_raw.conj().T
                + left_raw.conj().T
            )
        ),
        "source_h": source_h_raw if calculation.retain_raw_matrices else None,
        "source_h0": source_h0_raw if calculation.retain_raw_matrices else None,
        "source_v": source_v_raw if calculation.retain_raw_matrices else None,
        "fink_orthogonal": (
            fink_matrix if calculation.retain_raw_matrices else None
        ),
        "source_orthogonal": (
            source_orth if calculation.retain_raw_matrices else None
        ),
    }
    return (
        energy,
        amplitudes_raw,
        diagnostics,
        retained_data,
    )


class WickX2CICMRREPT2(lib.StreamObject):
    """State-specific general-complex-spinor full-matrix IC-MRREPT2."""

    def __init__(self, mc, frozen=0):
        if _utils._has_frozen_orbitals(frozen) or _utils._has_frozen_orbitals(
            getattr(mc, "frozen", None)
        ):
            raise NotImplementedError(
                "nonzero frozen spinors are outside X2C-IC-MRREPT2 v1"
            )
        self._mc = mc
        self._scf = mc._scf
        self.mol = self._scf.mol
        self.verbose = getattr(mc, "verbose", self.mol.verbose)
        self.stdout = getattr(mc, "stdout", self.mol.stdout)

        self.root = 0
        self.metric_atol = 1.0e-12
        self.metric_rtol = 1.0e-10
        self.metric_rcond = 1.0e-10
        # Official full.py meaning: absolute overlap-metric eigenvalue cutoff.
        self.trunc_thrds = 1.0e-10
        self.denominator_atol = 1.0e-10
        self.denominator_rtol = 0.0
        self.discarded_source_atol = 1.0e-10
        self.discarded_source_rtol = 1.0e-8
        self.matrix_atol = 1.0e-10
        self.matrix_rtol = 1.0e-9
        self.energy_imag_atol = 1.0e-10
        self.energy_imag_rtol = 1.0e-9
        self.reference_residual_warn = 1.0e-7
        self.reference_residual_error = 1.0e-2
        self.reference_energy_atol = 1.0e-8
        self.rdm_atol = _utils._DEFAULT_RDM_ATOL
        self.rdm_rtol = _utils._DEFAULT_RDM_RTOL
        self.rdm_work_memory = _utils._DEFAULT_RDM_WORK_MEMORY
        self.integral_roundoff_factor = _utils._DEFAULT_AO2MO_ROUNDOFF_FACTOR
        self.contraction_backend = _utils._DEFAULT_CONTRACTION_BACKEND
        self.matrix_memory_limit = None
        self.retain_raw_matrices = False
        self.frozen = 0

        self.mo_coeff = getattr(mc, "mo_coeff", None)
        self.eris = None
        self.eris_basis = None
        self._clear_results()
        self._keys = set(self.__dict__)

    def run(self, *args, **kwargs):
        """Run :meth:`kernel` while forwarding per-call RDM/ERI inputs."""

        kernel_kwargs = {
            name: value
            for name, value in kwargs.items()
            if name in _KERNEL_KEYWORDS
        }
        setting_kwargs = {
            name: value
            for name, value in kwargs.items()
            if name not in _KERNEL_KEYWORDS or name in self._keys
        }
        self.set(**setting_kwargs)
        self.kernel(*args, **kernel_kwargs)
        return self

    @property
    def e_tot(self):
        if self.e_corr is None or self.reference_energy is None:
            return None
        return float(self.reference_energy + self.e_corr)

    def _clear_results(self):
        self.reference_energy = None
        self.e_corr = None
        self.sub_eners = {}
        self.sub_times = {}
        self.metric_diagnostics = {}
        self.fink_h0_diagnostics = {}
        self.denominator_diagnostics = {}
        self.rdm_diagnostics = None
        self.integral_symmetry_diagnostics = None
        self.basis_layouts = None
        self.amplitudes = {}
        self.raw_metric = None
        self.raw_fink_matrix = None
        self.raw_fink_right = None
        self.raw_fink_left = None
        self.raw_source = None
        self.raw_h0_source = None
        self.raw_v_source = None
        self.orthogonal_fink_matrix = None
        self.orthogonal_source = None
        self.memory_diagnostics = {}

    def _validate_controls(self, root: int):
        if root < 0:
            raise IndexError("root must be non-negative")
        self.contraction_backend = _utils._normalize_contraction_backend(
            self.contraction_backend
        )
        for name in (
            "metric_atol",
            "metric_rtol",
            "metric_rcond",
            "trunc_thrds",
            "denominator_atol",
            "denominator_rtol",
            "discarded_source_atol",
            "discarded_source_rtol",
            "matrix_atol",
            "matrix_rtol",
            "energy_imag_atol",
            "energy_imag_rtol",
            "reference_residual_warn",
            "reference_residual_error",
            "reference_energy_atol",
            "rdm_atol",
            "rdm_rtol",
        ):
            setattr(
                self,
                name,
                _mrci._finite_nonnegative(getattr(self, name), name=name),
            )
        if (
            self.metric_atol == 0.0
            and self.metric_rcond == 0.0
            and self.trunc_thrds == 0.0
        ):
            raise ValueError("at least one metric cutoff must be positive")
        if self.denominator_atol == 0.0 and self.denominator_rtol == 0.0:
            raise ValueError("at least one denominator cutoff must be positive")
        if self.reference_residual_error < self.reference_residual_warn:
            raise ValueError(
                "reference_residual_error must be at least reference_residual_warn"
            )
        if int(self.rdm_work_memory) <= 0:
            raise ValueError("rdm_work_memory must be positive")

    def _prepare_inputs(
        self,
        mc,
        *,
        root: int,
        mo_coeff,
        pdms,
        eris,
    ):
        mo_coeff = np.asarray(mo_coeff)
        if mo_coeff.ndim != 2:
            raise ValueError("mo_coeff must be a two-dimensional array")
        if pdms is None:
            reference_mo = np.asarray(getattr(mc, "mo_coeff", mo_coeff))
            if not np.array_equal(mo_coeff, reference_mo):
                raise ValueError(
                    "automatic RDMs use mc.mo_coeff; pass transformed raw "
                    "SGF pdms with a different mo_coeff"
                )
            pdms = _mrci._reference_pdms(mc, root)
        nelec_source = getattr(mc.fcisolver, "nelecas", None)
        if nelec_source is None:
            nelec_source = mc.nelecas
        pdms, rdm_diagnostics = _utils.validate_pdms(
            pdms,
            int(mc.ncas),
            _utils._total_nelec(nelec_source),
            atol=self.rdm_atol,
            rtol=self.rdm_rtol,
            work_memory=self.rdm_work_memory,
        )
        if eris is None:
            eris = _utils._dense_eris_from_mc(
                mc,
                mo_coeff,
                roundoff_factor=self.integral_roundoff_factor,
            )
        elif not isinstance(eris, spinor_helper._SpinorERIs):
            raise TypeError("eris must be a spinor_helper._SpinorERIs")
        if (eris.ncore, eris.ncas, eris.nmo) != (
            int(mc.ncore),
            int(mc.ncas),
            int(mo_coeff.shape[1]),
        ):
            raise ValueError("eris partition does not match the CASSCF object")
        return mo_coeff, pdms, eris, rdm_diagnostics

    def kernel(
        self,
        mc=None,
        mo_coeff=None,
        pdms=None,
        eris=None,
        eris_basis="input_mo",
        root=None,
    ):
        """Compute a state-specific full-class-matrix X2C-IC-MRREPT2 energy."""

        total_start = time.perf_counter()
        self._clear_results()
        if mc is None:
            mc = self._mc
        if _utils._has_frozen_orbitals(getattr(mc, "frozen", None)):
            raise NotImplementedError(
                "nonzero frozen spinors are outside X2C-IC-MRREPT2 v1"
            )
        solver_converged = getattr(
            getattr(mc, "fcisolver", None), "converged", None
        )
        if solver_converged is not None and not bool(
            np.all(np.asarray(solver_converged))
        ):
            raise RuntimeError("the selected CASSCF/DMRG reference is not converged")
        if root is None:
            root = self.root
        root = int(root)
        self._validate_controls(root)
        eris_basis = _utils._normalize_eris_basis(eris_basis)
        if eris_basis != "input_mo":
            raise ValueError(
                "X2C-IC-MRREPT2 does not semicanonicalize orbitals; supplied "
                "ERIs must use eris_basis='input_mo'"
            )
        reference_energies = np.asarray(getattr(mc, "e_states", None))
        if reference_energies.ndim:
            available_roots = len(reference_energies)
        else:
            available_roots = int(
                getattr(getattr(mc, "fcisolver", None), "nroots", 1)
            )
        if root >= available_roots:
            raise IndexError(
                f"reference root {root} is outside [0, {available_roots})"
            )
        self.root = root
        if mo_coeff is None:
            mo_coeff = mc.mo_coeff

        start = time.perf_counter()
        mo_coeff, pdms, prepared_eris, rdm_diagnostics = self._prepare_inputs(
            mc,
            root=root,
            mo_coeff=mo_coeff,
            pdms=pdms,
            eris=eris,
        )
        self.sub_times["inputs"] = time.perf_counter() - start
        logger.info(self, "native MR-REPT2 inputs ready in %.3f s",
                    self.sub_times["inputs"])
        self.mo_coeff = mo_coeff
        self.eris = prepared_eris
        self.eris_basis = "input_mo"
        self.reference_energy = _utils._reference_energy(mc, root)
        self.rdm_diagnostics = rdm_diagnostics
        self.integral_symmetry_diagnostics = getattr(
            prepared_eris, "symmetry_diagnostics", None
        )

        start = time.perf_counter()
        equations = _compile_equations()
        self.sub_times["equations"] = time.perf_counter() - start
        logger.info(self, "native MR-REPT2 Wick equations ready in %.3f s",
                    self.sub_times["equations"])
        if equations.maximum_rdm_rank > 4:
            raise RuntimeError("generated MR-REPT2 equations require >4-RDM")
        if self.contraction_backend == "pytblis":
            _utils._validate_tblis_operand_dtypes(
                [
                    (f"h{key}", prepared_eris.get_h1(key))
                    for key in equations.required_h1_blocks
                ]
                + [
                    (f"w{key}", prepared_eris.get_phys(key))
                    for key in equations.required_eri_blocks
                ]
                + [("fAA", prepared_eris.get_h1eff("AA"))]
                + [
                    (f"dm{rank}", density)
                    for rank, density in enumerate(pdms, start=1)
                ]
            )
        evaluator = _mrci._ExpressionEvaluator(
            prepared_eris, pdms, self.contraction_backend
        )
        reference_audit = _mrci._reference_stationarity_audit(
            evaluator,
            equations,
            mc,
            self.reference_energy,
            residual_warn=self.reference_residual_warn,
            residual_error=self.reference_residual_error,
            energy_atol=self.reference_energy_atol,
        )

        layouts = tuple(
            layout
            for layout in _mrci._make_layouts(prepared_eris)
            if layout.key != "ref"
        )
        self.basis_layouts = layouts
        start = time.perf_counter()
        metrics = tuple(
            _build_class_metric(
                layout,
                evaluator,
                equations,
                metric_atol=self.metric_atol,
                metric_rtol=self.metric_rtol,
                metric_rcond=self.metric_rcond,
                trunc_thrds=self.trunc_thrds,
                matrix_atol=self.matrix_atol,
                matrix_rtol=self.matrix_rtol,
            )
            for layout in layouts
        )
        self.sub_times["metric"] = time.perf_counter() - start
        self.metric_diagnostics = {
            metric.layout.key: metric.diagnostics for metric in metrics
        }

        memory_limit = _mrci._effective_memory_limit(self, mc)
        memory = {}
        for metric in metrics:
            estimate = _class_memory_estimate(
                metric.layout.raw_dimension,
                metric.diagnostics["rank"],
                retain_raw_matrices=self.retain_raw_matrices,
                dtype=evaluator.dtype,
            )
            estimate["limit_bytes"] = int(memory_limit)
            estimate["passed"] = bool(
                estimate["estimated_peak_bytes"] <= memory_limit
            )
            memory[metric.layout.key] = estimate
            if not estimate["passed"]:
                raise MemoryError(
                    f"MR-REPT2 class {metric.layout.key} requires an "
                    f"estimated {estimate['estimated_peak_bytes'] / 2**30:.2f} "
                    f"GiB, exceeding {memory_limit / 2**30:.2f} GiB"
                )
        self.memory_diagnostics = memory

        self.raw_metric = {} if self.retain_raw_matrices else None
        self.raw_fink_matrix = {} if self.retain_raw_matrices else None
        self.raw_fink_right = {} if self.retain_raw_matrices else None
        self.raw_fink_left = {} if self.retain_raw_matrices else None
        self.raw_source = {} if self.retain_raw_matrices else None
        self.raw_h0_source = {} if self.retain_raw_matrices else None
        self.raw_v_source = {} if self.retain_raw_matrices else None
        self.orthogonal_fink_matrix = (
            {} if self.retain_raw_matrices else None
        )
        self.orthogonal_source = {} if self.retain_raw_matrices else None

        class_diagnostics = {}
        for metric in metrics:
            key = metric.layout.key
            logger.info(self, "native MR-REPT2 assembling class %s: "
                        "raw=%d retained=%d free-blocks=%d",
                        key, metric.layout.raw_dimension, metric.diagnostics["rank"],
                        len(metric.layout.free_tuples))
            start = time.perf_counter()
            energy, amplitudes, diagnostics, retained = _solve_class(
                self, metric, evaluator, equations
            )
            self.sub_eners[key] = energy
            self.amplitudes[key] = amplitudes
            class_diagnostics[key] = diagnostics
            self.sub_times[key] = time.perf_counter() - start
            if self.retain_raw_matrices:
                self.raw_metric[key] = retained["metric"]
                self.raw_fink_matrix[key] = retained["fink"]
                self.raw_fink_right[key] = retained["fink_right"]
                self.raw_fink_left[key] = retained["fink_left"]
                self.raw_source[key] = retained["source_h"]
                self.raw_h0_source[key] = retained["source_h0"]
                self.raw_v_source[key] = retained["source_v"]
                self.orthogonal_fink_matrix[key] = retained[
                    "fink_orthogonal"
                ]
                self.orthogonal_source[key] = retained[
                    "source_orthogonal"
                ]
            logger.note(
                self,
                "root %d E(%s-%4s) = %20.14f raw=%d rank=%d",
                root,
                self.__class__.__name__,
                key,
                energy,
                metric.layout.raw_dimension,
                metric.diagnostics["rank"],
            )

        self.e_corr = float(sum(self.sub_eners.values()))
        self.denominator_diagnostics = class_diagnostics
        maximum_h0_source = max(
            (
                diagnostics["h0_reference_to_q_source_norm"]
                for diagnostics in class_diagnostics.values()
            ),
            default=0.0,
        )
        self.fink_h0_diagnostics = {
            "definition": (
                "all bare-H monomials preserving electron number separately "
                "in I/A/E"
            ),
            "one_body_blocks": list(equations.h0_one_body_blocks),
            "two_body_blocks": list(equations.h0_two_body_blocks),
            "one_body_retained_count": len(equations.h0_one_body_blocks),
            "two_body_retained_count": len(equations.h0_two_body_blocks),
            "one_body_rejected_count": 3**2 - len(
                equations.h0_one_body_blocks
            ),
            "two_body_rejected_count": 3**4 - len(
                equations.h0_two_body_blocks
            ),
            "reference_stationarity": reference_audit,
            "maximum_h0_reference_to_q_source_norm": maximum_h0_source,
            "reference_to_q_coupling_is_v_only": bool(
                maximum_h0_source
                <= _source_threshold(
                    max(
                        (
                            diagnostics["source_norm"]
                            for diagnostics in class_diagnostics.values()
                        ),
                        default=0.0,
                    ),
                    atol=self.discarded_source_atol,
                    rtol=self.discarded_source_rtol,
                )
            ),
            "class_matrices_are_full": True,
            "contractions": dict(evaluator.evaluation_diagnostics),
            "semicanonicalization_used": False,
            "orbital_energies_used": False,
        }
        self.sub_times["total"] = time.perf_counter() - total_start
        logger.note(
            self,
            "root %d X2C-IC-MRREPT2 E_corr=%.16g E_tot=%.16g",
            root,
            self.e_corr,
            self.e_tot,
        )
        logger.info(
            self,
            "MR-REPT2 timings: %s",
            " | ".join(
                f"{name}={value:.2f}s" for name, value in self.sub_times.items()
            ),
        )
        gc.collect()
        return self.e_corr


X2CICMRREPT2 = WickX2CICMRREPT2
