#!/usr/bin/env python
# SPDX-License-Identifier: GPL-3.0-or-later
r"""Dense no-Kramers X2C strongly-contracted NEVPT2.

The spin-orbital Hamiltonian used by this module is

.. math::

   H = \sum_{pq} h_{pq} C_p D_q
       + \frac12 \sum_{pqrs} w_{pqrs} C_p C_q D_s D_r,

with unantisymmetrized integrals

.. math::

   w_{pqrs} = \mathrm{eri}_{prqs}, \qquad
   \mathrm{eri}_{pqrs} = (pq|rs).

All indices label individual complex spinors.  There is no spin summation,
Kramers compression, ``E1/E2`` spin-free operator, or spatial ``gamma``
factor.  The eight strongly-contracted spaces follow Sections I.E--I.L of
the Supporting Information to Shiozaki and Mizukami, JCTC 2015:

``ijrs`` (E, Eqs. 13--14), ``ijr`` (F, Eqs. 15--17), ``ij`` (G,
Eqs. 18--20), ``rsi`` (H, Eqs. 21--23), ``ir`` (I, Eqs. 24--27), ``i``
(J, Eqs. 28--30), ``rs`` (K, Eqs. 31--33), and ``r`` (L, Eqs. 34--36).

The actual norm and Dyall-commutator contractions are generated by the
installed Block2 Wick bindings.  Active expectation values are lowered to
raw SGF particle RDMs with axes

``dm_k[p1,...,pk,qk,...,q1] = <C[p1]...C[pk]D[qk]...D[q1]>``.

The default ``strict_si`` denominator is the one-sided expression printed in
the SI.  Its imaginary residual is a hard error before the accepted value is
converted to real arithmetic.  The independently generated left branch is
always checked against the adjoint of the right branch.  An explicit
``hermitianized`` mode retains the manifestly Hermitian half-sum as a
finite-MPS stabilization, but records whether the one-sided SI gate failed;
it is therefore never silently presented as the literal SI expression.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import itertools
import time
from types import SimpleNamespace
from typing import Any

import numpy as np
from pyscf import lib
from pyscf.lib import logger

try:
    from . import spinor_helper
except ImportError:  # pragma: no cover - permits running the reference file
    import spinor_helper


__all__ = [
    "SUBSPACE_ORDER",
    "WickX2CSCNEVPT2",
    "X2CSCNEVPT2",
    "dump_wick_equations",
    "make_dm1234",
    "make_rdm1",
    "make_rdm2",
    "make_rdm3",
    "make_rdm4",
    "validate_pdms",
]


SUBSPACE_ORDER = ("ijrs", "rsi", "ijr", "rs", "ij", "ir", "r", "i")

_ERIS_BASES = frozenset(("input_mo", "semicanonical"))
_DENOMINATOR_MODES = frozenset(("hermitianized", "strict_si"))
_CONTRACTION_BACKENDS = frozenset(("numpy", "pytblis"))
_DEFAULT_CONTRACTION_BACKEND = "pytblis"


def _select_root_ci(ci, root, *, nroots=1):
    """Select a multiroot CI handle without slicing a single CI vector."""

    root = int(root)
    if isinstance(ci, (list, tuple, range)):
        return ci[root]
    if isinstance(ci, np.ndarray) and ci.ndim == 1:
        if ci.dtype == object or (int(nroots) > 1 and len(ci) == int(nroots)):
            return ci[root]
    return ci


def _total_nelec(nelecas) -> int:
    """Normalize scalar or ``(nalpha, nbeta)`` active-electron counts."""

    if np.isscalar(nelecas):
        total = int(nelecas)
    else:
        values = tuple(nelecas)
        if not values:
            raise ValueError("nelecas must not be empty")
        total = sum(int(value) for value in values)
    if total < 0:
        raise ValueError("nelecas must be non-negative")
    return total


def _has_frozen_orbitals(frozen) -> bool:
    """Return whether a PySCF-style frozen-orbital specification is active."""

    if frozen is None:
        return False
    array = np.asarray(frozen)
    if array.ndim == 0:
        return bool(array.item())
    return bool(array.size)


def _normalize_eris_basis(eris_basis) -> str:
    if not isinstance(eris_basis, str) or eris_basis not in _ERIS_BASES:
        choices = ", ".join(sorted(_ERIS_BASES))
        raise ValueError(f"eris_basis must be one of: {choices}")
    return eris_basis


def _normalize_denominator_mode(denominator_mode) -> str:
    if (
        not isinstance(denominator_mode, str)
        or denominator_mode not in _DENOMINATOR_MODES
    ):
        choices = ", ".join(sorted(_DENOMINATOR_MODES))
        raise ValueError(f"denominator_mode must be one of: {choices}")
    return denominator_mode


def _normalize_contraction_backend(contraction_backend) -> str:
    if (
        not isinstance(contraction_backend, str)
        or contraction_backend not in _CONTRACTION_BACKENDS
    ):
        choices = ", ".join(sorted(_CONTRACTION_BACKENDS))
        raise ValueError(f"contraction_backend must be one of: {choices}")
    return contraction_backend


@lru_cache(maxsize=2)
def _wick_einsum_namespace(contraction_backend):
    """Return the late-bound ``np.einsum`` namespace for Wick source."""

    contraction_backend = _normalize_contraction_backend(contraction_backend)
    if contraction_backend == "numpy":
        einsum = np.einsum
    else:
        try:
            from pytblis import einsum
        except ImportError as error:  # pragma: no cover - required dependency
            raise ImportError(
                "contraction_backend='pytblis' requires the pytblis package"
            ) from error
    return SimpleNamespace(einsum=einsum)


# Each expression is the fixed-free-index component of P_omega H |Phi>.
# The factors and signs follow the unantisymmetrized Hamiltonian above.  In
# particular, a fixed pair is represented by its explicit exchange
# difference, whereas a fully summed active pair carries no extra 1/2.
# These are the operator counterparts of SI Sections I.E--I.L.
_PERTURBER_EXPRESSIONS = {
    # S_ij,rs^(0), SI Eqs. (13)--(14); i<j and r<s.
    "ijrs": (
        "w[rsij] C[r] C[s] D[j] D[i]\n"
        " - w[rsji] C[r] C[s] D[j] D[i]"
    ),
    # S_i,rs^(-1), SI Eqs. (21)--(23); r<s.
    "rsi": (
        "SUM <a> w[rsia] C[r] C[s] D[a] D[i]\n"
        " - SUM <a> w[sria] C[r] C[s] D[a] D[i]"
    ),
    # S_ij,r^(1), SI Eqs. (15)--(17); i<j.
    "ijr": (
        "SUM <a> w[raij] C[r] C[a] D[j] D[i]\n"
        " - SUM <a> w[raji] C[r] C[a] D[j] D[i]"
    ),
    # S_rs^(-2), SI Eqs. (31)--(33); r<s.
    "rs": "SUM <ab> w[rsab] C[r] C[s] D[b] D[a]",
    # S_ij^(2), SI Eqs. (18)--(20); i<j.
    "ij": "SUM <ab> w[abij] C[a] C[b] D[j] D[i]",
    # S_i,r^(0), SI Eqs. (24)--(27).
    "ir": (
        "SUM <ab> w[raib] C[r] C[a] D[b] D[i]\n"
        " - SUM <ab> w[rabi] C[r] C[a] D[b] D[i]\n"
        " + h[ri] C[r] D[i]"
    ),
    # S_r^(-1), SI Eqs. (34)--(36).
    "r": (
        "SUM <abc> w[rabc] C[r] C[a] D[c] D[b]\n"
        " + SUM <a> h[ra] C[r] D[a]"
    ),
    # S_i^(1), SI Eqs. (28)--(30).  The dummy ordering uses the AAIA block
    # without invoking an ERI permutation rule.
    "i": (
        "SUM <abc> w[baic] C[b] C[a] D[c] D[i]\n"
        " + SUM <a> h[ai] C[a] D[i]"
    ),
}

_PAIR_RESTRICTIONS = {
    "ijrs": ((0, 1), (2, 3)),
    "rsi": ((0, 1),),
    "ijr": ((0, 1),),
    "rs": ((0, 1),),
    "ij": ((0, 1),),
    "ir": (),
    "r": (),
    "i": (),
}

_H1_KEYS = ("AA", "AI", "EI", "EA")
_W_KEYS = (
    "AAAA",
    "EAAA",
    "EAIA",
    "EAAI",
    "AAIA",
    "EEIA",
    "EAII",
    "EEAA",
    "AAII",
    "EEII",
)


@dataclass(frozen=True)
class _WickEquationBundle:
    norm_code: dict[str, str]
    right_commutator_code: dict[str, str]
    left_commutator_code: dict[str, str]
    commutator_code: dict[str, str]
    norm_text: dict[str, str]
    right_commutator_text: dict[str, str]
    left_commutator_text: dict[str, str]
    commutator_text: dict[str, str]


def _block2_wick_types():
    try:
        from block2 import (
            MapPStrIntVectorWickPermutation,
            MapWickIndexTypesSet,
            VectorWickIndex,
            VectorWickString,
            VectorWickTensor,
            WickExpr,
            WickIndex,
            WickIndexTypes,
            WickString,
            WickTensor,
            WickTensorTypes,
        )
    except ImportError as error:  # pragma: no cover - installation error
        raise RuntimeError(
            "block2 must be installed with the internal-contraction Wick bindings"
        ) from error
    return {
        "MapPStrIntVectorWickPermutation": MapPStrIntVectorWickPermutation,
        "MapWickIndexTypesSet": MapWickIndexTypesSet,
        "VectorWickIndex": VectorWickIndex,
        "VectorWickString": VectorWickString,
        "VectorWickTensor": VectorWickTensor,
        "WickExpr": WickExpr,
        "WickIndex": WickIndex,
        "WickIndexTypes": WickIndexTypes,
        "WickString": WickString,
        "WickTensor": WickTensor,
        "WickTensorTypes": WickTensorTypes,
    }


def _wick_parsers(types):
    index_types = types["WickIndexTypes"]
    index = types["WickIndex"]
    index_map = types["MapWickIndexTypesSet"]()
    index_map[index_types.Inactive] = index.parse_set("ijklmnoz")
    index_map[index_types.Active] = index.parse_set("abcdefghpq")
    index_map[index_types.External] = index.parse_set("rstuvwxy")

    # Deliberately empty.  qc_phys/qc_chem contain ordinary permutations that
    # are false for general complex spinors when the required conjugation is
    # omitted.  Hermitian ERI identities are numerical checks, not Wick rules.
    permutation_map = types["MapPStrIntVectorWickPermutation"]()
    parse = lambda expression: types["WickExpr"].parse(
        expression, index_map, permutation_map
    )
    parse_tensor = lambda expression: types["WickTensor"].parse(
        expression, index_map, permutation_map
    )
    return parse, parse_tensor


def _conjugate_with_coefficients(expression, types):
    """Hermitian-conjugate operators and explicitly rename coefficient data.

    Block2 0.5.4rc16 reverses/adjoints C/D in ``WickExpr.conjugate()`` but
    intentionally does not conjugate ordinary coefficient tensors.  The
    renamed ``hc`` and ``wc`` arrays are bound to elementwise conjugates at
    execution time.
    """

    tensor_type = types["WickTensorTypes"]
    result = expression.conjugate()
    names = {"h": "hc", "w": "wc"}
    for term in result.terms:
        for tensor in term.tensors:
            if tensor.type == tensor_type.Tensor and tensor.name in names:
                tensor.name = names[tensor.name]
    return result


def _vacuum_reduce(expression):
    """Contract the external vacuum and filled inactive determinant."""

    return (
        expression.expand()
        .remove_external()
        .remove_inactive()
        .simplify()
    )


def _lower_active_operators(expression, types):
    """Replace each active normal-ordered C...D... string by one raw RDM."""

    tensor_type = types["WickTensorTypes"]
    vector_index = types["VectorWickIndex"]
    vector_string = types["VectorWickString"]
    vector_tensor = types["VectorWickTensor"]
    wick_expr = types["WickExpr"]
    wick_string = types["WickString"]
    wick_tensor = types["WickTensor"]

    lowered_terms = vector_string()
    for term in expression.terms:
        coefficients = vector_tensor()
        operators = []
        for tensor in term.tensors:
            if tensor.type in (
                tensor_type.CreationOperator,
                tensor_type.DestroyOperator,
            ):
                operators.append(tensor)
            else:
                coefficients.append(tensor)

        if operators:
            kinds = [tensor.type for tensor in operators]
            ncreation = kinds.count(tensor_type.CreationOperator)
            ndestroy = kinds.count(tensor_type.DestroyOperator)
            expected = [tensor_type.CreationOperator] * ncreation
            expected += [tensor_type.DestroyOperator] * ndestroy
            if ncreation != ndestroy or kinds != expected:
                raise RuntimeError(
                    "Wick left an active operator string that is not a "
                    f"particle RDM: {term!r}"
                )
            if ncreation > 4:
                raise RuntimeError(
                    "SC-NEVPT2 Wick expansion requested an active "
                    f"{ncreation}-RDM; recheck the commutator: {term!r}"
                )
            indices = vector_index()
            for tensor in operators:
                indices.append(tensor.indices[0])
            coefficients.append(wick_tensor(f"dm{ncreation}", indices))

        lowered_terms.append(
            wick_string(coefficients, term.ctr_indices, term.factor)
        )
    return wick_expr(lowered_terms).simplify()


@lru_cache(maxsize=1)
def _compile_wick_equations() -> _WickEquationBundle:
    types = _block2_wick_types()
    parse, parse_tensor = _wick_parsers(types)

    h_dyall_active = parse("SUM <ab> h[ab] C[a] D[b]")
    h_dyall_active += parse(
        "0.5 SUM <abcd> w[abcd] C[a] C[b] D[d] D[c]"
    )

    norm_code = {}
    right_commutator_code = {}
    left_commutator_code = {}
    commutator_code = {}
    norm_text = {}
    right_commutator_text = {}
    left_commutator_text = {}
    commutator_text = {}
    for key in SUBSPACE_ORDER:
        ket = parse(_PERTURBER_EXPRESSIONS[key])
        bra = _conjugate_with_coefficients(ket, types)

        norm = _lower_active_operators(_vacuum_reduce(bra * ket), types)

        # [one-/two-body H_D, at-most-two-body T] is connected and contains
        # at most three creation and three destruction operators.  Asking
        # Wick for max_unctr=6 discards only the zero-contraction H2*T2
        # products, which cancel identically in the commutator.  This ordering
        # is important when w has intentionally been given no permutation
        # rules: otherwise Block2 cannot graph-canonicalize two dummy-index
        # forms of that exact zero before the bra is multiplied, producing a
        # spurious 5-RDM in the r/i classes.
        connected_right = (h_dyall_active ^ ket).expand(6).simplify()
        right_commutator = _lower_active_operators(
            _vacuum_reduce(bra * connected_right), types
        )
        connected_left = (bra ^ h_dyall_active).expand(6).simplify()
        left_commutator = _lower_active_operators(
            _vacuum_reduce(connected_left * ket), types
        )

        # The SI one-sided commutator is real when the CAS reference is an
        # exact eigenstate of the active Dyall Hamiltonian.  A converged DMRG
        # MPS has a finite eigen-equation residual, however, so that
        # one-sided form need not itself be Hermitian.  Form its Hermitian
        # part explicitly at the operator/Wick level:
        #
        #   1/2 { T^dagger [H_D,T] + [T^dagger,H_D] T }.
        #
        # This is exactly the SI expression in the eigenstate limit, remains
        # connected and requires no RDM above rank four.  The independently
        # generated left and right branches are retained so execution can
        # verify their adjoint relation; this is deliberately not a final
        # ``.real`` projection of the one-sided numerical result.
        commutator = (0.5 * (right_commutator + left_commutator)).simplify()

        norm_target = parse_tensor(f"norm[{key}]")
        commutator_target = parse_tensor(f"commutator[{key}]")
        norm_code[key] = norm.to_einsum(norm_target)
        right_commutator_code[key] = right_commutator.to_einsum(
            commutator_target
        )
        left_commutator_code[key] = left_commutator.to_einsum(
            commutator_target
        )
        commutator_code[key] = commutator.to_einsum(commutator_target)
        norm_text[key] = repr(norm)
        right_commutator_text[key] = repr(right_commutator)
        left_commutator_text[key] = repr(left_commutator)
        commutator_text[key] = repr(commutator)

    return _WickEquationBundle(
        norm_code=norm_code,
        right_commutator_code=right_commutator_code,
        left_commutator_code=left_commutator_code,
        commutator_code=commutator_code,
        norm_text=norm_text,
        right_commutator_text=right_commutator_text,
        left_commutator_text=left_commutator_text,
        commutator_text=commutator_text,
    )


def dump_wick_equations(filename: str | None = None) -> str:
    """Return (and optionally write) auditable equations for all eight spaces."""

    equations = _compile_wick_equations()
    sections = []
    for key in SUBSPACE_ORDER:
        sections.extend(
            (
                f"[{key}] perturber\n{_PERTURBER_EXPRESSIONS[key]}",
                f"[{key}] norm expression\n{equations.norm_text[key]}",
                f"[{key}] norm einsum\n{equations.norm_code[key]}",
                f"[{key}] right Dyall commutator expression\n"
                f"{equations.right_commutator_text[key]}",
                f"[{key}] right Dyall commutator einsum\n"
                f"{equations.right_commutator_code[key]}",
                f"[{key}] left Dyall commutator expression\n"
                f"{equations.left_commutator_text[key]}",
                f"[{key}] left Dyall commutator einsum\n"
                f"{equations.left_commutator_code[key]}",
                f"[{key}] Hermitian Dyall commutator expression\n"
                f"{equations.commutator_text[key]}",
                f"[{key}] Hermitian Dyall commutator einsum\n"
                f"{equations.commutator_code[key]}",
            )
        )
    text = "\n\n".join(sections) + "\n"
    if filename is not None:
        with open(filename, "w", encoding="utf-8") as handle:
            handle.write(text)
    return text


def _free_index_shape(key: str, eris: spinor_helper._SpinorERIs):
    return tuple(eris.ncore if char in "ij" else eris.nvirt for char in key)


def _orbital_gap(key: str, core_energy, virtual_energy):
    shape = tuple(
        len(core_energy) if char in "ij" else len(virtual_energy)
        for char in key
    )
    gap = np.zeros(shape, dtype=float)
    for axis, char in enumerate(key):
        values = -np.asarray(core_energy) if char in "ij" else np.asarray(
            virtual_energy
        )
        reshape = [1] * len(key)
        reshape[axis] = len(values)
        gap += values.reshape(reshape)
    return gap


def _strict_pair_mask(key: str, shape):
    mask = np.ones(shape, dtype=bool)
    if not shape or any(size == 0 for size in shape):
        return mask
    grid = np.indices(shape, sparse=True)
    for left, right in _PAIR_RESTRICTIONS[key]:
        mask &= grid[left] < grid[right]
    return mask


def _require_real(values, *, root, subspace, quantity, atol, rtol):
    values = np.asarray(values)
    if not np.all(np.isfinite(values)):
        raise FloatingPointError(
            f"root {root} subspace {subspace}: {quantity} contains non-finite values"
        )
    if not np.iscomplexobj(values):
        return values.astype(float, copy=False)
    limit = atol + rtol * np.maximum(1.0, np.abs(values.real))
    violation = np.abs(values.imag) - limit
    if np.any(violation > 0.0):
        maximum = float(np.max(np.abs(values.imag)))
        raise FloatingPointError(
            f"root {root} subspace {subspace}: {quantity} is not real; "
            f"maximum imaginary part = {maximum:.3e}"
        )
    return values.real


def _require_adjoint_pair(
    left,
    right,
    mask,
    *,
    root,
    subspace,
    atol,
    rtol,
):
    """Verify independently generated scalar branches are adjoints."""

    left = np.asarray(left)
    right = np.asarray(right)
    mask = np.asarray(mask, dtype=bool)
    if left.shape != right.shape or left.shape != mask.shape:
        raise ValueError("adjoint-branch arrays or mask have different shapes")
    selected_left = left[mask]
    selected_right = right[mask]
    if not np.all(np.isfinite(selected_left)) or not np.all(
        np.isfinite(selected_right)
    ):
        raise FloatingPointError(
            f"root {root} subspace {subspace}: Dyall commutator branch "
            "contains non-finite values"
        )
    if not selected_left.size:
        return {
            "maximum_adjoint_error": 0.0,
            "maximum_adjoint_error_index": [],
            "reality_limit_at_maximum_error": float(atol + rtol),
        }

    error = np.abs(selected_left - selected_right.conj())
    limit = atol + rtol * np.maximum(
        1.0, np.maximum(np.abs(selected_left), np.abs(selected_right))
    )
    local_index = int(np.argmax(error))
    selected_flat = np.flatnonzero(mask)
    full_index = np.unravel_index(
        int(selected_flat[local_index]), left.shape
    )
    if error[local_index] > limit[local_index]:
        raise FloatingPointError(
            f"root {root} subspace {subspace}: independently generated "
            "Dyall commutator branches are not adjoints; maximum error = "
            f"{float(error[local_index]):.3e} at {full_index}"
        )
    return {
        "maximum_adjoint_error": float(error[local_index]),
        "maximum_adjoint_error_index": [int(index) for index in full_index],
        "reality_limit_at_maximum_error": float(limit[local_index]),
    }


def _scalar_reality_diagnostics(values, mask, *, atol, rtol):
    """Return the largest imaginary residual of a selected scalar array."""

    values = np.asarray(values)
    mask = np.asarray(mask, dtype=bool)
    selected = values[mask]
    if not selected.size:
        return {
            "maximum_imaginary_part": 0.0,
            "maximum_imaginary_index": [],
            "reality_limit_at_maximum": float(atol + rtol),
            "real_part_at_maximum": 0.0,
            "maximum_imaginary_to_limit_ratio": 0.0,
            "maximum_ratio_index": [],
            "gate_passed": True,
        }
    magnitude = np.abs(selected.imag)
    limits = atol + rtol * np.maximum(1.0, np.abs(selected.real))
    local_index = int(np.argmax(magnitude))
    selected_flat = np.flatnonzero(mask)
    full_index = np.unravel_index(
        int(selected_flat[local_index]), values.shape
    )
    ratio = np.divide(
        magnitude,
        limits,
        out=np.full_like(magnitude, np.inf, dtype=float),
        where=limits > 0.0,
    )
    ratio_index = int(np.argmax(ratio))
    ratio_full_index = np.unravel_index(
        int(selected_flat[ratio_index]), values.shape
    )
    return {
        "maximum_imaginary_part": float(magnitude[local_index]),
        "maximum_imaginary_index": [int(index) for index in full_index],
        "reality_limit_at_maximum": float(limits[local_index]),
        "real_part_at_maximum": float(selected[local_index].real),
        "maximum_imaginary_to_limit_ratio": float(ratio[ratio_index]),
        "maximum_ratio_index": [int(index) for index in ratio_full_index],
        "gate_passed": bool(np.all(magnitude <= limits)),
    }


def _audit_one_sided_si_denominator(
    norm,
    right_commutator,
    one_sided_gap,
    mask,
    *,
    root,
    subspace,
    gap_atol,
    gap_rtol,
    numerator_noise_allowance,
    energy_imag_l1_tol,
    projection_shift_l1_tol,
    denominator_tol,
    enforce,
):
    """Audit the literal SI denominator with a bounded near-null exception.

    Dividing a roundoff-sized imaginary numerator by a nearly null perturber
    norm can make the raw gap look complex even for an exact eigenvector.  A
    direct gap-gate failure is therefore accepted only when the numerator is
    within an explicit absolute noise allowance *and* both the imaginary
    energy and real-projection shift have small cancellation-free L1 bounds.
    """

    norm = np.asarray(norm)
    right_commutator = np.asarray(right_commutator)
    one_sided_gap = np.asarray(one_sided_gap)
    mask = np.asarray(mask, dtype=bool)
    if not (
        norm.shape
        == right_commutator.shape
        == one_sided_gap.shape
        == mask.shape
    ):
        raise ValueError("one-sided SI audit arrays or mask have different shapes")

    tolerances = {
        "gap_atol": float(gap_atol),
        "gap_rtol": float(gap_rtol),
        "numerator_noise_allowance": float(numerator_noise_allowance),
        "energy_imag_l1_tol": float(energy_imag_l1_tol),
        "projection_shift_l1_tol": float(projection_shift_l1_tol),
    }
    if any(
        not np.isfinite(value) or value < 0.0
        for value in tolerances.values()
    ):
        raise ValueError("strict-SI audit tolerances must be finite and non-negative")

    selected_norm = np.asarray(norm[mask].real, dtype=float)
    selected_numerator = right_commutator[mask]
    selected_gap = one_sided_gap[mask]
    selected_flat = np.flatnonzero(mask)
    if not selected_norm.size:
        diagnostics = {
            **_scalar_reality_diagnostics(
                one_sided_gap,
                mask,
                atol=tolerances["gap_atol"],
                rtol=tolerances["gap_rtol"],
            ),
            "strict_si_compatible": True,
            "direct_gap_gate_passed": True,
            "raw_numerator_gate_passed": True,
            "positive_denominator_gate_passed": True,
            "roundoff_limited_near_null_count": 0,
            "roundoff_limited_near_null_indices": [],
            "maximum_numerator_imaginary_part": 0.0,
            "maximum_numerator_imaginary_index": [],
            "maximum_numerator_imaginary_to_limit_ratio": 0.0,
            "maximum_numerator_ratio_index": [],
            "imaginary_energy_l1": 0.0,
            "imaginary_energy_l1_tolerance": tolerances[
                "energy_imag_l1_tol"
            ],
            "imaginary_energy_l1_gate_passed": True,
            "real_projection_shift_l1": 0.0,
            "real_projection_shift_l1_tolerance": tolerances[
                "projection_shift_l1_tol"
            ],
            "real_projection_shift_l1_gate_passed": True,
            "numerator_noise_allowance": tolerances[
                "numerator_noise_allowance"
            ],
            "numerical_policy": "explicit-calibrated-numerator-allowance",
        }
        return selected_norm, diagnostics

    if (
        not np.all(np.isfinite(selected_norm))
        or not np.all(np.isfinite(selected_numerator))
        or not np.all(np.isfinite(selected_gap))
    ):
        raise FloatingPointError(
            f"root {root} subspace {subspace}: one-sided SI audit contains "
            "non-finite inputs"
        )

    gap_imag = np.abs(selected_gap.imag)
    gap_limit = tolerances["gap_atol"] + tolerances["gap_rtol"] * np.maximum(
        1.0, np.abs(selected_gap.real)
    )
    numerator_imag = np.abs(selected_numerator.imag)
    numerator_limit = (
        tolerances["numerator_noise_allowance"] + selected_norm * gap_limit
    )
    direct_gap_pass = gap_imag <= gap_limit
    numerator_pass = numerator_imag <= numerator_limit
    near_null = (
        ~direct_gap_pass
        & (
            selected_norm * gap_limit
            < tolerances["numerator_noise_allowance"]
        )
        & numerator_pass
    )
    gap_accepted = direct_gap_pass | near_null
    positive = selected_gap.real > denominator_tol

    with np.errstate(divide="ignore", invalid="ignore", over="ignore"):
        complex_energy = -selected_norm / selected_gap
        projected_energy = -selected_norm / selected_gap.real
    finite_energies = np.all(np.isfinite(complex_energy)) and np.all(
        np.isfinite(projected_energy)
    )
    if finite_energies:
        imaginary_energy_l1 = float(np.sum(np.abs(complex_energy.imag)))
        projection_shift_l1 = float(
            np.sum(np.abs(projected_energy - complex_energy.real))
        )
    else:
        imaginary_energy_l1 = np.inf
        projection_shift_l1 = np.inf
    energy_imag_pass = (
        imaginary_energy_l1 <= tolerances["energy_imag_l1_tol"]
    )
    projection_shift_pass = (
        projection_shift_l1 <= tolerances["projection_shift_l1_tol"]
    )
    strict_compatible = bool(
        np.all(gap_accepted)
        and np.all(numerator_pass)
        and np.all(positive)
        and finite_energies
        and energy_imag_pass
        and projection_shift_pass
    )

    def full_index(local_index):
        return [
            int(index)
            for index in np.unravel_index(
                int(selected_flat[int(local_index)]), mask.shape
            )
        ]

    numerator_ratio = np.divide(
        numerator_imag,
        numerator_limit,
        out=np.full_like(numerator_imag, np.inf, dtype=float),
        where=numerator_limit > 0.0,
    )
    numerator_max = int(np.argmax(numerator_imag))
    numerator_ratio_max = int(np.argmax(numerator_ratio))
    near_null_local = np.flatnonzero(near_null)
    diagnostics = {
        **_scalar_reality_diagnostics(
            one_sided_gap,
            mask,
            atol=tolerances["gap_atol"],
            rtol=tolerances["gap_rtol"],
        ),
        "strict_si_compatible": strict_compatible,
        "direct_gap_gate_passed": bool(np.all(direct_gap_pass)),
        "raw_numerator_gate_passed": bool(np.all(numerator_pass)),
        "positive_denominator_gate_passed": bool(np.all(positive)),
        "roundoff_limited_near_null_count": int(len(near_null_local)),
        "roundoff_limited_near_null_indices": [
            full_index(index) for index in near_null_local
        ],
        "maximum_numerator_imaginary_part": float(
            numerator_imag[numerator_max]
        ),
        "maximum_numerator_imaginary_index": full_index(numerator_max),
        "maximum_numerator_imaginary_to_limit_ratio": float(
            numerator_ratio[numerator_ratio_max]
        ),
        "maximum_numerator_ratio_index": full_index(numerator_ratio_max),
        "imaginary_energy_l1": imaginary_energy_l1,
        "imaginary_energy_l1_tolerance": tolerances["energy_imag_l1_tol"],
        "imaginary_energy_l1_gate_passed": bool(energy_imag_pass),
        "real_projection_shift_l1": projection_shift_l1,
        "real_projection_shift_l1_tolerance": tolerances[
            "projection_shift_l1_tol"
        ],
        "real_projection_shift_l1_gate_passed": bool(projection_shift_pass),
        "numerator_noise_allowance": tolerances[
            "numerator_noise_allowance"
        ],
        "numerical_policy": "explicit-calibrated-numerator-allowance",
    }
    if enforce and not strict_compatible:
        raise FloatingPointError(
            f"root {root} subspace {subspace}: one-sided SI denominator "
            "audit failed; "
            f"max |Im gap|={float(np.max(gap_imag)):.3e}, "
            f"max numerator ratio={float(np.max(numerator_ratio)):.3e}, "
            f"Im(E) L1={imaginary_energy_l1:.3e}, "
            f"projection shift L1={projection_shift_l1:.3e}"
        )
    return selected_gap.real, diagnostics


def _validate_zero_norm_commutator(
    values,
    mask,
    *,
    root,
    subspace,
    atol,
    rtol,
):
    """Gate and describe the Hermitian numerator of discarded perturbers."""

    values = np.asarray(values)
    mask = np.asarray(mask, dtype=bool)
    if values.shape != mask.shape:
        raise ValueError("zero-norm commutator array and mask have different shapes")
    selected = values[mask]
    if not np.all(np.isfinite(selected)):
        raise FloatingPointError(
            f"root {root} subspace {subspace}: zero-norm Dyall commutator "
            "contains non-finite values"
        )
    if not selected.size:
        return {
            "maximum_absolute_value": 0.0,
            "maximum_absolute_index": [],
            "acceptance_limit_at_maximum": float(atol + rtol),
            "gate_passed": True,
        }

    magnitude = np.abs(selected)
    limit = atol + rtol * np.maximum(1.0, np.abs(selected.real))
    local_index = int(np.argmax(magnitude))
    selected_flat = np.flatnonzero(mask)
    full_index = np.unravel_index(
        int(selected_flat[local_index]), values.shape
    )
    if magnitude[local_index] > limit[local_index]:
        raise FloatingPointError(
            f"root {root} subspace {subspace}: a zero-norm perturber has "
            f"nonzero Dyall commutator {float(magnitude[local_index]):.3e} "
            f"at {full_index}"
        )
    return {
        "maximum_absolute_value": float(magnitude[local_index]),
        "maximum_absolute_index": [int(index) for index in full_index],
        "acceptance_limit_at_maximum": float(limit[local_index]),
        "gate_passed": True,
    }


def _execution_context(eris, pdms):
    context = {
        "deltaAA": np.eye(eris.ncas),
        "deltaII": np.eye(eris.ncore),
        "deltaEE": np.eye(eris.nvirt),
    }
    for rank, density in enumerate(pdms, start=1):
        context[f"dm{rank}{'A' * (2 * rank)}"] = density
    for key in _H1_KEYS:
        value = eris.get_h1eff(key)
        context[f"h{key}"] = value
        context[f"hc{key}"] = value.conj()
    for key in _W_KEYS:
        value = eris.get_phys(key)
        context[f"w{key}"] = value
        context[f"wc{key}"] = value.conj()
    return context


def _evaluate_wick_subspaces(
    eris,
    pdms,
    core_energy,
    virtual_energy,
    *,
    root=0,
    scalar_atol=1.0e-10,
    scalar_rtol=1.0e-9,
    norm_tol=1.0e-14,
    denominator_tol=1.0e-12,
    denominator_mode="strict_si",
    si_gap_imag_atol=1.0e-10,
    si_gap_imag_rtol=1.0e-9,
    si_numerator_noise_allowance=1.0e-12,
    si_energy_imag_l1_tol=1.0e-10,
    si_projection_shift_l1_tol=1.0e-12,
    contraction_backend=_DEFAULT_CONTRACTION_BACKEND,
    return_arrays=False,
    return_timings=False,
    return_diagnostics=False,
):
    """Evaluate all generated equations in the supplied semicanonical basis."""

    denominator_mode = _normalize_denominator_mode(denominator_mode)
    contraction_backend = _normalize_contraction_backend(contraction_backend)
    # Block2 emits source containing ``np.einsum``.  That global name is
    # resolved only here at exec time, so the cached source is backend-agnostic.
    wick_globals = {
        "np": _wick_einsum_namespace(contraction_backend),
    }
    equations = _compile_wick_equations()
    base_context = _execution_context(eris, pdms)
    sub_eners = {}
    sub_norms = {}
    sub_gaps = {}
    arrays = {}
    timings = {}
    realness_diagnostics = {}

    for key in SUBSPACE_ORDER:
        subspace_start = time.perf_counter()
        shape = _free_index_shape(key, eris)
        dtype = np.result_type(
            np.complex128,
            eris.h1eff.dtype,
            eris.pppp.dtype,
            *(density.dtype for density in pdms),
        )
        norm = np.zeros(shape, dtype=dtype)
        right_commutator = np.zeros(shape, dtype=dtype)
        left_commutator = np.zeros(shape, dtype=dtype)
        local_context = dict(base_context)
        local_context.update(norm=norm)
        exec(equations.norm_code[key], wick_globals, local_context)
        local_context["commutator"] = right_commutator
        exec(
            equations.right_commutator_code[key],
            wick_globals,
            local_context,
        )
        local_context["commutator"] = left_commutator
        exec(
            equations.left_commutator_code[key],
            wick_globals,
            local_context,
        )
        # This reconciles two independently contracted representations of the
        # *same one-sided* scalar.  In exact arithmetic left.conj() == right,
        # so unlike the Hermitian half-sum below it does not remove a physical
        # one-sided imaginary residual.
        si_right_commutator = 0.5 * (
            right_commutator + left_commutator.conj()
        )
        commutator = 0.5 * (right_commutator + left_commutator)

        ordered = _strict_pair_mask(key, shape)
        branch_diagnostics = _require_adjoint_pair(
            left_commutator,
            right_commutator,
            ordered,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        selected_norm = norm[ordered]
        selected_norm = _require_real(
            selected_norm,
            root=root,
            subspace=key,
            quantity="norm",
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        if np.any(selected_norm < -norm_tol):
            minimum = float(np.min(selected_norm))
            raise FloatingPointError(
                f"root {root} subspace {key}: negative norm {minimum:.3e}"
            )

        nonzero_flat = selected_norm > norm_tol
        nonzero = np.zeros(shape, dtype=bool)
        nonzero[ordered] = nonzero_flat
        selected_commutator = _require_real(
            commutator[nonzero],
            root=root,
            subspace=key,
            quantity="Hermitian Dyall commutator",
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        zero_norm = ordered & ~nonzero
        zero_norm_diagnostics = _validate_zero_norm_commutator(
            commutator,
            zero_norm,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        right_zero_norm_diagnostics = _validate_zero_norm_commutator(
            right_commutator,
            zero_norm,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        left_zero_norm_diagnostics = _validate_zero_norm_commutator(
            left_commutator,
            zero_norm,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        orbital_gap = _orbital_gap(key, core_energy, virtual_energy).astype(
            dtype, copy=False
        )
        one_sided_gap = orbital_gap.copy()
        hermitianized_gap = orbital_gap.copy()
        if np.any(nonzero):
            retained_norm = selected_norm[nonzero_flat]
            one_sided_gap[nonzero] += (
                si_right_commutator[nonzero] / retained_norm
            )
            hermitianized_gap[nonzero] += (
                selected_commutator / retained_norm
            )
            si_real_gap, one_sided_diagnostics = (
                _audit_one_sided_si_denominator(
                    norm,
                    si_right_commutator,
                    one_sided_gap,
                    nonzero,
                    root=root,
                    subspace=key,
                    gap_atol=si_gap_imag_atol,
                    gap_rtol=si_gap_imag_rtol,
                    numerator_noise_allowance=si_numerator_noise_allowance,
                    energy_imag_l1_tol=si_energy_imag_l1_tol,
                    projection_shift_l1_tol=si_projection_shift_l1_tol,
                    denominator_tol=denominator_tol,
                    enforce=denominator_mode == "strict_si",
                )
            )
            if denominator_mode == "strict_si":
                real_gap = si_real_gap
                selected_gap = one_sided_gap.copy()
            else:
                real_gap = _require_real(
                    hermitianized_gap[nonzero],
                    root=root,
                    subspace=key,
                    quantity="Hermitianized Dyall denominator",
                    atol=scalar_atol,
                    rtol=scalar_rtol,
                )
                selected_gap = hermitianized_gap.copy()
            selected_gap[nonzero] = real_gap
            if np.any(real_gap <= denominator_tol):
                minimum = float(np.min(real_gap))
                raise FloatingPointError(
                    f"root {root} subspace {key}: non-positive or near-zero "
                    f"Dyall denominator {minimum:.3e}"
                )
            contribution = -np.sum(selected_norm[nonzero_flat] / real_gap)
            gap_min = float(np.min(real_gap))
            gap_max = float(np.max(real_gap))
        else:
            contribution = 0.0
            gap_min = np.nan
            gap_max = np.nan
            selected_gap = (
                one_sided_gap
                if denominator_mode == "strict_si"
                else hermitianized_gap
            )
            _si_real_gap, one_sided_diagnostics = (
                _audit_one_sided_si_denominator(
                    norm,
                    si_right_commutator,
                    one_sided_gap,
                    nonzero,
                    root=root,
                    subspace=key,
                    gap_atol=si_gap_imag_atol,
                    gap_rtol=si_gap_imag_rtol,
                    numerator_noise_allowance=si_numerator_noise_allowance,
                    energy_imag_l1_tol=si_energy_imag_l1_tol,
                    projection_shift_l1_tol=si_projection_shift_l1_tol,
                    denominator_tol=denominator_tol,
                    enforce=denominator_mode == "strict_si",
                )
            )

        class_diagnostics = {
            **branch_diagnostics,
            "contraction_backend": contraction_backend,
            "denominator_mode": denominator_mode,
            "selected_denominator_source": (
                "reconciled_right_si"
                if denominator_mode == "strict_si"
                else "hermitian_half_sum"
            ),
            "norm": _scalar_reality_diagnostics(
                norm, ordered, atol=scalar_atol, rtol=scalar_rtol
            ),
            "hermitian_commutator": _scalar_reality_diagnostics(
                commutator, ordered, atol=scalar_atol, rtol=scalar_rtol
            ),
            "one_sided_denominator": one_sided_diagnostics,
            "hermitianized_denominator": _scalar_reality_diagnostics(
                hermitianized_gap,
                nonzero,
                atol=scalar_atol,
                rtol=scalar_rtol,
            ),
            "zero_norm_hermitian_commutator": zero_norm_diagnostics,
            "zero_norm_right_commutator": right_zero_norm_diagnostics,
            "zero_norm_left_commutator": left_zero_norm_diagnostics,
            "minimum_retained_norm": (
                float(np.min(selected_norm[nonzero_flat]))
                if np.any(nonzero_flat)
                else None
            ),
            "ordered_dimension": int(np.count_nonzero(ordered)),
            "retained_dimension": int(np.count_nonzero(nonzero_flat)),
            "discarded_zero_norm_dimension": int(np.count_nonzero(zero_norm)),
        }
        realness_diagnostics[key] = class_diagnostics

        sub_eners[key] = float(contribution)
        sub_norms[key] = float(np.sum(np.maximum(selected_norm, 0.0)))
        sub_gaps[key] = (gap_min, gap_max)
        if return_arrays:
            arrays[key] = {
                "norm": norm,
                "commutator": commutator,
                "right_commutator": right_commutator,
                "left_commutator": left_commutator,
                "si_right_commutator": si_right_commutator,
                "selected_commutator": (
                    si_right_commutator
                    if denominator_mode == "strict_si"
                    else commutator
                ),
                "orbital_gap": _orbital_gap(
                    key, core_energy, virtual_energy
                ),
                "denominator": selected_gap,
                "one_sided_denominator": one_sided_gap,
                "hermitianized_denominator": hermitianized_gap,
                "ordered": ordered,
                "nonzero": nonzero,
            }
        timings[key] = time.perf_counter() - subspace_start

    root_imaginary_energy_l1 = float(
        sum(
            diagnostics["one_sided_denominator"]["imaginary_energy_l1"]
            for diagnostics in realness_diagnostics.values()
        )
    )
    root_projection_shift_l1 = float(
        sum(
            diagnostics["one_sided_denominator"]["real_projection_shift_l1"]
            for diagnostics in realness_diagnostics.values()
        )
    )
    root_energy_gate_passed = bool(
        root_imaginary_energy_l1 <= si_energy_imag_l1_tol
    )
    root_projection_gate_passed = bool(
        root_projection_shift_l1 <= si_projection_shift_l1_tol
    )
    root_strict_si_compatible = bool(
        root_energy_gate_passed
        and root_projection_gate_passed
        and all(
            diagnostics["one_sided_denominator"]["strict_si_compatible"]
            for diagnostics in realness_diagnostics.values()
        )
    )
    root_audit = {
        "strict_si_compatible": root_strict_si_compatible,
        "imaginary_energy_l1": root_imaginary_energy_l1,
        "imaginary_energy_l1_tolerance": float(si_energy_imag_l1_tol),
        "imaginary_energy_l1_gate_passed": root_energy_gate_passed,
        "real_projection_shift_l1": root_projection_shift_l1,
        "real_projection_shift_l1_tolerance": float(
            si_projection_shift_l1_tol
        ),
        "real_projection_shift_l1_gate_passed": root_projection_gate_passed,
    }
    for diagnostics in realness_diagnostics.values():
        diagnostics["root_one_sided_si_audit"] = dict(root_audit)
    if denominator_mode == "strict_si" and not root_strict_si_compatible:
        raise FloatingPointError(
            f"root {root}: aggregate one-sided SI denominator audit failed; "
            f"Im(E) L1={root_imaginary_energy_l1:.3e}, "
            f"projection shift L1={root_projection_shift_l1:.3e}"
        )

    result = (sub_eners, sub_norms, sub_gaps)
    if return_arrays:
        result += (arrays,)
    if return_timings:
        result += (timings,)
    if return_diagnostics:
        result += (realness_diagnostics,)
    return result


def _maximum_abs(array) -> float:
    array = np.asarray(array)
    return float(np.max(np.abs(array), initial=0.0))


def _leading_chunks(shape, dtype, work_memory):
    """Yield leading-index chunks whose dense temporaries fit in memory.

    A transposed RDM is generally non-contiguous, so flattening it may itself
    allocate the full tensor.  Leading-index tuples keep both the original and
    transposed operands as views while bounding every arithmetic temporary.
    """

    shape = tuple(int(size) for size in shape)
    if not shape or 0 in shape:
        yield (...,)
        return
    itemsize = np.dtype(dtype).itemsize
    # Allow two arithmetic temporaries (e.g. conjugate plus difference).
    max_elements = max(1, int(work_memory) // (2 * itemsize))
    trailing = int(np.prod(shape, dtype=np.int64))
    prefix_rank = 0
    while trailing > max_elements and prefix_rank < len(shape):
        trailing //= shape[prefix_rank]
        prefix_rank += 1
    if prefix_rank == 0:
        yield (...,)
        return
    suffix = (slice(None),) * (len(shape) - prefix_rank)
    for prefix in np.ndindex(shape[:prefix_rank]):
        yield prefix + suffix


def _all_finite_chunked(array, work_memory):
    array = np.asarray(array)
    return all(
        bool(np.all(np.isfinite(array[index])))
        for index in _leading_chunks(array.shape, array.dtype, work_memory)
    )


def _maximum_abs_chunked(array, work_memory) -> float:
    array = np.asarray(array)
    maximum = 0.0
    for index in _leading_chunks(array.shape, array.dtype, work_memory):
        maximum = max(maximum, _maximum_abs(array[index]))
    return maximum


def _maximum_abs_relation(
    left,
    right,
    *,
    sign,
    conjugate_right=False,
    work_memory,
) -> float:
    """Return max(abs(left + sign * right)) using bounded temporaries."""

    left = np.asarray(left)
    right = np.asarray(right)
    if left.shape != right.shape:
        raise ValueError("RDM relation operands have different shapes")
    maximum = 0.0
    for index in _leading_chunks(left.shape, left.dtype, work_memory):
        right_chunk = right[index]
        if conjugate_right:
            right_chunk = right_chunk.conj()
        difference = left[index] + sign * right_chunk
        maximum = max(maximum, _maximum_abs(difference))
    return maximum


def validate_pdms(
    pdms,
    ncas,
    nelec,
    *,
    atol=1.0e-9,
    rtol=1.0e-8,
    work_memory=512 * 2**20,
):
    """Validate raw SGF 1--4 particle RDM shapes, order, and contractions.

    ``work_memory`` bounds arithmetic temporaries used by the symmetry checks.
    This matters for a 16-spinor complex 4-RDM, whose dense storage alone is
    64 GiB.  It does not relax or sample any validation condition.
    """

    if not isinstance(pdms, (tuple, list)) or len(pdms) != 4:
        raise ValueError("pdms must be a (dm1, dm2, dm3, dm4) sequence")
    ncas = int(ncas)
    nelec = int(nelec)
    work_memory = int(work_memory)
    if work_memory <= 0:
        raise ValueError("work_memory must be positive")
    checked = []
    diagnostics = {}
    for rank, density in enumerate(pdms, start=1):
        density = np.asarray(density)
        expected_shape = (ncas,) * (2 * rank)
        if density.shape != expected_shape:
            raise ValueError(
                f"dm{rank} must have shape {expected_shape}, got {density.shape}"
            )
        if not np.issubdtype(density.dtype, np.number):
            raise TypeError(f"dm{rank} must be numeric")
        if not _all_finite_chunked(density, work_memory):
            raise ValueError(f"dm{rank} contains non-finite values")

        creator_error = 0.0
        annihilator_error = 0.0
        for axis in range(rank - 1):
            creator_error = max(
                creator_error,
                _maximum_abs_relation(
                    density,
                    density.swapaxes(axis, axis + 1),
                    sign=1.0,
                    work_memory=work_memory,
                ),
            )
            annihilator_axis = rank + axis
            annihilator_error = max(
                annihilator_error,
                _maximum_abs_relation(
                    density,
                    density.swapaxes(
                        annihilator_axis, annihilator_axis + 1
                    ),
                    sign=1.0,
                    work_memory=work_memory,
                ),
            )

        hermitian_axes = tuple(range(2 * rank - 1, rank - 1, -1))
        hermitian_axes += tuple(range(rank - 1, -1, -1))
        hermiticity_error = _maximum_abs_relation(
            density,
            density.transpose(hermitian_axes),
            sign=-1.0,
            conjugate_right=True,
            work_memory=work_memory,
        )
        scale = max(1.0, _maximum_abs_chunked(density, work_memory))
        tolerance = atol + rtol * scale
        if max(creator_error, annihilator_error, hermiticity_error) > tolerance:
            raise ValueError(
                f"dm{rank} violates raw SGF antisymmetry/Hermiticity: "
                f"creator={creator_error:.3e}, annihilator={annihilator_error:.3e}, "
                f"Hermiticity={hermiticity_error:.3e}"
            )
        diagnostics[f"dm{rank}"] = {
            "shape": list(density.shape),
            "creator_antisymmetry_error": creator_error,
            "annihilator_antisymmetry_error": annihilator_error,
            "hermiticity_error": hermiticity_error,
        }
        checked.append(density)

    trace = np.trace(checked[0])
    trace_error = abs(trace - nelec)
    if trace_error > atol + rtol * max(1, nelec):
        raise ValueError(
            f"dm1 trace is inconsistent with {nelec} electrons: "
            f"error={trace_error:.3e}"
        )
    diagnostics["dm1"]["trace_error"] = float(trace_error)
    diagnostics["dm1"]["trace"] = float(trace.real)
    diagnostics["dm1"]["trace_imag"] = float(trace.imag)

    for rank in range(2, 5):
        contracted = np.trace(
            checked[rank - 1], axis1=rank - 1, axis2=rank
        )
        expected = (nelec - rank + 1) * checked[rank - 2]
        error = _maximum_abs_relation(
            contracted,
            expected,
            sign=-1.0,
            work_memory=work_memory,
        )
        scale = max(1.0, _maximum_abs_chunked(expected, work_memory))
        if error > atol + rtol * scale:
            raise ValueError(
                f"dm{rank}->dm{rank - 1} particle-number contraction "
                f"failed: error={error:.3e}"
            )
        diagnostics[f"dm{rank}"]["contraction_error"] = error
    return tuple(checked), diagnostics


def _root_ket(dmrgci, root):
    driver = getattr(dmrgci, "driver", None)
    kets = getattr(dmrgci, "kets", None)
    if driver is None or kets is None:
        raise RuntimeError(
            "the converged pyblock2 driver/MPS must remain open while forming RDMs"
        )
    root = int(root)
    if not 0 <= root < len(kets):
        raise IndexError(
            f"DMRG root {root} is outside the available range [0, {len(kets)})"
        )
    return driver, kets[root]


def _make_rdm(dmrgci, root, rank):
    driver, ket = _root_ket(dmrgci, root)
    method = getattr(driver, f"get_{rank}pdm", None)
    kwargs = {
        "site_type": int(getattr(dmrgci, "npdm_site_type", 0)),
        "cutoff": float(getattr(dmrgci, "npdm_cutoff", 1.0e-24)),
    }
    if callable(method):
        density = method(ket, **kwargs)
    else:  # Compatibility fallback, using the inspected installed signature.
        method = getattr(driver, "get_npdm", None)
        if not callable(method):
            raise RuntimeError(
                f"the installed pyblock2 driver has no {rank}-RDM interface"
            )
        density = method(ket, pdm_type=rank, **kwargs)
    density = np.asarray(density)
    ncas = int(getattr(dmrgci, "ncas"))
    expected_shape = (ncas,) * (2 * rank)
    if density.shape != expected_shape:
        raise ValueError(
            f"Block2 root {root} {rank}-RDM has shape {density.shape}; "
            f"expected raw SGF shape {expected_shape}"
        )
    if not np.iscomplexobj(density):
        density = density.astype(np.complex128)
    return density


def make_rdm1(dmrgci, root=0):
    """Return raw ``<C[p]D[q]>`` for one selected SGF MPS root."""

    return _make_rdm(dmrgci, root, 1)


def make_rdm2(dmrgci, root=0):
    """Return raw ``<C[p]C[q]D[s]D[r]>`` for one selected MPS root."""

    return _make_rdm(dmrgci, root, 2)


def make_rdm3(dmrgci, root=0):
    """Return the explicit raw SGF 3-particle RDM for one MPS root."""

    return _make_rdm(dmrgci, root, 3)


def make_rdm4(dmrgci, root=0):
    """Return the explicit raw SGF 4-particle RDM for one MPS root."""

    return _make_rdm(dmrgci, root, 4)


def make_dm1234(dmrgci, root=0):
    """Obtain explicit, unapproximated raw 1--4 RDMs for one selected root."""

    return tuple(_make_rdm(dmrgci, root, rank) for rank in range(1, 5))


def _rotate_eris(eris, rotation):
    rotation = np.asarray(rotation)
    h1e = rotation.T.conj() @ eris.h1e @ rotation
    h1eff = rotation.T.conj() @ eris.h1eff @ rotation
    eri = np.einsum(
        "ap,bq,cr,ds,abcd->pqrs",
        rotation.conj(),
        rotation,
        rotation.conj(),
        rotation,
        eris.pppp,
        optimize=True,
    )
    return spinor_helper.init_eris(
        h1e,
        eri,
        eris.ncore,
        eris.ncas,
        h1eff=h1eff,
        frozen=0,
        copy=False,
        check=True,
    )


def _project_dense_mo_integrals(h1e, eri):
    """Project AO2MO roundoff back onto the physical spinor symmetries.

    ``s1`` means that the full tensor is stored; it does not remove the
    Coulomb identities ``(pq|rs) = (rs|pq)`` and
    ``(pq|rs) = (qp|sr)*``.  The raw residual is gated before projection so
    an axis/conjugation bug cannot be silently averaged away.  ``eri`` is a
    private writable AO2MO buffer and is consumed as scratch to keep the peak
    at two full tensors.
    """

    h1e = np.asarray(h1e)
    eri = np.asarray(eri)
    if h1e.ndim != 2 or h1e.shape[0] != h1e.shape[1]:
        raise ValueError("h1e must be square before symmetry projection")
    nmo = h1e.shape[0]
    if eri.shape != (nmo,) * 4:
        raise ValueError("eri has the wrong shape before symmetry projection")
    if not np.issubdtype(h1e.dtype, np.inexact):
        raise TypeError("h1e must have a real or complex floating dtype")
    if not np.issubdtype(eri.dtype, np.inexact):
        raise TypeError("eri must have a real or complex floating dtype")
    if not np.all(np.isfinite(h1e)):
        raise ValueError("raw transformed h1e contains non-finite values")
    if not eri.flags.writeable:
        eri = np.array(eri, copy=True)

    h1e_scale = _maximum_abs(h1e)
    h1e_error = _maximum_abs(h1e - h1e.T.conj())
    eri_scale = 0.0
    pair_error = 0.0
    conjugate_error = 0.0
    for p in range(nmo):
        block = eri[p]
        if not np.all(np.isfinite(block)):
            raise ValueError("raw transformed eri contains non-finite values")
        eri_scale = max(eri_scale, _maximum_abs(block))
        pair = eri[:, :, p, :].transpose(2, 0, 1)
        conjugate = eri[:, p, :, :].transpose(0, 2, 1).conj()
        pair_error = max(pair_error, _maximum_abs(block - pair))
        conjugate_error = max(
            conjugate_error, _maximum_abs(block - conjugate)
        )

    # AO2MO consists of several long complex contractions.  A 4096-epsilon
    # gate is deliberately much wider than the observed Cl/dyall-v3z
    # residual while remaining many orders of magnitude below an index or
    # missing-conjugation error.  This gate is only for the raw input; the
    # returned arrays are projected onto the identities exactly below.
    roundoff_factor = 4096.0
    h1e_epsilon = float(np.finfo(np.asarray(h1e.real).dtype).eps)
    eri_epsilon = float(np.finfo(np.asarray(eri.real).dtype).eps)
    h1e_tolerance = (
        roundoff_factor * h1e_epsilon * max(1.0, h1e_scale)
    )
    eri_tolerance = roundoff_factor * eri_epsilon * max(1.0, eri_scale)
    if h1e_error > h1e_tolerance:
        raise ValueError(
            "raw transformed h1e violates Hermiticity beyond roundoff: "
            f"error={h1e_error:.3e}, tolerance={h1e_tolerance:.3e}"
        )
    if max(pair_error, conjugate_error) > eri_tolerance:
        raise ValueError(
            "raw transformed eri violates complex Coulomb symmetry beyond "
            f"roundoff: pair={pair_error:.3e}, "
            f"conjugate={conjugate_error:.3e}, "
            f"tolerance={eri_tolerance:.3e}"
        )

    projected_h1e = np.empty_like(h1e)
    np.add(h1e, h1e.T.conj(), out=projected_h1e)
    projected_h1e *= 0.5

    projected_eri = np.empty_like(eri)
    np.add(eri, eri.transpose(2, 3, 0, 1), out=projected_eri)
    projected_eri *= 0.5
    np.conjugate(projected_eri.transpose(1, 0, 3, 2), out=eri)
    projected_eri += eri
    projected_eri *= 0.5

    post_h1e_error = _maximum_abs(projected_h1e - projected_h1e.T.conj())
    post_pair_error = 0.0
    post_conjugate_error = 0.0
    for p in range(nmo):
        block = projected_eri[p]
        pair = projected_eri[:, :, p, :].transpose(2, 0, 1)
        conjugate = (
            projected_eri[:, p, :, :].transpose(0, 2, 1).conj()
        )
        post_pair_error = max(
            post_pair_error, _maximum_abs(block - pair)
        )
        post_conjugate_error = max(
            post_conjugate_error, _maximum_abs(block - conjugate)
        )

    diagnostics = {
        "h1e": {
            "raw_hermiticity_error": h1e_error,
            "maximum_absolute_value": h1e_scale,
            "roundoff_gate": h1e_tolerance,
            "projection_change_upper_bound": 0.5 * h1e_error
            + 2.0 * h1e_epsilon * max(1.0, h1e_scale),
            "post_projection_hermiticity_error": post_h1e_error,
        },
        "eri": {
            "raw_pair_exchange_error": pair_error,
            "raw_conjugate_exchange_error": conjugate_error,
            "maximum_absolute_value": eri_scale,
            "roundoff_gate": eri_tolerance,
            "projection_change_upper_bound": 0.5
            * (pair_error + conjugate_error)
            + 4.0 * eri_epsilon * max(1.0, eri_scale),
            "post_projection_pair_exchange_error": post_pair_error,
            "post_projection_conjugate_exchange_error": post_conjugate_error,
        },
    }
    return projected_h1e, projected_eri, diagnostics


def _dense_eris_from_mc(mc, mo_coeff):
    from pyscf.ao2mo import nrr_outcore

    mo_coeff = np.asarray(mo_coeff)
    hcore = np.asarray(mc.get_hcore())
    h1e = mo_coeff.T.conj() @ hcore @ mo_coeff
    dense = nrr_outcore.full_iofree(
        mc.mol,
        mo_coeff,
        motype="j-spinor",
        verbose=getattr(mc, "verbose", logger.NOTE),
    )
    nmo = mo_coeff.shape[1]
    raw_eri = np.asarray(dense).reshape((nmo,) * 4)
    del dense
    h1e, eri, symmetry_diagnostics = _project_dense_mo_integrals(h1e, raw_eri)
    del raw_eri
    result = spinor_helper.init_eris(
        h1e,
        eri,
        int(mc.ncore),
        int(mc.ncas),
        frozen=0,
        copy=False,
        check=True,
    )
    result.symmetry_diagnostics = symmetry_diagnostics
    return result


def _reference_energy(mc, root):
    if hasattr(mc, "e_states") and getattr(mc, "e_states") is not None:
        energies = np.asarray(mc.e_states)
        if energies.ndim:
            return float(energies[root])
    energies = np.asarray(mc.e_tot)
    if energies.ndim:
        return float(energies[root])
    if int(getattr(getattr(mc, "fcisolver", None), "nroots", 1)) > 1:
        solver_energies = np.asarray(getattr(mc.fcisolver, "e_tot", []))
        if solver_energies.ndim and len(solver_energies) > root:
            # DMRGCI.e_tot already includes the active-space core constant
            # used by its most recent CASSCF Hamiltonian.
            return float(solver_energies[root])
        raise RuntimeError("state-specific CASSCF reference energies are unavailable")
    return float(energies)


class WickX2CSCNEVPT2(lib.StreamObject):
    """State-specific dense spinor SC-NEVPT2 generated with Block2 Wick."""

    def __init__(self, mc, frozen=0):
        if _has_frozen_orbitals(frozen) or _has_frozen_orbitals(
            getattr(mc, "frozen", None)
        ):
            raise NotImplementedError("nonzero frozen spinors are outside dense v1")
        self._mc = mc
        self._scf = mc._scf
        self.mol = self._scf.mol
        self.verbose = getattr(mc, "verbose", self.mol.verbose)
        self.stdout = getattr(mc, "stdout", self.mol.stdout)
        self.root = 0
        self.mo_coeff = getattr(mc, "mo_coeff", None)
        self.mo_energy = getattr(mc, "mo_energy", None)
        self.canonicalized = False
        self.eris = None
        self.eris_basis = None
        self.e_corr = None
        self.reference_energy = None
        self.sub_eners = {}
        self.sub_norms = {}
        self.sub_denominators = {}
        self.sub_realness_diagnostics = {}
        self.sub_times = {}
        self.rdm_diagnostics = None
        self.integral_symmetry_diagnostics = None
        self.scalar_atol = 1.0e-10
        self.scalar_rtol = 1.0e-9
        self.rdm_atol = 1.0e-9
        self.rdm_rtol = 1.0e-8
        self.rdm_work_memory = 512 * 2**20
        self.norm_tol = 1.0e-14
        self.denominator_tol = 1.0e-12
        self.denominator_mode = "strict_si"
        self.contraction_backend = _DEFAULT_CONTRACTION_BACKEND
        self.si_gap_imag_atol = 1.0e-10
        self.si_gap_imag_rtol = 1.0e-9
        self.si_numerator_noise_allowance = 1.0e-12
        self.si_energy_imag_l1_tol = 1.0e-10
        self.si_projection_shift_l1_tol = 1.0e-12
        self.strict_si_compatible = None
        self.scalar_tolerance = None
        self.reference_residual_bound = None
        self.frozen = 0
        self._keys = set(self.__dict__)

    @property
    def e_tot(self):
        if self.e_corr is None:
            return None
        return np.asarray(self.reference_energy) + np.asarray(self.e_corr)

    def _semicanonicalize(self, mc, mo_coeff, dm1, root):
        if self.canonicalized:
            if self.mo_energy is None:
                self.mo_energy = getattr(mc, "mo_energy", None)
            if self.mo_energy is None:
                raise ValueError(
                    "canonicalized=True requires prepared spinor orbital energies"
                )
            energies = np.asarray(self.mo_energy)
            if energies.shape != (mo_coeff.shape[1],):
                raise ValueError("mo_energy has the wrong shape")
            if np.iscomplexobj(energies) and _maximum_abs(energies.imag) > 1e-12:
                raise ValueError("semicanonical orbital energies must be real")
            return np.asarray(mo_coeff), np.asarray(energies.real, dtype=float)

        ci = _select_root_ci(
            getattr(mc, "ci", None),
            root,
            nroots=getattr(getattr(mc, "fcisolver", None), "nroots", 1),
        )
        rotated, _ci, energies = mc.canonicalize(
            mo_coeff,
            ci=ci,
            cas_natorb=False,
            casdm1=dm1,
            verbose=self.verbose,
        )
        rotated = np.asarray(rotated)
        ncore = int(mc.ncore)
        nocc = ncore + int(mc.ncas)
        active_change = _maximum_abs(
            rotated[:, ncore:nocc] - np.asarray(mo_coeff)[:, ncore:nocc]
        )
        if active_change > 1.0e-12:
            raise RuntimeError(
                "root-specific semicanonicalization changed active orbitals "
                f"by {active_change:.3e}; the MPS/RDM basis would be invalid"
            )
        return rotated, np.asarray(energies, dtype=float)

    def kernel(
        self,
        mc=None,
        mo_coeff=None,
        pdms=None,
        eris=None,
        eris_basis="input_mo",
        denominator_mode=None,
        root=None,
        contraction_backend=None,
    ):
        """Compute one root-specific SC-NEVPT2 correction.

        ``contraction_backend`` selects ``"pytblis"`` (the default) or the
        NumPy reference implementation for the Block2-generated contractions.
        """

        if mc is None:
            mc = self._mc
        if _has_frozen_orbitals(getattr(mc, "frozen", None)):
            raise NotImplementedError("nonzero frozen spinors are outside dense v1")
        eris_basis = _normalize_eris_basis(eris_basis)
        if denominator_mode is None:
            denominator_mode = self.denominator_mode
        denominator_mode = _normalize_denominator_mode(denominator_mode)
        self.denominator_mode = denominator_mode
        if contraction_backend is None:
            contraction_backend = self.contraction_backend
        contraction_backend = _normalize_contraction_backend(
            contraction_backend
        )
        self.contraction_backend = contraction_backend
        if root is None:
            root = self.root
        root = int(root)
        if root < 0:
            raise IndexError("root must be non-negative")
        self.root = root
        if mo_coeff is None:
            mo_coeff = mc.mo_coeff
        mo_coeff = np.asarray(mo_coeff)
        self.reference_energy = _reference_energy(mc, root)

        solver = mc.fcisolver
        residual_bound = getattr(solver, "convergence_info", {}).get(
            "local_residual_bound", 0.0
        )
        residual_bound = float(residual_bound)
        if not np.isfinite(residual_bound) or residual_bound < 0.0:
            residual_bound = 0.0
        self.reference_residual_bound = residual_bound
        # The requested local eigensolver threshold is useful provenance, but
        # is not a measured contraction-error bound and therefore does not
        # relax either the strict-SI or Hermitianized scalar checks.
        self.scalar_tolerance = float(self.scalar_atol)

        pdm_start = time.perf_counter()
        if pdms is None:
            pdms = make_dm1234(mc.fcisolver, root=root)
        solver_nelecas = getattr(mc.fcisolver, "nelecas", None)
        if solver_nelecas is None:
            solver_nelecas = mc.nelecas
        pdms, self.rdm_diagnostics = validate_pdms(
            pdms,
            int(mc.ncas),
            _total_nelec(solver_nelecas),
            atol=self.rdm_atol,
            rtol=self.rdm_rtol,
            work_memory=self.rdm_work_memory,
        )
        pdm_time = time.perf_counter() - pdm_start

        integral_start = time.perf_counter()
        original_mo = mo_coeff
        semicanonical_mo, orbital_energy = self._semicanonicalize(
            mc, original_mo, pdms[0], root
        )
        if eris is None:
            eris = _dense_eris_from_mc(mc, semicanonical_mo)
            effective_eris_basis = "semicanonical"
        else:
            if not isinstance(eris, spinor_helper._SpinorERIs):
                raise TypeError("eris must be a spinor_helper._SpinorERIs instance")
            if (eris.ncore, eris.ncas, eris.nmo) != (
                int(mc.ncore),
                int(mc.ncas),
                semicanonical_mo.shape[1],
            ):
                raise ValueError("eris partition does not match the CASSCF object")
            if (
                eris_basis == "input_mo"
                and not np.array_equal(semicanonical_mo, original_mo)
            ):
                overlap = np.asarray(mc._scf.get_ovlp())
                rotation = original_mo.T.conj() @ overlap @ semicanonical_mo
                eris = _rotate_eris(eris, rotation)
            effective_eris_basis = "semicanonical"
        integral_time = time.perf_counter() - integral_start

        self.mo_coeff = semicanonical_mo
        self.mo_energy = orbital_energy
        self.eris = eris
        self.eris_basis = effective_eris_basis
        self.integral_symmetry_diagnostics = getattr(
            eris, "symmetry_diagnostics", None
        )
        ncore = eris.ncore
        nocc = eris.nocc
        core_energy = orbital_energy[:ncore]
        virtual_energy = orbital_energy[nocc:]

        self.sub_times = {"pdms": pdm_time, "eris": integral_time}
        self.sub_eners = {}
        self.sub_norms = {}
        self.sub_denominators = {}
        self.sub_realness_diagnostics = {}
        (
            sub_eners,
            sub_norms,
            sub_gaps,
            subspace_times,
            realness_diagnostics,
        ) = _evaluate_wick_subspaces(
            eris,
            pdms,
            core_energy,
            virtual_energy,
            root=root,
            scalar_atol=self.scalar_tolerance,
            scalar_rtol=self.scalar_rtol,
            norm_tol=self.norm_tol,
            denominator_tol=self.denominator_tol,
            denominator_mode=denominator_mode,
            si_gap_imag_atol=self.si_gap_imag_atol,
            si_gap_imag_rtol=self.si_gap_imag_rtol,
            si_numerator_noise_allowance=self.si_numerator_noise_allowance,
            si_energy_imag_l1_tol=self.si_energy_imag_l1_tol,
            si_projection_shift_l1_tol=self.si_projection_shift_l1_tol,
            contraction_backend=contraction_backend,
            return_timings=True,
            return_diagnostics=True,
        )
        self.strict_si_compatible = all(
            diagnostics["root_one_sided_si_audit"]["strict_si_compatible"]
            for diagnostics in realness_diagnostics.values()
        )
        if denominator_mode == "hermitianized" and not self.strict_si_compatible:
            failed = ", ".join(
                key
                for key, diagnostics in realness_diagnostics.items()
                if not diagnostics["one_sided_denominator"][
                    "strict_si_compatible"
                ]
            )
            if not failed:
                failed = "<aggregate L1 gate>"
            logger.warn(
                self,
                "root %d uses denominator_mode=hermitianized; the one-sided "
                "SI audit failed for classes: %s",
                root,
                failed,
            )
        for key in SUBSPACE_ORDER:
            self.sub_eners[key] = sub_eners[key]
            self.sub_norms[key] = sub_norms[key]
            self.sub_denominators[key] = sub_gaps[key]
            self.sub_realness_diagnostics[key] = realness_diagnostics[key]
            self.sub_times[key] = subspace_times[key]
            logger.note(
                self,
                "root %d E(%s-%4s) = %20.14f  norm = %.10g  gap = [%s, %s]",
                root,
                self.__class__.__name__,
                key,
                sub_eners[key],
                sub_norms[key],
                "nan" if np.isnan(sub_gaps[key][0]) else f"{sub_gaps[key][0]:.8g}",
                "nan" if np.isnan(sub_gaps[key][1]) else f"{sub_gaps[key][1]:.8g}",
            )
        self.e_corr = float(sum(self.sub_eners.values()))
        logger.note(
            self,
            "root %d E(reference) = %.16g  E_corr = %.16g  E(total) = %.16g",
            root,
            self.reference_energy,
            self.e_corr,
            self.e_tot,
        )
        logger.info(
            self,
            "root %d contraction_backend=%s denominator_mode=%s "
            "strict_si_compatible=%s; "
            "physical-scalar realness tolerance = %.3e "
            "(configured %.3e; DMRG local threshold bound %.3e is diagnostic only)",
            root,
            contraction_backend,
            denominator_mode,
            self.strict_si_compatible,
            self.scalar_tolerance,
            self.scalar_atol,
            residual_bound,
        )
        logger.note(
            self,
            "root %d timings: %s",
            root,
            " | ".join(f"{key}={value:.2f}s" for key, value in self.sub_times.items()),
        )
        return self.e_corr


X2CSCNEVPT2 = WickX2CSCNEVPT2
