#!/usr/bin/env python
# SPDX-License-Identifier: GPL-3.0-or-later
r"""Dense no-Kramers X2C strongly-contracted NEVPT2.

The spin-orbital Hamiltonian used by this module is

.. math::

   H = \sum_{pq} h_{pq} C_p D_q
       + \frac12 \sum_{pqrs} w_{pqrs} C_p C_q D_s D_r,

with unantisymmetrized integrals

.. math::

   w_{pqrs} = \mathrm{eri}_{prqs}, \qquad
   \mathrm{eri}_{pqrs} = (pq|rs).

All indices label individual complex spinors.  There is no implicit spin
summation, Kramers compression, ``E1/E2`` spin-free operator, or spatial
``gamma`` factor.  An explicit ``strong_contraction_groups`` label vector can
nevertheless request that symmetry-partner core/external channels be summed
before their strongly-contracted denominator is formed.  This recovers, for
example, the spin-free scalar limit without guessing partners from accidental
orbital-energy degeneracies.  The eight strongly-contracted spaces follow
Sections I.E--I.L of the Supporting Information to Shiozaki and Mizukami,
JCTC 2015:

``ijrs`` (E, Eqs. 13--14), ``ijr`` (F, Eqs. 15--17), ``ij`` (G,
Eqs. 18--20), ``rsi`` (H, Eqs. 21--23), ``ir`` (I, Eqs. 24--27), ``i``
(J, Eqs. 28--30), ``rs`` (K, Eqs. 31--33), and ``r`` (L, Eqs. 34--36).

The actual norm and Dyall-commutator contractions are generated by the
installed Block2 Wick bindings.  Active expectation values are lowered to
raw SGF particle RDMs with axes

``dm_k[p1,...,pk,qk,...,q1] = <C[p1]...C[pk]D[qk]...D[q1]>``.

The default ``strict_si`` denominator is the one-sided expression printed in
the SI.  Finite imaginary residuals and related tolerance failures emit
``MRPTNumericalWarning`` before the selected value is converted to real
arithmetic.  Non-finite values and non-positive or near-zero denominators
remain hard errors.  The independently generated left branch is always
checked against the adjoint of the right branch.  An explicit
``hermitianized`` mode retains the manifestly Hermitian half-sum as a
finite-MPS stabilization, but records whether the one-sided SI gate failed;
it is therefore never silently presented as the literal SI expression.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import time
from typing import Any

import numpy as np
from pyscf import lib
from pyscf.lib import logger

from . import nevpt2_utils as _utils
from . import spinor_helper


__all__ = [
    "MRPTNumericalWarning",
    "SUBSPACE_ORDER",
    "WickX2CSCNEVPT2",
    "X2CSCNEVPT2",
    "dump_wick_equations",
    "make_dm1234",
    "make_rdm1",
    "make_rdm2",
    "make_rdm3",
    "make_rdm4",
    "validate_pdms",
]


# Shared infrastructure lives in nevpt2_utils.  These aliases preserve the
# established x2cscnevpt2 import surface while keeping one implementation.
SUBSPACE_ORDER = _utils.SUBSPACE_ORDER
MRPTNumericalWarning = _utils.MRPTNumericalWarning
_ERIS_BASES = _utils._ERIS_BASES
_DENOMINATOR_MODES = _utils._DENOMINATOR_MODES
_CONTRACTION_BACKENDS = _utils._CONTRACTION_BACKENDS
_DEFAULT_CONTRACTION_BACKEND = _utils._DEFAULT_CONTRACTION_BACKEND
_warn_numerical = _utils._warn_numerical
_select_root_ci = _utils._select_root_ci
_total_nelec = _utils._total_nelec
_has_frozen_orbitals = _utils._has_frozen_orbitals
_normalize_eris_basis = _utils._normalize_eris_basis
_normalize_denominator_mode = _utils._normalize_denominator_mode
_normalize_contraction_backend = _utils._normalize_contraction_backend
_validate_tblis_operand_dtypes = _utils._validate_tblis_operand_dtypes
_wick_einsum_namespace = _utils._wick_einsum_namespace
_PERTURBER_EXPRESSIONS = _utils._PERTURBER_EXPRESSIONS

_PAIR_RESTRICTIONS = _utils._PAIR_RESTRICTIONS

_H1_KEYS = _utils._H1_KEYS
_W_KEYS = _utils._W_KEYS
_WickERIBlocks = _utils._WickERIBlocks
_compact_wick_eris = _utils._compact_wick_eris
_rotate_wick_eris = _utils._rotate_wick_eris


@dataclass(frozen=True)
class _WickEquationBundle:
    norm_code: dict[str, str]
    transition_norm_code: dict[str, str]
    right_commutator_code: dict[str, str]
    left_commutator_code: dict[str, str]
    commutator_code: dict[str, str]
    norm_text: dict[str, str]
    transition_norm_text: dict[str, str]
    right_commutator_text: dict[str, str]
    left_commutator_text: dict[str, str]
    commutator_text: dict[str, str]


_block2_wick_types = _utils._block2_wick_types
_wick_parsers = _utils._wick_parsers
_conjugate_with_coefficients = _utils._conjugate_with_coefficients
_vacuum_reduce = _utils._vacuum_reduce
_lower_active_operators = _utils._lower_active_operators


@lru_cache(maxsize=1)
def _compile_wick_equations() -> _WickEquationBundle:
    types = _block2_wick_types()
    parse, parse_tensor = _wick_parsers(types)

    h_dyall_active = parse("SUM <ab> h[ab] C[a] D[b]")
    h_dyall_active += parse(
        "0.5 SUM <abcd> w[abcd] C[a] C[b] D[d] D[c]"
    )

    norm_code = {}
    transition_norm_code = {}
    right_commutator_code = {}
    left_commutator_code = {}
    commutator_code = {}
    norm_text = {}
    transition_norm_text = {}
    right_commutator_text = {}
    left_commutator_text = {}
    commutator_text = {}
    for key in SUBSPACE_ORDER:
        ket = parse(_PERTURBER_EXPRESSIONS[key])
        bra = _conjugate_with_coefficients(ket, types)

        reduced_norm = _vacuum_reduce(bra * ket)
        norm = _lower_active_operators(reduced_norm, types)
        transition_norm = _lower_active_operators(
            reduced_norm, types, include_overlap=True
        )

        # [one-/two-body H_D, at-most-two-body T] is connected and contains
        # at most three creation and three destruction operators.  Asking
        # Wick for max_unctr=6 discards only the zero-contraction H2*T2
        # products, which cancel identically in the commutator.  This ordering
        # is important when w has intentionally been given no permutation
        # rules: otherwise Block2 cannot graph-canonicalize two dummy-index
        # forms of that exact zero before the bra is multiplied, producing a
        # spurious 5-RDM in the r/i classes.
        connected_right = (h_dyall_active ^ ket).expand(6).simplify()
        right_commutator = _lower_active_operators(
            _vacuum_reduce(bra * connected_right), types
        )
        connected_left = (bra ^ h_dyall_active).expand(6).simplify()
        left_commutator = _lower_active_operators(
            _vacuum_reduce(connected_left * ket), types
        )

        # The SI one-sided commutator is real when the CAS reference is an
        # exact eigenstate of the active Dyall Hamiltonian.  A converged DMRG
        # MPS has a finite eigen-equation residual, however, so that
        # one-sided form need not itself be Hermitian.  Form its Hermitian
        # part explicitly at the operator/Wick level:
        #
        #   1/2 { T^dagger [H_D,T] + [T^dagger,H_D] T }.
        #
        # This is exactly the SI expression in the eigenstate limit, remains
        # connected and requires no RDM above rank four.  The independently
        # generated left and right branches are retained so execution can
        # verify their adjoint relation; this is deliberately not a final
        # ``.real`` projection of the one-sided numerical result.
        commutator = (0.5 * (right_commutator + left_commutator)).simplify()

        norm_target = parse_tensor(f"norm[{key}]")
        commutator_target = parse_tensor(f"commutator[{key}]")
        norm_code[key] = norm.to_einsum(norm_target)
        transition_norm_code[key] = transition_norm.to_einsum(norm_target)
        right_commutator_code[key] = right_commutator.to_einsum(
            commutator_target
        )
        left_commutator_code[key] = left_commutator.to_einsum(
            commutator_target
        )
        commutator_code[key] = commutator.to_einsum(commutator_target)
        norm_text[key] = repr(norm)
        transition_norm_text[key] = repr(transition_norm)
        right_commutator_text[key] = repr(right_commutator)
        left_commutator_text[key] = repr(left_commutator)
        commutator_text[key] = repr(commutator)

    return _WickEquationBundle(
        norm_code=norm_code,
        transition_norm_code=transition_norm_code,
        right_commutator_code=right_commutator_code,
        left_commutator_code=left_commutator_code,
        commutator_code=commutator_code,
        norm_text=norm_text,
        transition_norm_text=transition_norm_text,
        right_commutator_text=right_commutator_text,
        left_commutator_text=left_commutator_text,
        commutator_text=commutator_text,
    )


def dump_wick_equations(filename: str | None = None) -> str:
    """Return (and optionally write) auditable equations for all eight spaces."""

    equations = _compile_wick_equations()
    sections = []
    for key in SUBSPACE_ORDER:
        sections.extend(
            (
                f"[{key}] perturber\n{_PERTURBER_EXPRESSIONS[key]}",
                f"[{key}] norm expression\n{equations.norm_text[key]}",
                f"[{key}] norm einsum\n{equations.norm_code[key]}",
                f"[{key}] transition norm expression\n"
                f"{equations.transition_norm_text[key]}",
                f"[{key}] transition norm einsum\n"
                f"{equations.transition_norm_code[key]}",
                f"[{key}] right Dyall commutator expression\n"
                f"{equations.right_commutator_text[key]}",
                f"[{key}] right Dyall commutator einsum\n"
                f"{equations.right_commutator_code[key]}",
                f"[{key}] left Dyall commutator expression\n"
                f"{equations.left_commutator_text[key]}",
                f"[{key}] left Dyall commutator einsum\n"
                f"{equations.left_commutator_code[key]}",
                f"[{key}] Hermitian Dyall commutator expression\n"
                f"{equations.commutator_text[key]}",
                f"[{key}] Hermitian Dyall commutator einsum\n"
                f"{equations.commutator_code[key]}",
            )
        )
    text = "\n\n".join(sections) + "\n"
    if filename is not None:
        with open(filename, "w", encoding="utf-8") as handle:
            handle.write(text)
    return text


_free_index_shape = _utils._free_index_shape


def _orbital_gap(key: str, core_energy, virtual_energy):
    shape = tuple(
        len(core_energy) if char in "ij" else len(virtual_energy)
        for char in key
    )
    gap = np.zeros(shape, dtype=float)
    for axis, char in enumerate(key):
        values = -np.asarray(core_energy) if char in "ij" else np.asarray(
            virtual_energy
        )
        reshape = [1] * len(key)
        reshape[axis] = len(values)
        gap += values.reshape(reshape)
    return gap


_strict_pair_mask = _utils._strict_pair_mask


def _normalize_strong_contraction_groups(
    groups,
    eris,
    core_energy,
    virtual_energy,
    *,
    atol,
    rtol,
):
    """Validate and normalize explicit core/external contraction labels.

    Labels are indexed by the full semicanonical spinor-MO order.  Their
    numerical values have no meaning: equal labels within a core or virtual
    partition identify channels that belong to one strongly-contracted
    orbital.  Active labels are retained only so the public input has one
    unambiguous full-MO shape.
    """

    for name, value in (("atol", atol), ("rtol", rtol)):
        if not np.isfinite(value) or value < 0.0:
            raise ValueError(
                f"strong-contraction group {name} must be finite and "
                "non-negative"
            )
    labels = np.asarray(groups)
    if labels.shape != (eris.nmo,):
        raise ValueError(
            "strong_contraction_groups must have shape "
            f"({eris.nmo},), got {labels.shape}"
        )
    if labels.dtype.kind not in "iufc":
        raise TypeError("strong_contraction_groups must contain integer labels")
    if labels.dtype.kind in "iu":
        integral_labels = labels
    else:
        if labels.dtype.kind == "c" and np.any(labels.imag != 0.0):
            raise ValueError("strong_contraction_groups contains complex labels")
        numeric = np.asarray(labels.real, dtype=float)
        if not np.all(np.isfinite(numeric)):
            raise ValueError(
                "strong_contraction_groups contains non-finite labels"
            )
        integral_labels = np.rint(numeric)
        if np.any(numeric != integral_labels):
            raise ValueError(
                "strong_contraction_groups must contain integer labels"
            )

    ncore = int(eris.ncore)
    nocc = int(eris.nocc)
    if np.asarray(core_energy).shape != (ncore,):
        raise ValueError("core_energy has the wrong shape")
    if np.asarray(virtual_energy).shape != (eris.nmo - nocc,):
        raise ValueError("virtual_energy has the wrong shape")
    normalized = np.empty(eris.nmo, dtype=np.int64)
    partitions = ((0, ncore), (ncore, nocc), (nocc, eris.nmo))
    for start, stop in partitions:
        if start == stop:
            continue
        _unique, inverse = np.unique(
            integral_labels[start:stop],
            return_inverse=True,
        )
        normalized[start:stop] = inverse

    def validate_partition(partition_labels, energies, name):
        energies = np.asarray(energies, dtype=float)
        for group in np.unique(partition_labels):
            selected = energies[partition_labels == group]
            spread = float(np.ptp(selected)) if selected.size else 0.0
            scale = max(1.0, float(np.max(np.abs(selected), initial=0.0)))
            tolerance = float(atol + rtol * scale)
            if spread > tolerance:
                raise ValueError(
                    f"strong-contraction {name} group {int(group)} spans "
                    f"nondegenerate semicanonical energies: spread={spread:.3e}, "
                    f"tolerance={tolerance:.3e}"
                )

    validate_partition(normalized[:ncore], core_energy, "core")
    validate_partition(normalized[nocc:], virtual_energy, "virtual")
    return normalized


def _group_strong_contraction_arrays(
    key,
    arrays,
    orbital_gap,
    ordered,
    groups,
    eris,
    *,
    atol,
    rtol,
):
    """Sum symmetry-partner channels before forming an SC denominator."""

    ordered = np.asarray(ordered, dtype=bool)
    arrays = tuple(np.asarray(array) for array in arrays)
    orbital_gap = np.asarray(orbital_gap, dtype=float)
    if any(array.shape != ordered.shape for array in arrays):
        raise ValueError("strong-contraction arrays and mask have different shapes")
    if orbital_gap.shape != ordered.shape:
        raise ValueError("strong-contraction orbital gap has the wrong shape")

    selected_coordinates = np.column_stack(np.nonzero(ordered))
    raw_dimension = int(selected_coordinates.shape[0])
    if raw_dimension == 0:
        empty_arrays = tuple(
            np.zeros(0, dtype=array.dtype) for array in arrays
        )
        diagnostics = {
            "enabled": True,
            "raw_ordered_dimension": 0,
            "contracted_group_dimension": 0,
            "maximum_orbital_gap_spread": 0.0,
            "orbital_gap_tolerance_at_maximum": float(atol + rtol),
        }
        return empty_arrays, np.zeros(0, dtype=float), diagnostics

    nocc = int(eris.nocc)
    group_columns = []
    for axis, char in enumerate(key):
        if char in "ij":
            partition_groups = groups[: eris.ncore]
        else:
            partition_groups = groups[nocc:]
        group_columns.append(
            partition_groups[selected_coordinates[:, axis]]
        )
    group_keys = np.column_stack(group_columns)
    # A restricted raw pair is ordered by spinor index.  For non-contiguous
    # or otherwise arbitrarily labelled partner groups, canonicalize the
    # corresponding group pair as well so its members cannot split across two
    # denominators merely because of their column order.
    for left, right in _PAIR_RESTRICTIONS[key]:
        low = np.minimum(group_keys[:, left], group_keys[:, right])
        high = np.maximum(group_keys[:, left], group_keys[:, right])
        group_keys[:, left] = low
        group_keys[:, right] = high

    _unique_keys, inverse = np.unique(
        group_keys, axis=0, return_inverse=True
    )
    group_count = int(np.max(inverse)) + 1
    grouped_arrays = []
    for array in arrays:
        grouped = np.zeros(group_count, dtype=array.dtype)
        np.add.at(grouped, inverse, array[ordered])
        grouped_arrays.append(grouped)

    selected_gap = orbital_gap[ordered]
    gap_min = np.full(group_count, np.inf, dtype=float)
    gap_max = np.full(group_count, -np.inf, dtype=float)
    gap_sum = np.zeros(group_count, dtype=float)
    group_size = np.zeros(group_count, dtype=np.int64)
    np.minimum.at(gap_min, inverse, selected_gap)
    np.maximum.at(gap_max, inverse, selected_gap)
    np.add.at(gap_sum, inverse, selected_gap)
    np.add.at(group_size, inverse, 1)
    spreads = gap_max - gap_min
    scales = np.maximum(1.0, np.maximum(np.abs(gap_min), np.abs(gap_max)))
    limits = atol + rtol * scales
    maximum_index = int(np.argmax(spreads))
    if np.any(spreads > limits):
        failed = int(np.argmax(spreads - limits))
        raise ValueError(
            f"subspace {key}: one strong-contraction group spans unequal "
            f"orbital gaps: spread={spreads[failed]:.3e}, "
            f"tolerance={limits[failed]:.3e}"
        )
    grouped_gap = gap_sum / group_size
    diagnostics = {
        "enabled": True,
        "raw_ordered_dimension": raw_dimension,
        "contracted_group_dimension": group_count,
        "maximum_orbital_gap_spread": float(spreads[maximum_index]),
        "orbital_gap_tolerance_at_maximum": float(limits[maximum_index]),
    }
    return tuple(grouped_arrays), grouped_gap, diagnostics


_require_real = _utils._require_real


def _require_adjoint_pair(
    left,
    right,
    mask,
    *,
    root,
    subspace,
    atol,
    rtol,
):
    """Verify independently generated scalar branches are adjoints."""

    left = np.asarray(left)
    right = np.asarray(right)
    mask = np.asarray(mask, dtype=bool)
    if left.shape != right.shape or left.shape != mask.shape:
        raise ValueError("adjoint-branch arrays or mask have different shapes")
    selected_left = left[mask]
    selected_right = right[mask]
    if not np.all(np.isfinite(selected_left)) or not np.all(
        np.isfinite(selected_right)
    ):
        raise FloatingPointError(
            f"root {root} subspace {subspace}: Dyall commutator branch "
            "contains non-finite values"
        )
    if not selected_left.size:
        return {
            "maximum_adjoint_error": 0.0,
            "maximum_adjoint_error_index": [],
            "reality_limit_at_maximum_error": float(atol + rtol),
            "adjoint_gate_passed": True,
        }

    error = np.abs(selected_left - selected_right.conj())
    limit = atol + rtol * np.maximum(
        1.0, np.maximum(np.abs(selected_left), np.abs(selected_right))
    )
    local_index = int(np.argmax(error))
    selected_flat = np.flatnonzero(mask)
    full_index = np.unravel_index(
        int(selected_flat[local_index]), left.shape
    )
    gate_passed = bool(error[local_index] <= limit[local_index])
    if not gate_passed:
        _warn_numerical(
            f"root {root} subspace {subspace}: independently generated "
            "Dyall commutator branches are not adjoints; maximum error = "
            f"{float(error[local_index]):.3e} at {full_index}"
        )
    return {
        "maximum_adjoint_error": float(error[local_index]),
        "maximum_adjoint_error_index": [int(index) for index in full_index],
        "reality_limit_at_maximum_error": float(limit[local_index]),
        "adjoint_gate_passed": gate_passed,
    }


def _scalar_reality_diagnostics(values, mask, *, atol, rtol):
    """Return the largest imaginary residual of a selected scalar array."""

    values = np.asarray(values)
    mask = np.asarray(mask, dtype=bool)
    selected = values[mask]
    if not selected.size:
        return {
            "maximum_imaginary_part": 0.0,
            "maximum_imaginary_index": [],
            "reality_limit_at_maximum": float(atol + rtol),
            "real_part_at_maximum": 0.0,
            "maximum_imaginary_to_limit_ratio": 0.0,
            "maximum_ratio_index": [],
            "gate_passed": True,
        }
    magnitude = np.abs(selected.imag)
    limits = atol + rtol * np.maximum(1.0, np.abs(selected.real))
    local_index = int(np.argmax(magnitude))
    selected_flat = np.flatnonzero(mask)
    full_index = np.unravel_index(
        int(selected_flat[local_index]), values.shape
    )
    ratio = np.divide(
        magnitude,
        limits,
        out=np.full_like(magnitude, np.inf, dtype=float),
        where=limits > 0.0,
    )
    ratio_index = int(np.argmax(ratio))
    ratio_full_index = np.unravel_index(
        int(selected_flat[ratio_index]), values.shape
    )
    return {
        "maximum_imaginary_part": float(magnitude[local_index]),
        "maximum_imaginary_index": [int(index) for index in full_index],
        "reality_limit_at_maximum": float(limits[local_index]),
        "real_part_at_maximum": float(selected[local_index].real),
        "maximum_imaginary_to_limit_ratio": float(ratio[ratio_index]),
        "maximum_ratio_index": [int(index) for index in ratio_full_index],
        "gate_passed": bool(np.all(magnitude <= limits)),
    }


def _audit_one_sided_si_denominator(
    norm,
    right_commutator,
    one_sided_gap,
    mask,
    *,
    root,
    subspace,
    gap_atol,
    gap_rtol,
    numerator_noise_allowance,
    energy_imag_l1_tol,
    projection_shift_l1_tol,
    denominator_tol,
    enforce,
):
    """Audit the literal SI denominator with a bounded near-null exception.

    Dividing a roundoff-sized imaginary numerator by a nearly null perturber
    norm can make the raw gap look complex even for an exact eigenvector.  A
    direct gap-gate failure is therefore accepted only when the numerator is
    within an explicit absolute noise allowance *and* both the imaginary
    energy and real-projection shift have small cancellation-free L1 bounds.
    """

    norm = np.asarray(norm)
    right_commutator = np.asarray(right_commutator)
    one_sided_gap = np.asarray(one_sided_gap)
    mask = np.asarray(mask, dtype=bool)
    if not (
        norm.shape
        == right_commutator.shape
        == one_sided_gap.shape
        == mask.shape
    ):
        raise ValueError("one-sided SI audit arrays or mask have different shapes")

    tolerances = {
        "gap_atol": float(gap_atol),
        "gap_rtol": float(gap_rtol),
        "numerator_noise_allowance": float(numerator_noise_allowance),
        "energy_imag_l1_tol": float(energy_imag_l1_tol),
        "projection_shift_l1_tol": float(projection_shift_l1_tol),
    }
    if any(
        not np.isfinite(value) or value < 0.0
        for value in tolerances.values()
    ):
        raise ValueError("strict-SI audit tolerances must be finite and non-negative")

    selected_norm = np.asarray(norm[mask].real, dtype=float)
    selected_numerator = right_commutator[mask]
    selected_gap = one_sided_gap[mask]
    selected_flat = np.flatnonzero(mask)
    if not selected_norm.size:
        diagnostics = {
            **_scalar_reality_diagnostics(
                one_sided_gap,
                mask,
                atol=tolerances["gap_atol"],
                rtol=tolerances["gap_rtol"],
            ),
            "strict_si_compatible": True,
            "direct_gap_gate_passed": True,
            "raw_numerator_gate_passed": True,
            "positive_denominator_gate_passed": True,
            "roundoff_limited_near_null_count": 0,
            "roundoff_limited_near_null_indices": [],
            "maximum_numerator_imaginary_part": 0.0,
            "maximum_numerator_imaginary_index": [],
            "maximum_numerator_imaginary_to_limit_ratio": 0.0,
            "maximum_numerator_ratio_index": [],
            "imaginary_energy_l1": 0.0,
            "imaginary_energy_l1_tolerance": tolerances[
                "energy_imag_l1_tol"
            ],
            "imaginary_energy_l1_gate_passed": True,
            "real_projection_shift_l1": 0.0,
            "real_projection_shift_l1_tolerance": tolerances[
                "projection_shift_l1_tol"
            ],
            "real_projection_shift_l1_gate_passed": True,
            "numerator_noise_allowance": tolerances[
                "numerator_noise_allowance"
            ],
            "numerical_policy": "explicit-calibrated-numerator-allowance",
        }
        return selected_norm, diagnostics

    if (
        not np.all(np.isfinite(selected_norm))
        or not np.all(np.isfinite(selected_numerator))
        or not np.all(np.isfinite(selected_gap))
    ):
        raise FloatingPointError(
            f"root {root} subspace {subspace}: one-sided SI audit contains "
            "non-finite inputs"
        )

    gap_imag = np.abs(selected_gap.imag)
    gap_limit = tolerances["gap_atol"] + tolerances["gap_rtol"] * np.maximum(
        1.0, np.abs(selected_gap.real)
    )
    numerator_imag = np.abs(selected_numerator.imag)
    numerator_limit = (
        tolerances["numerator_noise_allowance"] + selected_norm * gap_limit
    )
    direct_gap_pass = gap_imag <= gap_limit
    numerator_pass = numerator_imag <= numerator_limit
    near_null = (
        ~direct_gap_pass
        & (
            selected_norm * gap_limit
            < tolerances["numerator_noise_allowance"]
        )
        & numerator_pass
    )
    gap_accepted = direct_gap_pass | near_null
    positive = selected_gap.real > denominator_tol

    with np.errstate(divide="ignore", invalid="ignore", over="ignore"):
        complex_energy = -selected_norm / selected_gap
        projected_energy = -selected_norm / selected_gap.real
    finite_energies = np.all(np.isfinite(complex_energy)) and np.all(
        np.isfinite(projected_energy)
    )
    if not finite_energies:
        raise FloatingPointError(
            f"root {root} subspace {subspace}: one-sided SI energy audit "
            "produced non-finite values"
        )
    imaginary_energy_l1 = float(np.sum(np.abs(complex_energy.imag)))
    projection_shift_l1 = float(
        np.sum(np.abs(projected_energy - complex_energy.real))
    )
    energy_imag_pass = (
        imaginary_energy_l1 <= tolerances["energy_imag_l1_tol"]
    )
    projection_shift_pass = (
        projection_shift_l1 <= tolerances["projection_shift_l1_tol"]
    )
    strict_compatible = bool(
        np.all(gap_accepted)
        and np.all(numerator_pass)
        and np.all(positive)
        and finite_energies
        and energy_imag_pass
        and projection_shift_pass
    )

    def full_index(local_index):
        return [
            int(index)
            for index in np.unravel_index(
                int(selected_flat[int(local_index)]), mask.shape
            )
        ]

    numerator_ratio = np.divide(
        numerator_imag,
        numerator_limit,
        out=np.full_like(numerator_imag, np.inf, dtype=float),
        where=numerator_limit > 0.0,
    )
    numerator_max = int(np.argmax(numerator_imag))
    numerator_ratio_max = int(np.argmax(numerator_ratio))
    near_null_local = np.flatnonzero(near_null)
    diagnostics = {
        **_scalar_reality_diagnostics(
            one_sided_gap,
            mask,
            atol=tolerances["gap_atol"],
            rtol=tolerances["gap_rtol"],
        ),
        "strict_si_compatible": strict_compatible,
        "direct_gap_gate_passed": bool(np.all(direct_gap_pass)),
        "raw_numerator_gate_passed": bool(np.all(numerator_pass)),
        "positive_denominator_gate_passed": bool(np.all(positive)),
        "roundoff_limited_near_null_count": int(len(near_null_local)),
        "roundoff_limited_near_null_indices": [
            full_index(index) for index in near_null_local
        ],
        "maximum_numerator_imaginary_part": float(
            numerator_imag[numerator_max]
        ),
        "maximum_numerator_imaginary_index": full_index(numerator_max),
        "maximum_numerator_imaginary_to_limit_ratio": float(
            numerator_ratio[numerator_ratio_max]
        ),
        "maximum_numerator_ratio_index": full_index(numerator_ratio_max),
        "imaginary_energy_l1": imaginary_energy_l1,
        "imaginary_energy_l1_tolerance": tolerances["energy_imag_l1_tol"],
        "imaginary_energy_l1_gate_passed": bool(energy_imag_pass),
        "real_projection_shift_l1": projection_shift_l1,
        "real_projection_shift_l1_tolerance": tolerances[
            "projection_shift_l1_tol"
        ],
        "real_projection_shift_l1_gate_passed": bool(projection_shift_pass),
        "numerator_noise_allowance": tolerances[
            "numerator_noise_allowance"
        ],
        "numerical_policy": "explicit-calibrated-numerator-allowance",
    }
    if enforce and not strict_compatible:
        _warn_numerical(
            f"root {root} subspace {subspace}: one-sided SI denominator "
            "audit failed; "
            f"max |Im gap|={float(np.max(gap_imag)):.3e}, "
            f"max numerator ratio={float(np.max(numerator_ratio)):.3e}, "
            f"Im(E) L1={imaginary_energy_l1:.3e}, "
            f"projection shift L1={projection_shift_l1:.3e}"
        )
    return selected_gap.real, diagnostics


def _validate_zero_norm_commutator(
    values,
    mask,
    *,
    root,
    subspace,
    atol,
    rtol,
):
    """Gate and describe the Hermitian numerator of discarded perturbers."""

    values = np.asarray(values)
    mask = np.asarray(mask, dtype=bool)
    if values.shape != mask.shape:
        raise ValueError("zero-norm commutator array and mask have different shapes")
    selected = values[mask]
    if not np.all(np.isfinite(selected)):
        raise FloatingPointError(
            f"root {root} subspace {subspace}: zero-norm Dyall commutator "
            "contains non-finite values"
        )
    if not selected.size:
        return {
            "maximum_absolute_value": 0.0,
            "maximum_absolute_index": [],
            "acceptance_limit_at_maximum": float(atol + rtol),
            "gate_passed": True,
        }

    magnitude = np.abs(selected)
    limit = atol + rtol * np.maximum(1.0, np.abs(selected.real))
    local_index = int(np.argmax(magnitude))
    selected_flat = np.flatnonzero(mask)
    full_index = np.unravel_index(
        int(selected_flat[local_index]), values.shape
    )
    gate_passed = bool(magnitude[local_index] <= limit[local_index])
    if not gate_passed:
        _warn_numerical(
            f"root {root} subspace {subspace}: a zero-norm perturber has "
            f"nonzero Dyall commutator {float(magnitude[local_index]):.3e} "
            f"at {full_index}"
        )
    return {
        "maximum_absolute_value": float(magnitude[local_index]),
        "maximum_absolute_index": [int(index) for index in full_index],
        "acceptance_limit_at_maximum": float(limit[local_index]),
        "gate_passed": gate_passed,
    }


_execution_context = _utils._execution_context


def _evaluate_wick_subspaces(
    eris,
    pdms,
    core_energy,
    virtual_energy,
    *,
    root=0,
    scalar_atol=1.0e-10,
    scalar_rtol=1.0e-9,
    norm_tol=1.0e-14,
    denominator_tol=1.0e-12,
    denominator_mode="strict_si",
    si_gap_imag_atol=1.0e-10,
    si_gap_imag_rtol=1.0e-9,
    si_numerator_noise_allowance=1.0e-12,
    si_energy_imag_l1_tol=1.0e-10,
    si_projection_shift_l1_tol=1.0e-12,
    contraction_backend=_DEFAULT_CONTRACTION_BACKEND,
    strong_contraction_groups=None,
    strong_contraction_group_atol=1.0e-10,
    strong_contraction_group_rtol=1.0e-9,
    return_arrays=False,
    return_timings=False,
    return_diagnostics=False,
):
    """Evaluate all generated equations in the supplied semicanonical basis."""

    denominator_mode = _normalize_denominator_mode(denominator_mode)
    contraction_backend = _normalize_contraction_backend(contraction_backend)
    if strong_contraction_groups is not None and return_arrays:
        raise NotImplementedError(
            "return_arrays=True is not yet available with explicit "
            "strong-contraction groups"
        )
    normalized_groups = None
    if strong_contraction_groups is not None:
        normalized_groups = _normalize_strong_contraction_groups(
            strong_contraction_groups,
            eris,
            core_energy,
            virtual_energy,
            atol=strong_contraction_group_atol,
            rtol=strong_contraction_group_rtol,
        )
    if contraction_backend == "pytblis":
        _validate_tblis_operand_dtypes(
            [(f"h{key}", eris.get_h1eff(key)) for key in _H1_KEYS]
            + [(f"w{key}", eris.get_phys(key)) for key in _W_KEYS]
            + [(f"dm{rank}", density) for rank, density in enumerate(pdms, 1)]
        )
    # Block2 emits source containing ``np.einsum``.  That global name is
    # resolved only here at exec time, so the cached source is backend-agnostic.
    wick_globals = {
        "np": _wick_einsum_namespace(contraction_backend),
    }
    equations = _compile_wick_equations()
    base_context = _execution_context(eris, pdms)
    sub_eners = {}
    sub_norms = {}
    sub_gaps = {}
    arrays = {}
    timings = {}
    realness_diagnostics = {}

    for key in SUBSPACE_ORDER:
        subspace_start = time.perf_counter()
        shape = _free_index_shape(key, eris)
        integral_dtypes = tuple(
            eris.get_h1eff(block).dtype for block in _H1_KEYS
        ) + tuple(eris.get_phys(block).dtype for block in _W_KEYS)
        dtype = np.result_type(
            np.complex128,
            *integral_dtypes,
            *(density.dtype for density in pdms),
        )
        norm = np.zeros(shape, dtype=dtype)
        right_commutator = np.zeros(shape, dtype=dtype)
        left_commutator = np.zeros(shape, dtype=dtype)
        local_context = dict(base_context)
        local_context.update(norm=norm)
        exec(equations.norm_code[key], wick_globals, local_context)
        local_context["commutator"] = right_commutator
        exec(
            equations.right_commutator_code[key],
            wick_globals,
            local_context,
        )
        local_context["commutator"] = left_commutator
        exec(
            equations.left_commutator_code[key],
            wick_globals,
            local_context,
        )
        ordered = _strict_pair_mask(key, shape)
        branch_diagnostics = _require_adjoint_pair(
            left_commutator,
            right_commutator,
            ordered,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        orbital_gap = _orbital_gap(key, core_energy, virtual_energy)
        raw_ordered_dimension = int(np.count_nonzero(ordered))
        if normalized_groups is None:
            grouping_diagnostics = {
                "enabled": False,
                "raw_ordered_dimension": raw_ordered_dimension,
                "contracted_group_dimension": raw_ordered_dimension,
                "maximum_orbital_gap_spread": 0.0,
                "orbital_gap_tolerance_at_maximum": float(
                    strong_contraction_group_atol
                    + strong_contraction_group_rtol
                ),
            }
        else:
            grouped, orbital_gap, grouping_diagnostics = (
                _group_strong_contraction_arrays(
                    key,
                    (norm, right_commutator, left_commutator),
                    orbital_gap,
                    ordered,
                    normalized_groups,
                    eris,
                    atol=strong_contraction_group_atol,
                    rtol=strong_contraction_group_rtol,
                )
            )
            norm, right_commutator, left_commutator = grouped
            shape = norm.shape
            ordered = np.ones(shape, dtype=bool)
        orbital_gap = orbital_gap.astype(dtype, copy=False)

        # This reconciles two independently contracted representations of the
        # *same one-sided* scalar.  In exact arithmetic left.conj() == right,
        # so unlike the Hermitian half-sum below it does not remove a physical
        # one-sided imaginary residual.  Explicit symmetry-partner channels,
        # when requested, have already been summed above: the nonlinear SC
        # denominator must be formed only after that sum.
        si_right_commutator = 0.5 * (
            right_commutator + left_commutator.conj()
        )
        commutator = 0.5 * (right_commutator + left_commutator)

        selected_norm = norm[ordered]
        selected_norm = _require_real(
            selected_norm,
            root=root,
            subspace=key,
            quantity="norm",
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        if np.any(selected_norm < -norm_tol):
            minimum = float(np.min(selected_norm))
            _warn_numerical(
                f"root {root} subspace {key}: negative norm {minimum:.3e}"
            )

        nonzero_flat = selected_norm > norm_tol
        nonzero = np.zeros(shape, dtype=bool)
        nonzero[ordered] = nonzero_flat
        selected_commutator = _require_real(
            commutator[nonzero],
            root=root,
            subspace=key,
            quantity="Hermitian Dyall commutator",
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        zero_norm = ordered & ~nonzero
        zero_norm_diagnostics = _validate_zero_norm_commutator(
            commutator,
            zero_norm,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        right_zero_norm_diagnostics = _validate_zero_norm_commutator(
            right_commutator,
            zero_norm,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        left_zero_norm_diagnostics = _validate_zero_norm_commutator(
            left_commutator,
            zero_norm,
            root=root,
            subspace=key,
            atol=scalar_atol,
            rtol=scalar_rtol,
        )
        one_sided_gap = orbital_gap.copy()
        hermitianized_gap = orbital_gap.copy()
        if np.any(nonzero):
            retained_norm = selected_norm[nonzero_flat]
            one_sided_gap[nonzero] += (
                si_right_commutator[nonzero] / retained_norm
            )
            hermitianized_gap[nonzero] += (
                selected_commutator / retained_norm
            )
            si_real_gap, one_sided_diagnostics = (
                _audit_one_sided_si_denominator(
                    norm,
                    si_right_commutator,
                    one_sided_gap,
                    nonzero,
                    root=root,
                    subspace=key,
                    gap_atol=si_gap_imag_atol,
                    gap_rtol=si_gap_imag_rtol,
                    numerator_noise_allowance=si_numerator_noise_allowance,
                    energy_imag_l1_tol=si_energy_imag_l1_tol,
                    projection_shift_l1_tol=si_projection_shift_l1_tol,
                    denominator_tol=denominator_tol,
                    enforce=denominator_mode == "strict_si",
                )
            )
            if denominator_mode == "strict_si":
                real_gap = si_real_gap
                selected_gap = one_sided_gap.copy()
            else:
                real_gap = _require_real(
                    hermitianized_gap[nonzero],
                    root=root,
                    subspace=key,
                    quantity="Hermitianized Dyall denominator",
                    atol=scalar_atol,
                    rtol=scalar_rtol,
                )
                selected_gap = hermitianized_gap.copy()
            selected_gap[nonzero] = real_gap
            if np.any(real_gap <= denominator_tol):
                minimum = float(np.min(real_gap))
                raise FloatingPointError(
                    f"root {root} subspace {key}: non-positive or near-zero "
                    f"Dyall denominator {minimum:.3e}"
                )
            contribution = -np.sum(selected_norm[nonzero_flat] / real_gap)
            gap_min = float(np.min(real_gap))
            gap_max = float(np.max(real_gap))
        else:
            contribution = 0.0
            gap_min = np.nan
            gap_max = np.nan
            selected_gap = (
                one_sided_gap
                if denominator_mode == "strict_si"
                else hermitianized_gap
            )
            _si_real_gap, one_sided_diagnostics = (
                _audit_one_sided_si_denominator(
                    norm,
                    si_right_commutator,
                    one_sided_gap,
                    nonzero,
                    root=root,
                    subspace=key,
                    gap_atol=si_gap_imag_atol,
                    gap_rtol=si_gap_imag_rtol,
                    numerator_noise_allowance=si_numerator_noise_allowance,
                    energy_imag_l1_tol=si_energy_imag_l1_tol,
                    projection_shift_l1_tol=si_projection_shift_l1_tol,
                    denominator_tol=denominator_tol,
                    enforce=denominator_mode == "strict_si",
                )
            )

        class_diagnostics = {
            **branch_diagnostics,
            "contraction_backend": contraction_backend,
            "denominator_mode": denominator_mode,
            "selected_denominator_source": (
                "reconciled_right_si"
                if denominator_mode == "strict_si"
                else "hermitian_half_sum"
            ),
            "norm": _scalar_reality_diagnostics(
                norm, ordered, atol=scalar_atol, rtol=scalar_rtol
            ),
            "hermitian_commutator": _scalar_reality_diagnostics(
                commutator, ordered, atol=scalar_atol, rtol=scalar_rtol
            ),
            "one_sided_denominator": one_sided_diagnostics,
            "hermitianized_denominator": _scalar_reality_diagnostics(
                hermitianized_gap,
                nonzero,
                atol=scalar_atol,
                rtol=scalar_rtol,
            ),
            "zero_norm_hermitian_commutator": zero_norm_diagnostics,
            "zero_norm_right_commutator": right_zero_norm_diagnostics,
            "zero_norm_left_commutator": left_zero_norm_diagnostics,
            "strong_contraction_grouping": grouping_diagnostics,
            "minimum_retained_norm": (
                float(np.min(selected_norm[nonzero_flat]))
                if np.any(nonzero_flat)
                else None
            ),
            "ordered_dimension": int(np.count_nonzero(ordered)),
            "raw_ordered_dimension": raw_ordered_dimension,
            "retained_dimension": int(np.count_nonzero(nonzero_flat)),
            "discarded_zero_norm_dimension": int(np.count_nonzero(zero_norm)),
        }
        realness_diagnostics[key] = class_diagnostics

        sub_eners[key] = float(contribution)
        sub_norms[key] = float(np.sum(np.maximum(selected_norm, 0.0)))
        sub_gaps[key] = (gap_min, gap_max)
        if return_arrays:
            arrays[key] = {
                "norm": norm,
                "commutator": commutator,
                "right_commutator": right_commutator,
                "left_commutator": left_commutator,
                "si_right_commutator": si_right_commutator,
                "selected_commutator": (
                    si_right_commutator
                    if denominator_mode == "strict_si"
                    else commutator
                ),
                "orbital_gap": _orbital_gap(
                    key, core_energy, virtual_energy
                ),
                "denominator": selected_gap,
                "one_sided_denominator": one_sided_gap,
                "hermitianized_denominator": hermitianized_gap,
                "ordered": ordered,
                "nonzero": nonzero,
            }
        timings[key] = time.perf_counter() - subspace_start

    root_imaginary_energy_l1 = float(
        sum(
            diagnostics["one_sided_denominator"]["imaginary_energy_l1"]
            for diagnostics in realness_diagnostics.values()
        )
    )
    root_projection_shift_l1 = float(
        sum(
            diagnostics["one_sided_denominator"]["real_projection_shift_l1"]
            for diagnostics in realness_diagnostics.values()
        )
    )
    root_energy_gate_passed = bool(
        root_imaginary_energy_l1 <= si_energy_imag_l1_tol
    )
    root_projection_gate_passed = bool(
        root_projection_shift_l1 <= si_projection_shift_l1_tol
    )
    root_strict_si_compatible = bool(
        root_energy_gate_passed
        and root_projection_gate_passed
        and all(
            diagnostics["one_sided_denominator"]["strict_si_compatible"]
            for diagnostics in realness_diagnostics.values()
        )
    )
    root_audit = {
        "strict_si_compatible": root_strict_si_compatible,
        "imaginary_energy_l1": root_imaginary_energy_l1,
        "imaginary_energy_l1_tolerance": float(si_energy_imag_l1_tol),
        "imaginary_energy_l1_gate_passed": root_energy_gate_passed,
        "real_projection_shift_l1": root_projection_shift_l1,
        "real_projection_shift_l1_tolerance": float(
            si_projection_shift_l1_tol
        ),
        "real_projection_shift_l1_gate_passed": root_projection_gate_passed,
    }
    for diagnostics in realness_diagnostics.values():
        diagnostics["root_one_sided_si_audit"] = dict(root_audit)
    if denominator_mode == "strict_si" and not root_strict_si_compatible:
        _warn_numerical(
            f"root {root}: aggregate one-sided SI denominator audit failed; "
            f"Im(E) L1={root_imaginary_energy_l1:.3e}, "
            f"projection shift L1={root_projection_shift_l1:.3e}"
        )

    result = (sub_eners, sub_norms, sub_gaps)
    if return_arrays:
        result += (arrays,)
    if return_timings:
        result += (timings,)
    if return_diagnostics:
        result += (realness_diagnostics,)
    return result


_maximum_abs = _utils._maximum_abs
_leading_chunks = _utils._leading_chunks
_all_finite_chunked = _utils._all_finite_chunked
_maximum_abs_chunked = _utils._maximum_abs_chunked
_maximum_abs_relation = _utils._maximum_abs_relation
validate_pdms = _utils.validate_pdms
_root_ket = _utils._root_ket
_make_rdm = _utils._make_rdm
make_rdm1 = _utils.make_rdm1
make_rdm2 = _utils.make_rdm2
make_rdm3 = _utils.make_rdm3
make_rdm4 = _utils.make_rdm4
make_dm1234 = _utils.make_dm1234
_rotate_eris = _utils._rotate_eris
_DEFAULT_AO2MO_ROUNDOFF_FACTOR = _utils._DEFAULT_AO2MO_ROUNDOFF_FACTOR
_SUPPORTED_AO2MO_DTYPES = _utils._SUPPORTED_AO2MO_DTYPES
_SYMMETRY_COMPARISON_PATHS = _utils._SYMMETRY_COMPARISON_PATHS
_REAL_OPS_PER_REAL_MULTIPLY_ADD = _utils._REAL_OPS_PER_REAL_MULTIPLY_ADD
_REAL_OPS_PER_COMPLEX_MULTIPLY_ADD = (
    _utils._REAL_OPS_PER_COMPLEX_MULTIPLY_ADD
)
_require_supported_ao2mo_dtype = _utils._require_supported_ao2mo_dtype
_roundoff_gamma = _utils._roundoff_gamma
_ao2mo_roundoff_policy = _utils._ao2mo_roundoff_policy
_project_dense_mo_integrals = _utils._project_dense_mo_integrals
_dense_eris_from_mc = _utils._dense_eris_from_mc
_reference_energy = _utils._reference_energy

# Numerical controls shared by the state-specific and QD-SC drivers.
_SC_NUMERICAL_DEFAULTS = (
    ("integral_roundoff_factor", _DEFAULT_AO2MO_ROUNDOFF_FACTOR),
    ("scalar_atol", 1.0e-10),
    ("scalar_rtol", 1.0e-9),
    ("rdm_atol", _utils._DEFAULT_RDM_ATOL),
    ("rdm_rtol", _utils._DEFAULT_RDM_RTOL),
    ("rdm_work_memory", _utils._DEFAULT_RDM_WORK_MEMORY),
    ("norm_tol", 1.0e-14),
    ("denominator_tol", _utils._DEFAULT_DENOMINATOR_TOL),
    ("si_gap_imag_atol", 1.0e-10),
    ("si_gap_imag_rtol", 1.0e-9),
    ("si_numerator_noise_allowance", 1.0e-12),
    ("si_energy_imag_l1_tol", 1.0e-10),
    ("si_projection_shift_l1_tol", 1.0e-12),
    ("strong_contraction_group_atol", 1.0e-10),
    ("strong_contraction_group_rtol", 1.0e-9),
)


@dataclass(frozen=True)
class _PreparedSCRoot:
    """One fully audited state-specific row for SS or QD-SC-NEVPT2."""

    root: int
    reference_energy: float
    reference_residual_bound: float
    scalar_tolerance: float
    mo_coeff: np.ndarray
    orbital_energy: np.ndarray
    eris: Any
    eris_basis: str
    core_energy: np.ndarray
    virtual_energy: np.ndarray
    pdms123: tuple[np.ndarray, np.ndarray, np.ndarray] | None
    subspace_arrays: dict[str, dict[str, np.ndarray]] | None
    subspace_energies: dict[str, float]
    subspace_norms: dict[str, float]
    subspace_gaps: dict[str, tuple[float, float]]
    subspace_diagnostics: dict[str, dict[str, Any]]
    subspace_times: dict[str, float]
    rdm_diagnostics: dict[str, Any]
    integral_symmetry_diagnostics: dict[str, Any] | None
    pdm_time: float
    integral_time: float
    strict_si_compatible: bool
    e_corr: float


class WickX2CSCNEVPT2(lib.StreamObject):
    """State-specific dense spinor SC-NEVPT2 generated with Block2 Wick."""

    def __init__(self, mc, frozen=0):
        if _has_frozen_orbitals(frozen) or _has_frozen_orbitals(
            getattr(mc, "frozen", None)
        ):
            raise NotImplementedError("nonzero frozen spinors are outside dense v1")
        self._mc = mc
        self._scf = mc._scf
        self.mol = self._scf.mol
        self.verbose = getattr(mc, "verbose", self.mol.verbose)
        self.stdout = getattr(mc, "stdout", self.mol.stdout)
        self.root = 0
        self.mo_coeff = getattr(mc, "mo_coeff", None)
        self.mo_energy = getattr(mc, "mo_energy", None)
        self.canonicalized = False
        self.eris = None
        self.eris_basis = None
        self.e_corr = None
        self.reference_energy = None
        self.sub_eners = {}
        self.sub_norms = {}
        self.sub_denominators = {}
        self.sub_realness_diagnostics = {}
        self.sub_times = {}
        self.rdm_diagnostics = None
        self.integral_symmetry_diagnostics = None
        for name, value in _SC_NUMERICAL_DEFAULTS:
            setattr(self, name, value)
        self.denominator_mode = "strict_si"
        self.contraction_backend = _DEFAULT_CONTRACTION_BACKEND
        self.strong_contraction_groups = None
        self.strict_si_compatible = None
        self.scalar_tolerance = None
        self.reference_residual_bound = None
        self.frozen = 0
        self._keys = set(self.__dict__)

    @property
    def e_tot(self):
        if self.e_corr is None:
            return None
        return np.asarray(self.reference_energy) + np.asarray(self.e_corr)

    def _semicanonicalize(self, mc, mo_coeff, dm1, root):
        return _utils.semicanonicalize(
            mc,
            mo_coeff,
            dm1,
            root,
            canonicalized=self.canonicalized,
            mo_energy=self.mo_energy,
            verbose=self.verbose,
        )

    def _prepare_sc_root(
        self,
        mc,
        *,
        mo_coeff,
        pdms,
        eris,
        eris_basis,
        root,
        denominator_mode,
        contraction_backend,
        strong_contraction_groups=None,
        return_arrays=False,
        compact_eris=False,
        retain_pdms123=False,
    ) -> _PreparedSCRoot:
        """Prepare one audited multipartitioning row without committing state.

        This is the single numerical path used by both the public
        state-specific kernel and the QD driver.  It deliberately calls
        the instance ``_semicanonicalize`` hook so injected and
        subclass-provided canonicalization policies remain valid.
        """

        reference_energy = _reference_energy(mc, root)
        solver = mc.fcisolver
        residual_bound = getattr(solver, "convergence_info", {}).get(
            "local_residual_bound", 0.0
        )
        residual_bound = float(residual_bound)
        if not np.isfinite(residual_bound) or residual_bound < 0.0:
            residual_bound = 0.0
        # The requested local eigensolver threshold is useful provenance, but
        # is not a measured contraction-error bound and therefore does not
        # relax either the strict-SI or Hermitianized scalar checks.
        scalar_tolerance = float(self.scalar_atol)

        pdm_start = time.perf_counter()
        if pdms is None:
            pdms = make_dm1234(mc.fcisolver, root=root)
        solver_nelecas = getattr(mc.fcisolver, "nelecas", None)
        if solver_nelecas is None:
            solver_nelecas = mc.nelecas
        pdms, rdm_diagnostics = validate_pdms(
            pdms,
            int(mc.ncas),
            _total_nelec(solver_nelecas),
            atol=self.rdm_atol,
            rtol=self.rdm_rtol,
            work_memory=self.rdm_work_memory,
        )
        retained_pdms123 = tuple(pdms[:3]) if retain_pdms123 else None
        pdm_time = time.perf_counter() - pdm_start

        integral_start = time.perf_counter()
        original_mo = np.asarray(mo_coeff)
        semicanonical_mo, orbital_energy = self._semicanonicalize(
            mc, original_mo, pdms[0], root
        )
        if eris is None:
            prepared_eris = _dense_eris_from_mc(
                mc,
                semicanonical_mo,
                roundoff_factor=self.integral_roundoff_factor,
            )
            integral_symmetry_diagnostics = getattr(
                prepared_eris, "symmetry_diagnostics", None
            )
            if compact_eris:
                prepared_eris = _compact_wick_eris(prepared_eris)
        else:
            if not isinstance(eris, spinor_helper._SpinorERIs):
                raise TypeError(
                    "eris must be a spinor_helper._SpinorERIs instance"
                )
            if (eris.ncore, eris.ncas, eris.nmo) != (
                int(mc.ncore),
                int(mc.ncas),
                semicanonical_mo.shape[1],
            ):
                raise ValueError("eris partition does not match the CASSCF object")
            prepared_eris = eris
            integral_symmetry_diagnostics = getattr(
                prepared_eris, "symmetry_diagnostics", None
            )
            if (
                eris_basis == "input_mo"
                and not np.array_equal(semicanonical_mo, original_mo)
            ):
                overlap = np.asarray(mc._scf.get_ovlp())
                rotation = original_mo.T.conj() @ overlap @ semicanonical_mo
                if compact_eris:
                    prepared_eris = _rotate_wick_eris(eris, rotation)
                else:
                    prepared_eris = _rotate_eris(eris, rotation)
            elif compact_eris:
                prepared_eris = _compact_wick_eris(eris)
        integral_time = time.perf_counter() - integral_start

        ncore = prepared_eris.ncore
        nocc = prepared_eris.nocc
        core_energy = orbital_energy[:ncore]
        virtual_energy = orbital_energy[nocc:]
        evaluated = _evaluate_wick_subspaces(
            prepared_eris,
            pdms,
            core_energy,
            virtual_energy,
            root=root,
            scalar_atol=scalar_tolerance,
            scalar_rtol=self.scalar_rtol,
            norm_tol=self.norm_tol,
            denominator_tol=self.denominator_tol,
            denominator_mode=denominator_mode,
            si_gap_imag_atol=self.si_gap_imag_atol,
            si_gap_imag_rtol=self.si_gap_imag_rtol,
            si_numerator_noise_allowance=self.si_numerator_noise_allowance,
            si_energy_imag_l1_tol=self.si_energy_imag_l1_tol,
            si_projection_shift_l1_tol=self.si_projection_shift_l1_tol,
            contraction_backend=contraction_backend,
            strong_contraction_groups=strong_contraction_groups,
            strong_contraction_group_atol=(
                self.strong_contraction_group_atol
            ),
            strong_contraction_group_rtol=(
                self.strong_contraction_group_rtol
            ),
            return_arrays=return_arrays,
            return_timings=True,
            return_diagnostics=True,
        )
        if return_arrays:
            (
                sub_eners,
                sub_norms,
                sub_gaps,
                subspace_arrays,
                subspace_times,
                realness_diagnostics,
            ) = evaluated
        else:
            (
                sub_eners,
                sub_norms,
                sub_gaps,
                subspace_times,
                realness_diagnostics,
            ) = evaluated
            subspace_arrays = None
        strict_si_compatible = all(
            diagnostics["root_one_sided_si_audit"]["strict_si_compatible"]
            for diagnostics in realness_diagnostics.values()
        )
        return _PreparedSCRoot(
            root=root,
            reference_energy=reference_energy,
            reference_residual_bound=residual_bound,
            scalar_tolerance=scalar_tolerance,
            mo_coeff=semicanonical_mo,
            orbital_energy=orbital_energy,
            eris=prepared_eris,
            eris_basis="semicanonical",
            core_energy=core_energy,
            virtual_energy=virtual_energy,
            pdms123=retained_pdms123,
            subspace_arrays=subspace_arrays,
            subspace_energies=sub_eners,
            subspace_norms=sub_norms,
            subspace_gaps=sub_gaps,
            subspace_diagnostics=realness_diagnostics,
            subspace_times=subspace_times,
            rdm_diagnostics=rdm_diagnostics,
            integral_symmetry_diagnostics=integral_symmetry_diagnostics,
            pdm_time=pdm_time,
            integral_time=integral_time,
            strict_si_compatible=strict_si_compatible,
            e_corr=float(sum(sub_eners.values())),
        )

    def kernel(
        self,
        mc=None,
        mo_coeff=None,
        pdms=None,
        eris=None,
        eris_basis="input_mo",
        denominator_mode=None,
        root=None,
        contraction_backend=None,
        strong_contraction_groups=None,
        compact_eris=False,
    ):
        """Compute one root-specific SC-NEVPT2 correction.

        ``contraction_backend`` selects ``"pytblis"`` (the default) or the
        NumPy reference implementation for the Block2-generated contractions.
        ``strong_contraction_groups`` is an optional integer label for every
        semicanonical spinor MO.  Equal core or virtual labels are summed
        before forming a denominator; this is required to reproduce a
        spin-free SC contraction from explicit alpha/beta spinors.  Because
        labels describe the final MO columns, this option requires
        ``canonicalized=True``.
        With a dense input-basis ``eris``, ``compact_eris=True`` rotates and
        retains only the blocks used by Wick; the default preserves the
        historical full-ERI result object.
        """

        if mc is None:
            mc = self._mc
        if _has_frozen_orbitals(getattr(mc, "frozen", None)):
            raise NotImplementedError("nonzero frozen spinors are outside dense v1")
        eris_basis = _normalize_eris_basis(eris_basis)
        if denominator_mode is None:
            denominator_mode = self.denominator_mode
        denominator_mode = _normalize_denominator_mode(denominator_mode)
        self.denominator_mode = denominator_mode
        if contraction_backend is None:
            contraction_backend = self.contraction_backend
        contraction_backend = _normalize_contraction_backend(
            contraction_backend
        )
        self.contraction_backend = contraction_backend
        if strong_contraction_groups is None:
            strong_contraction_groups = self.strong_contraction_groups
        else:
            strong_contraction_groups = np.asarray(
                strong_contraction_groups
            ).copy()
            self.strong_contraction_groups = strong_contraction_groups
        if strong_contraction_groups is not None and not self.canonicalized:
            raise ValueError(
                "strong_contraction_groups describes semicanonical MO columns; "
                "set canonicalized=True and supply matching mo_energy"
            )
        if root is None:
            root = self.root
        root = int(root)
        if root < 0:
            raise IndexError("root must be non-negative")
        self.root = root
        if mo_coeff is None:
            mo_coeff = mc.mo_coeff
        mo_coeff = np.asarray(mo_coeff)
        row = self._prepare_sc_root(
            mc,
            mo_coeff=mo_coeff,
            pdms=pdms,
            eris=eris,
            eris_basis=eris_basis,
            root=root,
            denominator_mode=denominator_mode,
            contraction_backend=contraction_backend,
            strong_contraction_groups=strong_contraction_groups,
            return_arrays=False,
            compact_eris=bool(compact_eris),
        )
        self.reference_energy = row.reference_energy
        self.reference_residual_bound = row.reference_residual_bound
        self.scalar_tolerance = row.scalar_tolerance
        self.rdm_diagnostics = row.rdm_diagnostics
        self.mo_coeff = row.mo_coeff
        self.mo_energy = row.orbital_energy
        self.eris = row.eris
        self.eris_basis = row.eris_basis
        self.integral_symmetry_diagnostics = row.integral_symmetry_diagnostics
        self.strict_si_compatible = row.strict_si_compatible

        sub_eners = row.subspace_energies
        sub_norms = row.subspace_norms
        sub_gaps = row.subspace_gaps
        subspace_times = row.subspace_times
        realness_diagnostics = row.subspace_diagnostics
        self.sub_times = {"pdms": row.pdm_time, "eris": row.integral_time}
        self.sub_eners = {}
        self.sub_norms = {}
        self.sub_denominators = {}
        self.sub_realness_diagnostics = {}
        if denominator_mode == "hermitianized" and not self.strict_si_compatible:
            failed = ", ".join(
                key
                for key, diagnostics in realness_diagnostics.items()
                if not diagnostics["one_sided_denominator"][
                    "strict_si_compatible"
                ]
            )
            if not failed:
                failed = "<aggregate L1 gate>"
            logger.warn(
                self,
                "root %d uses denominator_mode=hermitianized; the one-sided "
                "SI audit failed for classes: %s",
                root,
                failed,
            )
        for key in SUBSPACE_ORDER:
            self.sub_eners[key] = sub_eners[key]
            self.sub_norms[key] = sub_norms[key]
            self.sub_denominators[key] = sub_gaps[key]
            self.sub_realness_diagnostics[key] = realness_diagnostics[key]
            self.sub_times[key] = subspace_times[key]
            logger.note(
                self,
                "root %d E(%s-%4s) = %20.14f  norm = %.10g  gap = [%s, %s]",
                root,
                self.__class__.__name__,
                key,
                sub_eners[key],
                sub_norms[key],
                "nan" if np.isnan(sub_gaps[key][0]) else f"{sub_gaps[key][0]:.8g}",
                "nan" if np.isnan(sub_gaps[key][1]) else f"{sub_gaps[key][1]:.8g}",
            )
        self.e_corr = float(sum(self.sub_eners.values()))
        logger.note(
            self,
            "root %d E(reference) = %.16g  E_corr = %.16g  E(total) = %.16g",
            root,
            self.reference_energy,
            self.e_corr,
            self.e_tot,
        )
        logger.info(
            self,
            "root %d contraction_backend=%s denominator_mode=%s "
            "strict_si_compatible=%s; "
            "physical-scalar realness tolerance = %.3e "
            "(configured %.3e; DMRG local threshold bound %.3e is diagnostic only)",
            root,
            contraction_backend,
            denominator_mode,
            self.strict_si_compatible,
            self.scalar_tolerance,
            self.scalar_atol,
            self.reference_residual_bound,
        )
        logger.note(
            self,
            "root %d timings: %s",
            root,
            " | ".join(f"{key}={value:.2f}s" for key, value in self.sub_times.items()),
        )
        return self.e_corr


X2CSCNEVPT2 = WickX2CSCNEVPT2
